### ISSUE TITLE
[Issue]: [Regression] User-created playlists not accessible via CollectionView in v10.8.11

### ISSUE THREAD

**Issue by Chaphasilor** [jellyfin/jellyfin#10272]
### Please describe your bug

Any playlists manually created by a user (as opposed to automatically discovered from e.g. a m3u file) are not returned by the ID if the `parentId` is set to the ID of the `CollectionView`. Afaik, only CollectionViews of type `Music` make use of this feature in the web client.  

Before Jellyfin 10.8.11, the `parentId` would be ignored when fetching `Playlist` items from the API, resulting in the request `<baseUrl>/Users/<userId>/Items?IncludeItemTypes=Playlist&Recursive=true&StartIndex=0&ParentId=<musicTypeCollectionViewId>` to return *any* created playlist (scanned, manually created within the `Music` CollectionView, as well as created in any other CollectionView like `Shows`).  
This of course wasn't ideal either (I don't want to see a playlist of show episodes in my music client), and therefore this was "fixed" in https://github.com/jellyfin/jellyfin/pull/9909 and backported to 10.8.z in https://github.com/jellyfin/jellyfin/pull/9916.

Now only auto-discovered playlists are returned when performing the request above; the user-created playlists can only be found in the `UserView` of `collectionType: playlist`. If this behavior was by design, it would be extremely annoying when building music clients for Jellyfin, and would prevent separating music playlists from video playlists.

**To reproduce:**
1. Set up Jellyfin 10.8.11 (via docker)
2. Import at least a music library that contains at least one m3u playlist file
3. Jellyfin should auto-detect the playlist, and it should show up in the web client under Home > Music > Playlists
4. Create a new playlist and add at least one song to it
5. The newly created playlist is not shown under Home > Music > Playlists, but does show up under Home > Playlists

### Jellyfin Version

Other

### if other:

10.8.11

### Environment

```markdown
- OS: TrueNAS-SCALE-22.12.3.3
- Linux Kernel: ?
- Virtualization: Docker (k3s)
- Clients: Finamp 0.6.17, jellyfin-web 10.8.11
- Browser: Microsoft Edge Dev 119.0.2109.1
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: n/a
- Storage: host path / ZFS dataset
```

### Jellyfin logs

```shell
issue doesn't show up in any logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BloodyIron** [comment]
Playlists created on Jellyfin stopped showing up in Finamp with Jellyfin server 10.8.11, but switched to the 10.8.10 docker image and the issue was addressed immediately. This looks to be a reliably provable regression with 10.8.11.

**Comment by BloodyIron** [comment]
> Playlists created on Jellyfin stopped showing up in Finamp with Jellyfin server 10.8.11, but switched to the 10.8.10 docker image and the issue was addressed immediately. This looks to be a reliably provable regression with 10.8.11.

What's with the downthumbs?... :/

**Comment by exaveal** [comment]
just wanted to notify that I have the same problem - but too stupid to do it right. Currently in vacation and I need Offline-functionality of Finamp. Playlist not working since remote update of my jellyfin server at home. Now I have no music anymore .. fu**

**Comment by drazil100** [comment]
I just updated my server last night to the latest version and my playlists dissapeared. The one I have favorited shows up on the favorites tab but nowhere else. I tried deleting it and am in the process of recreating it but it still doesn't show up in the playlists tab. Strangely, even though I deleted it, the new playlist of the same name is still showing up in my favorites so at least I can still access it.

**Comment by iwillreku3206** [comment]
On Jellyfin unstable, my playlists disappeared around a week ago, and my current workaround  is to downgrade to a version from September, but my playlist's items all disappeared

**Comment by OriCat101** [comment]
Same Issue here. Oddly enough my playlists appear in Feishin but not on Finamp.

**Comment by againstpetra** [comment]
@OriCat101, out of interest which version of Feishin does it work for you?

Thinking it working with Feishin could be related to this: https://github.com/jeffvli/feishin/issues/272

**Comment by ebattenberg** [comment]
Like the others here, I'm on 10.8.11, and my Jellyfin-created playlists do not show up under the music view of the web UI or in Finamp.  They do show up under the top-level Playlist view accessible via the hamburger button on the web UI.

**Comment by OriCat101** [comment]
> @OriCat101, out of interest which version of Feishin does it work for you?

I-m currently running v0.4.1 which is, to my knowledge, the newest version. 
![image](https://github.com/jellyfin/jellyfin/assets/63188591/0121b144-6e2b-48af-88f6-9c13296b9932)

@ebattenberg 
> They do show up under the top-level Playlist view accessible via the hamburger button on the web UI.

same here. They also show up when I try to add a song to a playlist.

**Comment by BloodyIron** [comment]
Considering how reproducible this bug is I think this warrants being added to a milestone or something equivalent. I don't mind sticking to a version for the moment, but I'm not really seeing dev engagement here to start on this matter. Can we get that engagement please? :) As for when, I don't care horribly, just that next steps are started please. Thanks! :D

**Comment by JonasR** [comment]
I can (mostly) confirm this behavior. I was on Truechart's `jellyfin-15.0.15` which comes with the server in version `10.8.11` and did not see the manually created playlists in Finamp. However, I **did** still see them in the Jellyfin web client and Media Player Desktop client. Not sure if I'm misreading this discussion here or if that is different from other people.

Downgrading to `jellyfin-15.0.6` with `10.8.10` made the playlists re-appear in Finamp as well.

**Comment by nielsvanvelzen** [comment]
Closing this issue as it didn't auto-close when #10406 was merged. The issue is fixed and will be released with Jellyfin 10.8.12.

**Comment by BloodyIron** [comment]
Confirmed issue corrected for me in v10.8.12, yay! Thanks! \o/

**Comment by mikedrawback** [comment]
Has this come back? I can't see playlists on Android Auto anymore since upgrading to 10.9.6

**Comment by mooninite** [comment]
I am not seeing any issues with playlists on Finamp 0.6.23 and Jellyfin 10.9.6.

**Comment by viasux** [comment]
My playlists are empty on v10.9.7
![image](https://github.com/jellyfin/jellyfin/assets/47131867/f20c6738-93aa-457c-a3dd-e8ebeb471e13)

**Comment by b4too** [comment]
If I'm not mistaken, as long as this playlist was not created by the user you are currently logged in with, this is expected behavior since 10.9.x.

**Comment by viasux** [comment]
> If I'm not mistaken, as long as this playlist was not created by the user you are currently logged in with, this is expected behavior since 10.9.x.

it was created by me, the logged in user

**Comment by b4too** [comment]
> > If I'm not mistaken, as long as this playlist was not created by the user you are currently logged in with, this is expected behavior since 10.9.x.
> 
> it was created by me, the logged in user

I misread your post and noticed it just after posting... I deleted my response in hope it would not be read but I wasn't fast enough

**Comment by Chaphasilor** [comment]
@viasux if you can reproduce this issue, especially on a fresh install, you should create a new issue for it, since this one is already closed :)

**Comment by viasux** [comment]
> @viasux if you can reproduce this issue, especially on a fresh install, you should create a new issue for it, since this one is already closed :)

I don't really have the time to test on a new install and I don't want to delete my playlists again. I might make another issue anyways though, and add more info if it happens again.

**Comment by exaveal** [comment]
problem exists again for Finamp and Android Car/Drive Mode. No playlists showing up.

**Comment by Chaphasilor** [comment]
@exaveal please report Finamp-related issues to the Finamp repository (https://github.com/jmshrv/finamp). You can also try the regular Jellyfin Android app, it also supports Android Auto :)

**Comment by exaveal** [comment]
Its a backend problem. It's all described here. The problem exists also in Android Auto for Jellyfin, not for Finamp. The problem exists in Finamp AND in Jellyfin Android Auto.

**Comment by Chaphasilor** [comment]
@exaveal if it's a backend problem, it shouldn't be specific to Android Auto. Either way, this issue has been closed for a while, so it's probably better to create a new issue and reference this older issue within it. Otherwise it won't receive any attention :)
