### ISSUE TITLE
[Issue]: xml special characters in collection names result in multiple escape sequences added to the name over time

### ISSUE THREAD

**Issue by TheMelmacian** [jellyfin/jellyfin#10767]
### Please describe your bug

XML special characters like `&`, `<` and `>` will be escaped when saved in the collection.xml. So every `&` will become `&amp;`.
The `Lilo & Stitch Collection` will be saved as `Lilo &amp; Stitch Collection` for example. And the collection folder is also named accordingly.
Loading and saving from XML should un-escape/escape these characters correctly.
At first everything seems fine. But after some time something in the loading or saving process goes wrong and the ampersand from the escape sequence is escaped again, which will result in `&amp;amp;` -> `Lilo &amp;amp; Stitch Collection`.
At this time the problem should also be visible in the UI, because even if un-escaped correctly the name now contains `&amp;` instead of a single `&`

Eventually this will repeat itself. `&amp;amp;` -> `&amp;amp;amp;` -> `&amp;amp;amp;amp;` -> ...

The bug was initially reported in the tmdbboxsets plugin repo:
https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/73 (includes logs and screenshots)
https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/37

I couldn't find any code in the boxset plugin that could trigger this behaviour since the boxset name is extracted from the movie metadata and boxset creation is handled by the server code.
So as far as I can tell it's not a problem with the plugin.

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 6.1.0-0.deb11.7
- Virtualization: Docker
- Storage: ext4 HDD
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheMelmacian** [comment]
Still an issue

**Comment by jamespearson04** [comment]
I deleted affected collections and performed a library scan to replace them following the bot comment, and the issue hasn't reappeared yet, so it may be resolved. Have you tried the same @TheMelmacian?

**Comment by hugalafutro** [comment]
I can 100% reproduce this by deleting the collections and rescanning the media library (JF 10.9.2)

deleting
```
[17:52:26] [INF] [34] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: BoxSet, Name: Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection, Path: /config/data/collections/Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection [boxset], Id: 7377bdb0-5ad2-8f5b-5f41-3d0ddcddd27f
[17:52:26] [INF] [34] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: BoxSet, Name: Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection, Path: /config/data/collections/Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection [boxset], Id: 7377bdb0-5ad2-8f5b-5f41-3d0ddcddd27f
[17:52:30] [INF] [16] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: BoxSet, Name: Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection, Path: /config/data/collections/Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection [boxset], Id: 6dabe56c-410f-ace9-e17f-5e310ba7c4e5
[17:52:30] [INF] [16] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: BoxSet, Name: Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection, Path: /config/data/collections/Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection [boxset], Id: 6dabe56c-410f-ace9-e17f-5e310ba7c4e5
[17:52:39] [INF] [16] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: BoxSet, Name: Philo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Clyde Collection, Path: /config/data/collections/Philo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Clyde Collection [boxset], Id: 61b01d56-5069-1d7a-4372-c505e6d3d22c
[17:52:39] [INF] [16] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: BoxSet, Name: Philo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Clyde Collection, Path: /config/data/collections/Philo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Clyde Collection [boxset], Id: 61b01d56-5069-1d7a-4372-c505e6d3d22c
```

rescanning produced largish log with unrelated spam nothing related to the issue I can spot: https://o.o5.ddns.net/ALcn2, but the collections immediately return with the bad names:
![image](https://github.com/jellyfin/jellyfin/assets/30209689/af5f72d8-83df-4fa5-b851-614f0867f1da)

**Comment by TheMelmacian** [comment]
A temporary workaround / fix:
- navigate to `config/data/collections` of your jellyfin instance
- replace all `&amp;amp;amp;...` to `&` in the affected collection folders
- open the `collection.xml` inside the folders and replace all `&amp;amp;amp;...` to a single `&amp;` in the title (you can't use `&` alone since it is a reserved special character in xml and must be escaped)
  - renaming the collection can also be done in the jellyfin gui
    - must be done before renamimg the folder or after jellyfin recognizes the changed folder name
    - use `&` instead of `&amp;` when you rename the collection in the gui
- wait for the server to recognize the changes or trigger an update of the `collections` library

After some time the bug will resurface but this will prevent the folder and collection names to grow endlessly

**Comment by jerem2772** [comment]
Bug always present in the last version 10.9.7

**Comment by fubar-coder** [comment]
Bug is still there in 10.9.8

**Comment by jerem2772** [comment]
Same with 10.9.9.....

**Comment by brupec** [comment]
Also have the problem with latest version

**Comment by awnumar** [comment]
This issue also exists in 10.9.11

**Comment by felix920506** [comment]
marking confirmed from multiple reports

**Comment by Bumblebrow** [comment]
Issue is still present in 10.10.0. 

Some Collection (Boxset) titles that are affected are:

Bill & Ted's Most Excellent Collection
Dungeons & Dragons Collection
Lilo & Stitch Collection
Prep & Landing Collection

Once the collection is created, folder shows "Bill &amp; Ted's Most Excellent Collection" and editing the title in the Jellyfin UI under metadata to replace the "&amp;" with "&" and locking it doesn't prevent it from changing back to &amp;.

**Comment by jesse-kaufman** [comment]
Still an issue here.

**Comment by Shadowghost** [comment]
I'm not able to reproduce this:
* Having the boxset defined in the NFO properly serializes and deserializes the name
* This also means that the foldername for the collection is created correctly (without `&amp`)
* The same is the case if the boxset is coming from Tmdb

What OSes are you guys using?

**Comment by hugalafutro** [comment]
> What OSes are you guys using?

Docker running on linux, media is bind mounted from nfs 4.1 share

I can 100% reproduce the issue in latest version as described in https://github.com/jellyfin/jellyfin/issues/10767#issuecomment-2118885968

**Comment by TheMelmacian** [comment]
> I'm not able to reproduce this:
> 
>     * Having the boxset defined in the NFO properly serializes and deserializes the name
> 
>     * This also means that the foldername for the collection is created correctly (without `&amp`)
> 
>     * The same is the case if the boxset is coming from Tmdb
> 
> 
> What OSes are you guys using?

I'm running the official Docker image on Debian Linux and all media files are stored on the same machine.

Collection folder name: `Lilo &amp;amp;amp;amp; Stitch Collection [boxset]`
collection.xml entry: `<LocalTitle>Lilo &amp;amp;amp;amp;amp; Stitch Collection</LocalTitle>`
And the corrupted name is also written in the `data` field of the included media: `"TmdbCollectionName": "Lilo &amp;amp;amp;amp;amp; Stitch Collection"`
This is probably why the old collection with the corrupted name resurfaces after the collection is manually renamed or deleted.


I think the problem only surfaces over time when the collections are updated. Probably via the TMDB Box Set plugin or any other Service that updates/checks collections.
On the first collection creation everything is as it should be, but after a while (next update/sync?) the first additional escape sequence is added and the bug starts to be visible (see first post).

Since the ampersand must only be escaped inside the xml file my current guess is:
- Box Set Plugin fetches collection data from TMDB
- API returns `{"id":97461,"name":"Lilo \u0026 Stitch Collection", ...}`
- name is saved in collection XML and database
  - collection XML: `<LocalTitle>Lilo &amp; Stitch Collection</LocalTitle>` (& is reserved in XML and must be escaped)
  - DB: `"TmdbCollectionName": "Lilo & Stitch Collection"`
- in the GUI everything seems fine
- Box Set Plugin runs again
- existing collections are read in from the collection.xml files, but &amp; is probably not unescaped -> &amp; is now part of the name
- when the collections and all items are updated the `&` is escaped again -> `&amp;amp;`
- repeat

**Comment by jesse-kaufman** [comment]
I'm running the linuxserver.io Jellyfin Docker image on Ubuntu 24.04 with my media dir being a bind mount on a btrfs partition (local drive)

What I found is that if I disable the TMDb Box Sets plugin and have "automatically add to collection" enabled for the movies library, I get the double-escaped titles. Any attempt to update the title gets reverted on the next library scan. If I run the TMDb Box Sets scan manually, the titles get corrected and stay corrected.

If I disable "automatically add to collection" on the library and enable the TMDb Box Sets plugin, I get the correctly-escaped title which stays. So that's a working solution for my setup.

**Comment by hugalafutro** [comment]
@jesse-kaufman strange, I get the bug with and without the plugin. I first reported this at the plugin repo, but was told is JF issue.

**Comment by Shadowghost** [comment]
> If I disable "automatically add to collection" on the library and enable the TMDb Box Sets plugin, I get the correctly-escaped title which stays. So that's a working solution for my setup.

This option works without the boxset plugin by grouping movies based on the collection name sourced from the tmdb metadata or nfo (which movies did it group for you?)
What I wrote above is for the deserialization of both of these sources and they work as expected.
If one of you uses NFOs, can you please check the content of the `<set>` tag?

**Comment by hugalafutro** [comment]
Hi, I'm sorry I don't know what deserialization is, but the affected movie has the wrong name in the nfo too. Currently using the plugin. So should I not? I find it very confusing the collections work without the plugin as well - so do I not need it? What does it offer on top of in-built functionality?

In any case with or without it the names always get messed up even if I delete the collection files and fix the names in jellyfin metadata editor, next rescan they're back like this
```
<set>Cheech &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Chong Collection</set>
```

**Comment by Shadowghost** [comment]
I guess you have NFO saving enabled in Jellyfin? If that is the case, what is written in the NFO after you update the name in the collection?

**Comment by hugalafutro** [comment]
- NFO Saving enabled with all 3 checkboxes
- Group films into collections is unchecked
- TMDB Boxsets plugin is enabled

Renaming the collection in jellyfin does not access the movie.nfo of the movie thus the <set> tag remains full of the &amps;

**Comment by TheMelmacian** [comment]
I probably found the cause for this.
After deleting the affected collections and fixing all database entries and .nfo files, the only place where an `&amp;` was present was the nfo (to be XML conform). After the error occurred again I suspected an error in the NfoParser and found something.

After the fix is merged and released, all affected collections need to be deleted and all set entries in the .nfo files manually changed to prevent the error from reoccurring. A re-scan afterwards is probably a good idea to also fix the database entries.

**Comment by TheMelmacian** [comment]
With #13092 merged and released with 10.10.5, the bug is hopefully fixed. But affected collections probably need to be fixed manually:

- correct wrong SET entries in metadata of all affected movies:
  - either refresh metadata and select "replace all existing metadata"
  - or correct `<set>` entries manually in the nfo files of the affected movies (replace `&amp;amp;amp;...` with a single `&amp;`
- rename affected collections; or delete them and wait until jellyfin recreates them

Please report back if the issue resurfaces again.

**Comment by felix920506** [comment]
Closing as linked PR should fix this issue.

**Comment by hugalafutro** [comment]
no bueno

`2025-02-03 06:51:40.471786+00:00[06:51:40] [INF] [1] Main: Jellyfin version: 10.10.5`

path:
`/config/data/collections/Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection [boxset]`

title:
`Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection`

in .nfo
```
  <set>
    <name>Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection</name>
  </set>
```

changed to:
```
  <set>
    <name>Robot Jox &amp; Wars Collection</name>
  </set>
```
in both .nfo's

deleted the collection:
```
2025-02-03 06:54:35.068938+00:00[06:54:35] [INF] [41] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: BoxSet, Name: Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection, Path: /config/data/collections/Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection [boxset], Id: 22b65e0d-64bf-9c59-ba8a-96c76d52a9a5
2025-02-03 06:54:35.073641+00:00[06:54:35] [INF] [41] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: BoxSet, Name: Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection, Path: /config/data/collections/Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection [boxset], Id: 22b65e0d-64bf-9c59-ba8a-96c76d52a9a5
```

rescanned metadata of Robot Jox with replace metadata option:
```
2025-02-03 07:06:23.595386+00:00[07:06:23] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media2/movies2/Robot Jox (1989)/Robot Jox (1989) Bluray-1080p x265.srt" -threads 0 -v warning -print_format json -show_streams -show_format
2025-02-03 07:06:29.550983+00:00[07:06:29] [WRN] [3] Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager: Not all the Tmdb Collection Names are the same for the box set (using the first one): Robot Jox - Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection, Robot Wars - Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection
2025-02-03 07:06:29.551311+00:00[07:06:29] [INF] [3] Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager: Box Set for Robot Jox &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Wars Collection (883303) does not exist. Creating it now!

**Comment by felix920506** [comment]
@hugalafutro when rescanning whatever is in NFOs will take priority. What you are seeing is intended behavior. You will need to manually fix the NFOs.

**Comment by hugalafutro** [comment]
I got this reply in email but don't see it here no idea if it was dm or deleted:
> @hugalafutro when rescanning whatever is in NFOs will take priority. What you are seeing is intended behavior. You will need to manually fix the NFOs.

In the above post I have followed the instructions from https://github.com/jellyfin/jellyfin/issues/10767#issuecomment-2629591143 to the letter and the issue is not resolved.

I have now tried with altogether deleting the `<set>` tags from .nfo, deleting the Collection and rescanning, the issue is still not resolved:
```
2025-02-04 08:02:06.224644+00:00[08:02:06] [WRN] [69] Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager: Not all the Tmdb Collection Names are the same for the box set (using the first one): Lilo & Stitch - Lilo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Stitch Collection, Lilo & Stitch 2: Stitch Has a Glitch - Lilo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Stitch Collection
2025-02-04 08:02:06.224753+00:00[08:02:06] [INF] [69] Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager: Box Set for Lilo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Stitch Collection (97461) does not exist. Creating it now!
```

and it adds this into the .nfo:
```
  <set>
    <name>Lilo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Stitch Collection</name>
  </set>
```

Can you please either tell me what I am doing wrong or re-open this issue?

**Comment by TheMelmacian** [comment]
```
[2025-02-04 21:59:56.501 +00:00] [INF] [19] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "BoxSet", Name: "Lilo &amp; Stitch Collection", Path: "/config/data/collections/Lilo &amp; Stitch Collection [boxset]", Id: 552f262f-160e-62ed-de3c-19442b1ee16a
[2025-02-04 21:59:56.511 +00:00] [INF] [19] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "BoxSet", Name: "Lilo &amp; Stitch Collection", Path: "/config/data/collections/Lilo &amp; Stitch Collection [boxset]", Id: 552f262f-160e-62ed-de3c-19442b1ee16a
[2025-02-04 22:00:56.520 +00:00] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: "collections" ("/config/data/collections") will be refreshed.
[2025-02-04 22:01:18.963 +00:00] [INF] [8] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/videos/MOVIES/Disney/Lilo & Stitch (2002)/Lilo & Stitch (2002).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2025-02-04 22:01:24.962 +00:00] [INF] [8] Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager: Box Set for "Lilo & Stitch Collection" ("97461") does not exist. Creating it now!
[2025-02-04 22:02:00.015 +00:00] [INF] [56] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/videos/MOVIES/Disney/Stitch! The Movie (2003)/Stitch! The Movie (2003).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
```

To make sure all wrong `<set>` entries are replaced in the database
- either refresh metadata with "replace all existing metadata" for **all** items of the collection (check nfo if saving to nfo is activated)
- or replace wrong entries in **all** nfo files of **all** items and refresh metadata with "scan for new or changed files" for **all** items
- delete collection afterwards
- repeat for other affected collections

If this doesn't help, you probably have to remove all affected items inside the database (movies and collections).
But as you can se in my logs, once the wrong entries are no longer present in .nfo and database, the collection is recreated with the correct name.

**Comment by hugalafutro** [comment]
I was at the edge of tears after trying every possible combination of rescans and deleting stuff from .nfo (rescan just put the wrong info back into the .nfo). The only thing that ended up working was physically deleting the movies from within Jellyfin interface, this removed them from the database I guess? Then copying them back without any .nfo and rescanning the Movies library.

It's a massive PITA and I only fixed 1 collection so far, but I'm happy it got finally fixed after all these years, it was driving me crazy.

```
2025-02-05 05:50:15.862197+00:00[05:50:15] [INF] [45] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Movie, Name: Lilo & Stitch, Path: /media/movies/Lilo & Stitch (2002)/Lilo & Stitch (2002) Bluray-1080p x264.mp4, Id: 56983658-6a69-06ac-f11e-840fc5313d8e
2025-02-05 05:50:15.869197+00:00[05:50:15] [INF] [45] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: Movie, Name: Lilo & Stitch, Path: /media/movies/Lilo & Stitch (2002), Id: 56983658-6a69-06ac-f11e-840fc5313d8e
2025-02-05 05:50:21.203116+00:00[05:50:21] [INF] [72] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Movie, Name: Lilo & Stitch 2: Stitch Has a Glitch, Path: /media/movies/Lilo & Stitch 2 Stitch Has a Glitch (2005)/Lilo & Stitch 2 Stitch Has a Glitch (2005) Bluray-1080p x264.mp4, Id: cdfb6aae-cdba-dba1-b0df-f969a10596b0
2025-02-05 05:50:21.209236+00:00[05:50:21] [INF] [72] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: Movie, Name: Lilo & Stitch 2: Stitch Has a Glitch, Path: /media/movies/Lilo & Stitch 2 Stitch Has a Glitch (2005), Id: cdfb6aae-cdba-dba1-b0df-f969a10596b0
2025-02-05 05:50:29.508526+00:00[05:50:29] [WRN] [74] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path /media/movies/Lilo & Stitch (2002)/Lilo & Stitch (2002) Bluray-1080p x264.mp4
2025-02-05 05:50:29.510265+00:00[05:50:29] [WRN] [74] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path /media/movies/Lilo & Stitch 2 Stitch Has a Glitch (2005)/Lilo & Stitch 2 Stitch Has a Glitch (2005) Bluray-1080p x264.mp4
2025-02-05 05:50:31.254971+00:00[05:50:31] [WRN] [45] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path /media/movies/Lilo & Stitch (2002)/Lilo & Stitch (2002) Bluray-1080p x264.mp4
2025-02-05 05:50:31.255620+00:00[05:50:31] [WRN] [45] MediaBrowser.Controller.Entities.BaseItem: Unable to find linked item at path /media/movies/Lilo & Stitch 2 Stitch Has a Glitch (2005)/Lilo & Stitch 2 Stitch Has a Glitch (2005) Bluray-1080p x264.mp4
2025-02-05 05:50:33.391020+00:00[05:50:33] [INF] [74] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: BoxSet, Name: Lilo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Stitch Collection, Path: /config/data/collections/Lilo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Stitch Collection [boxset], Id: 396a03f2-45fb-403d-9e92-a1550da9fc6b
2025-02-05 05:50:33.391129+00:00[05:50:33] [INF] [74] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: BoxSet, Name: Lilo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Stitch Collection, Path: /config/data/collections/Lilo &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Stitch Collection [boxset], Id: 396a03f2-45fb-403d-9e92-a1550da9fc6b
2025-02-05 05:51:21.346129+00:00[05:51:21] [INF] [83] Emby.Server.Implementations.IO.LibraryMonitor: movies (/media/movies) will be refreshed.
2025-02-05 05:51:21.353066+00:00[05:51:21] [INF] [74] Emby.Server.Implementations.IO.LibraryMonitor: movies (/media/movies) will be refreshed.
2025-02-05 05:53:36.139994+00:00[05:53:36] [INF] [86] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/movies/Lilo & Stitch 2 Stitch Has a Glitch (2005)/Lilo & Stitch 2 Stitch Has a Glitch (2005) Bluray-1080p x264.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
2025-02-05 05:53:36.297542+00:00[05:53:36] [INF] [95] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/movies/Lilo & Stitch 2 Stitch Has a Glitch (2005)/Lilo & Stitch 2 Stitch Has a Glitch (2005) Bluray-1080p x264.srt" -threads 0 -v warning -print_format json -show_streams -show_format
2025-02-05 05:53:39.563917+00:00[05:53:39] [INF] [95] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for /media/movies/Lilo & Stitch 2 Stitch Has a Glitch (2005)/Lilo & Stitch 2 Stitch Has a Glitch (2005) Bluray-1080p x264.mp4 [ID: cdfb6aae-cdba-dba1-b0df-f969a10596b0]
2025-02-05 05:53:39.565325+00:00[05:53:39] [INF] [95] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device cuda=cu:0 -filter_hw_device cu -hwaccel cuda -hwaccel_output_format cuda -noautorotate -hwaccel_flags +unsafe_output -threads 1 -i file:"/media/movies/Lilo & Stitch 2 Stitch Has a Glitch (2005)/Lilo & Stitch 2 Stitch Has a Glitch (2005) Bluray-1080p x264.mp4" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_cuda=w=320:h=180:format=yuv420p,hwdownload,format=yuv420p" -threads 2 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 "/tmp/jellyfin/aec74a7f870c44d7ab70737d4f81fec8/%08d.jpg"
2025-02-05 05:53:44.154618+00:00[05:53:44] [INF] [86] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/movies/Lilo & Stitch (2002)/Lilo & Stitch (2002) Bluray-1080p x264.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
2025-02-05 05:53:44.317790+00:00[05:53:44] [INF] [86] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/movies/Lilo & Stitch (2002)/Lilo & Stitch (2002) Bluray-1080p x264.srt" -threads 0 -v warning -print_format json -show_streams -show_format
2025-02-05 05:53:46.027942+00:00[05:53:46] [INF] [86] Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager: Minimum number of movies is 2, but there is/are only 1: Lilo & Stitch 2: Stitch Has a Glitch
2025-02-05 05:53:53.914686+00:00[05:53:53] [INF] [74] Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager: Box Set for Lilo & Stitch Collection (97461) does not exist. Creating it now!
```

as an aside, how are you achieving the line `[2025-02-04 22:00:56.520 +00:00] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: "collections" ("/config/data/collections") will be refreshed.`? I never see that in logs and the only way to create/update boxsets is to rescan Movies collection. Rescanning the Collections "library" itself only deletes and creates new image for it:
```
2025-02-05 05:42:11.821616+00:00[05:42:11] [INF] [63] Jellyfin.Drawing.ImageProcessor: Creating image collage and saving to /tmp/jellyfin/ca7c83509b4e44459865fc61081691d4.png
2025-02-05 05:42:12.247346+00:00[05:42:12] [INF] [63] Jellyfin.Drawing.ImageProcessor: Completed creation of image collage and saved to /tmp/jellyfin/ca7c83509b4e44459865fc61081691d4.png
```

**Comment by fubar-coder** [comment]
It would be really helpful to have a small PowerShell/bash script or something similar that fixes all those problems. The difficulty here seems to be the required access to the file system (for the NFO file) and the database access. Maybe the database entries can be fixed using the Jellyfin REST API?
