### ISSUE TITLE
Jellyfin v10.9.1 isn't respecting the metadata lock for Season names in Show libraries causing custom season names to be lost.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin#11656]
**Describe The Bug**
For a Show library that contains series with seasons, you're allowed to manually overwrite the title names for each season. You can then lock the metadata for the name so that its title will not change upon a future scan. This is how it worked before v10.9.0.

However, since upgrading to v10.9.0 (and v10.9.1), Jellyfin doesn't respect the metadata lock for the season name/title. With v10.9, a rescan of any season will prompt the server to change the name of any season to be "Season x" where x is the season number in the metadata.

**Steps To Reproduce**
1. Go to a show that has at least one season.
2. Edit the season's metadata and change its title to be anything. After changing the name, make sure to scroll to the bottom of the metadata edit popup to lock the name. Either uncheck the "Name" box, or select the "Lock this item to prevent future changes" box.
3. Reload the client, then navigate to the same show to see your change to the season's name.
4. Refresh the metadata for the whole show (to capture the season(s) as well), and select the "Scan for new and updated files" option. You can also go to the dashboard and use the "Scan All Libraries" button to get this same result.
5. Wait a short while to let the scan do its work.
6. Reload the client again, then navigate to the same show. You'll notice the client changed the custom name you gave the season back to "Season x" despite you locking it.

**Expected Behavior**
Jellyfin should respect the metadata lock and not change any season's name if you set a custom name for the season.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Any
 - Jellyfin Version: v10.9.1

**Additional Context**
The names seem to be pulled from the .nfo files I have saved next to the media files. If the .nfo has a season number stored with it, doing the above will show the error as I describe. I found that if I remove the season number from the season's .nfo files, this bug doesn't happen.

**Comment by gnattu** [comment]
Should be fixed by #11647

**Comment by maru801** [comment]
This issue was fixed with the server version v10.9.2.

**Comment by maru801** [comment]
Reopening this as I found out that v10.9.2 only fixed the season names from being changed when using the dashboard's "Scan All Libraries" or the "Scan for new and updated files" option for all else. Still, If you scan a season with either the "Search for missing metadata" or "Replace all metadata" options, it will still have its title name changed despite being locked.

And what's more, some seasons are now getting their season name changed to that of another season of another series when scanned. I don't understand what is going on here.

**Comment by maru801** [comment]
Seems to be fixed with v10.9.4 (provided you follow the correct folder structure). Closing this issue again.

**Comment by HunterNwc** [comment]
Hi - this seems to be still not addressed, i'm using Jellyfin 10.10.7

1 - changing a season name or any metadata entry
2 - lock the metadata to prevent modification
3 - rescan the **season** for "Search for missing metadata" or "Replace all metadata"
4 - season metadata are changed back to previous state

**Comment by irfanhakim-as** [comment]
Also on 10.10.7, after re-identifying a wrongly identified movie or show, and then locking the movie/show's metadata to prevent any changes after saving the new metadata/images, the movie/show would just almost soon after automatically revert to the wrong movie/show again - requiring re-identifying again manually.
