### ISSUE TITLE
[Issue]: after updating to 10.9.2 can't connect to the server anymore. AuthenticationScheme: CustomAuthentication was not authenticated.

### ISSUE THREAD

**Issue by DenisBY** [jellyfin/jellyfin#11715]
### Please describe your bug

After updating to 10.9.2 can't connect to the server anymore. In logs I see `AuthenticationScheme: CustomAuthentication was not authenticated.`

I tried to clean up the browser cache, use incognito mode. No success.

### Reproduction Steps

Update to 10.9.2

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Ubuntu
- Linux Kernel: 6.6.21-1-MANJARO-RPI4
- Virtualization: Docker
- Clients: Web
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
[15:02:01] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Network availability changed.
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Refreshing interfaces.
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Discovered 22 interfaces.
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Interfaces addresses: ["127.0.0.1", "192.168.178.2", "10.147.17.2", "172.22.0.1", "172.23.0.1", "172.24.0.1", "172.25.0.1", "::1", <IPv6 here>]
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Refreshing LAN information.
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Using LAN interface addresses as user provided no LAN details.
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "192.168.178.2", "10.147.17.2", "172.22.0.1", "172.23.0.1", "172.24.0.1", "172.25.0.1", "::1", <IPv6 here>]
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["::"]
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[15:02:03] [DBG] [17] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[15:02:08] [DBG] [32] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[15:02:10] [DBG] [17] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[15:02:11] [DBG] [17] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[15:02:12] [DBG] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
```

### Please attach any screenshots here

![изображение](https://github.com/jellyfin/jellyfin/assets/1147703/2448d435-8656-405e-a2a6-ea4083888474)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 13xforever** [comment]
I have the same issue on Windows version, all LAN clients fail to connect, including the web version.

**Comment by DenisBY** [comment]
My solution: disable IPv6 in `network.xml` config:
```
  <EnableIPv4>true</EnableIPv4>
  <EnableIPv6>false</EnableIPv6>
```

In this case it will bind to IPv4 ip:
```
[15:17:16] [DBG] [24] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
```

**Comment by 13xforever** [comment]
this is not an IPv6 issue, even with IPv4 only nothing works, also all my clients use ipv4 explicitly anyway

**Comment by alpha-tango-kilo** [comment]
Having the same issue here, explicitly disabling IPv6 in `network.xml` worked 🤷‍♂️

**Comment by 13xforever** [comment]
My issue resolved when disabling virtual interface filtering in config
```xml
<IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>
```

**Comment by Emma0Z** [comment]
Hello there,

I confirm @13xforever and @alpha-tango-kilo 
I disabled IPv6 and `IgnoreVirtualInterfaces` and everything run smoothly now.

I'm curious about why it was generating all this error like

```
[20:50:08] [INF] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[20:50:08] [INF] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[20:50:08] [INF] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
```

I'm not getting them anymore.

I'm using Jellyfin on Docker with a Synology DS415+, with IPv6 also and a Let's Encrypt certificate (binded on internet btw).

**Comment by winstonrc** [comment]
> My solution: disable IPv6 in `network.xml` config:

This worked for me.

**Comment by m0d3rnX** [comment]
I've had IPv6 already disabled, i've also tried to disable IgnoreVirtualInterfaces, not working on my end sadly.

**Comment by MitraMai** [comment]
> My issue resolved after disabling virtual interface filtering in config
> 
> ```
> <IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>
> ```

This worked for me. I also had IPv6 already disabled. Changing IgnoreVirtualInterfaces to false and restarting the jellyfin-server made me able to connect to server again.

**Comment by pecbeck** [comment]
Can someone please point me at the location of config files on windows 11, I just can't find them

**Comment by itzikmasar** [comment]
> Can someone please point me at the location of config files on windows 11, I just can't find them

It is in the 'ProgramData' folder, which is hidden, you have to show hidden files

**Comment by pecbeck** [comment]
Thanks, all working again

**Comment by newo-2001** [comment]
Disabling ipv6 in the network config indeed resolved the issue for me.

**Comment by Shadowghost** [comment]
What OS are you guys running? It seems that .NET behaves differently for binding to IPv6.Any than we expected.

**Comment by pecbeck** [comment]
Windows 11. It's rubbish

**Comment by marsara9** [comment]
I can't comment for the others but I have Jellyfin running in docker on Ubuntu 22.04. 

It's in the same compose file as Nginx, Portainer and Watchtower. I woke up that morning after Watchtower had updated Jellyfin that night to find that I couldn't login. So I'm not 100% sure it's the same issue.  But I was seeing the same not authenticated messages.  None of the solutions were here yet before i ended up just rebuilding from scratch.  As rolling back to 10.9.1 (using backups) didn't seem to fix it.  So again take this reply with a grain of salt as I might have ran into a different issue. 

I was using the linuxserver image until this happened.  Now I'm running the official version (not sure if that's relevant).

**Comment by newo-2001** [comment]
Debian 12 (bookworm)

**Comment by Elmagenta** [comment]
Same for me: Debian 12 (Bookworm) with Jellyfin on docker + Cloudflare Tunnels for remote access. Android App and Web with custom url were not connecting meanwhile my main PC with Windows 11 and my MacBook Air M1 (version Sonoma 14.2.1) with local address were connecting.
IPv6 on `<EnableIPv6>false</EnableIPv6>` was already on false, disabling IgnoreVirtualInterfaces `<IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>` made me access on Web, i don't have the android device to test it and i will do it tomorrow.

**Comment by ptasznikarium** [comment]
Same issue on Ubuntu 22.04

**Comment by ACR-Jeff** [comment]
Debian bookworm, Tried all of the above and still won't connect, Going to do some digging

**Comment by Lukhasz** [comment]
Same issue, running as an application on Truenas Scale (version 23.10.2). 
IPv6 is disabled. 
One thing of note is that the android (OxygenOS 13.1 / Android 13) Jellyfin application (version 2.6.1) can connect and play media, but only for one session. When the session is ended by closing the app, I have to clear cache and appdata to connect again, otherwise I get error: "Connection cannot be established. Please check the hostname and your network connection." 
This is on LAN.

**Comment by job432** [comment]
> Same issue, running as an application on Truenas Scale (version 23.10.2). IPv6 is disabled. One thing of note is that the android (OxygenOS 13.1 / Android 13) Jellyfin application (version 2.6.1) can connect and play media, but only for one session. When the session is ended by closing the app, I have to clear cache and appdata to connect again, otherwise I get error: "Connection cannot be established. Please check the hostname and your network connection." This is on LAN.

Same for me, tested on multiple Android Devices. I need to clear cache and application data to establish connection again. Pretty sure it is related to token session duration with is too low.

**Comment by Ryah** [comment]
Same exact issue here. Tried all of the above and still nothing. 

Ubuntu 20.04. Installed jellyfin through docker.

**Comment by Zanonia** [comment]
> Same issue, running as an application on Truenas Scale (version 23.10.2). IPv6 is disabled. One thing of note is that the android (OxygenOS 13.1 / Android 13) Jellyfin application (version 2.6.1) can connect and play media, but only for one session. When the session is ended by closing the app, I have to clear cache and appdata to connect again, otherwise I get error: "Connection cannot be established. Please check the hostname and your network connection." This is on LAN.

It's the same for me with the TrueNAS community docker image.
No problem with Findroid and Finamp or Jellyfin android TV app. It only affects Jellyfin android app.

**Comment by cinderblockgames** [comment]
I had to uninstall and reinstall the LDAP extension to get it to work again.

**Comment by SonicScrewdriver** [comment]
Same issue here on Windows after the newest update! 

The fix proposed regarding the edits to network.xml allowed me to get the other devices on my local network to connect to the server -- but now I'm unable to connect to the server using the same PC that is running it.

**Comment by Necronar** [comment]
Just chiming in to say I have the same problem on Docker running in Synology DSM.

**Comment by clion007** [comment]
Same issue here on Docker from alpine linux running on unraid after updated to the newest version 10.9.2. And can't decode even H264 encode vidoes in web client.

**Comment by ljani** [comment]
Before 10.9 everything was working with `<EnableIPv6>true</EnableIPv6>` and without the `IgnoreVirtualInterfaces` element.

With `v10.9.2` using both `<IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>` and `<EnableIPv6>false</EnableIPv6>` worked with the web UI and external clients.

With `v10.9.3` using both, neither or either does not work with the web UI. My setup:
- `https://jellyfin.example.com:443` points to `192.168.0.100` which is the server
- There's a reverse proxy listening on `:443` pointing to `http://127.0.0.1:8096`
- Web UI loads over `https://jellyfin.example.com`
- I also have Tailscale installed on my server
- But peeking at the dev tools there seems to be CORS failures for `https://100.0.0.10:8096/Branding/Css` and `https://100.0.0.10:8096/system/info/public`
- I have enabled remote IP filters:

```xml
  <RemoteIPFilter>
    <string>192.168.0.0/24</string>
    <string>100.0.0.0/24</string>
  </RemoteIPFilter>
```

I have not tried external clients with `v10.9.3` yet.

**Comment by clion007** [comment]
> With `10.9.3` I still need to `<EnableIPv6>false</EnableIPv6>` to connect to the server.
> 
> I'm on Windows 11.

看了下10.9.3的changelog，没有修复这个问题

**Comment by okphilo** [comment]
Why no one fix the fatal issue?

**Comment by jpmvferreira** [comment]
In on of the latest updates on Arch Linux, running Jellyfin behind a Wireguard instance, also caused this issue. Disabling IPv6 solved it.

**Comment by ACR-Jeff** [comment]
Seems like every update this happens, I always have to wait at least 2 or more revisions before updating because of this bug.

**Comment by okphilo** [comment]
issue disappear after i clean install 10.9.4

**Comment by FrankJeager** [comment]
Issue solved for me with 10.9.4.

Good job.

**Comment by Jusix** [comment]
Still broken for me with <EnableIPv6>true</EnableIPv6> in 10.9.4

**Comment by idosyncrasi** [comment]
Just ran to the same issue updating to 10.9.6. Fixed with `<EnableIPv6>false</EnableIPv6>`.

**Comment by stom66** [comment]
Have the same problem on Rocky after upgrading from 10.8.11 to 10.9.6.0.

`<IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>`
`<EnableIPv6>false</EnableIPv6>`

The above changes do not fix the issue.

**Comment by ACR-Jeff** [comment]
I've went back and restored a Timeshift backup, Waited a few weeks, Decided to give it a try again and update to the latest server version. I've found nothing that works to allow me to login, Debian 12 bookworm

**Comment by siggsy** [comment]
Still broken on 10.9.11 with debian 12 on proxmox and IPv6 enabled.
The connection works through ipv6 just refuses to work with ipv4.

**Comment by sephiroth1395** [comment]
On Jellyfin 10.9.11 over Debian 12 (LXC on Proxmox) from the Jellyfin APT repos : with IPv6 enabled, Android TV app cannot connect.  Other devices work.  Fixed by disabling IPv6.

**Comment by Bluscream** [comment]
@DenisBY You are an absolute hero!

**Comment by Bluscream** [comment]
Is this really just being ignored? time for plex then :pensive:
