### ISSUE TITLE
 Not fetching metadata for music library

### ISSUE THREAD

**Issue by eightsheep67** [jellyfin/jellyfin#11899]
### Please describe your bug

i have problem with music library. It worked fine on 10.8.13, then I upgraded to 10.9 and new added song not scraped correctly, it missed artists and album pic, i had to add manully. then I tried clean installation and clean all music nfo file. finding that there are 0 artist in the library. I trid many times on different machine with 10.9.3 docker image. it come out the same result.

### Reproduction Steps

Synology DS916+ DSM 7.2 Container
![331773304-e6a9475c-2017-44e6-9b78-382869320533](https://github.com/jellyfin/jellyfin/assets/70835718/eb0abc23-40be-495c-999d-1286cbed6ed6)

I tried clean installation and clean all music nfo file. finding that there are 0 artist in the library. I trid many times on different machine with 10.9.3 docker image. it come out the same result.

![331770688-9fda9bb7-61e2-4076-9478-427335ef9584](https://github.com/jellyfin/jellyfin/assets/70835718/d97ddf83-66bf-4619-904b-2c1430f33d31)
![331770791-a1b9bba9-0709-4cd6-b48a-38e1cdb4f287](https://github.com/jellyfin/jellyfin/assets/70835718/3654cc22-0991-497e-8973-f84fd3b132ca)
![331770867-a6796efa-13a7-426a-99dc-f0b2090cd59a](https://github.com/jellyfin/jellyfin/assets/70835718/854b18f5-5240-4325-9c5c-753b5073928b)
<img width="341" alt="331772745-e0809f48-e9e5-4968-aeea-f3fb893d0d39" src="https://github.com/jellyfin/jellyfin/assets/7083
![331772812-21416854-c75f-47b6-a35d-ba6116e41d71](https://github.com/jellyfin/jellyfin/assets/70835718/7043038e-bb36-4fe9-b1e5-d3dcd3572c80)
5718/49cb5154-110a-418a-8a8c-a060975be910">

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
file:\"/media/music/iTunes/iTunes Media/test/4 Non Blondes/Bigger, Better, Faster, More!/1-11 What's Up.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-18 06:50:41.619 +00:00] [ERR] [43] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-18 06:50:41.619 +00:00] [ERR] [23] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-18 06:50:41.620 +00:00] [ERR] [30] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-18 06:50:41.620 +00:00] [ERR] [10] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-18 06:50:41.819 +00:00] [INF] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/iTunes/iTunes Media/test/AC_DC/Iron Man 2/1-02 Rock 'n' Roll Damnation.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-18 06:50:41.926 +00:00] [ERR] [31] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-18 06:50:41.943 +00:00] [INF] [31] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/iTunes/iTunes Media/test/AC_DC/Iron Man 2/1-03 Guns For Hire.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-18 06:50:42.054 +00:00] [ERR] [28] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-18 06:50:42.080 +00:00] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/iTunes/iTunes Media/test/AC_DC/Iron Man 2/1-04 Cold Hearted Man.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-18 06:50:42.204 +00:00] [ERR] [30] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-18 06:50:42.230 +00:00] [INF] [30] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/iTunes/iTunes Media/test/AC_DC/Iron Man 2/1-05 Back In Black.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-18 06:50:42.307 +00:00] [ERR] [16] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-18 06:50:42.315 +00:00] [INF] [16] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/iTunes/iTunes Media/test/AC_DC/Iron Man 2/1-06 Thunderstruck.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-18 06:50:42.367 +00:00] [ERR] [42] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentException: Length must be non-negative (Parameter 'length')
   at TagLib.File.ReadBlock(Int32 length)
   at TagLib.Mpeg4.IsoHandlerBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.AppleItemListBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoMetaBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, Int64 position, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.Box.LoadChildren(File file)
   at TagLib.Mpeg4.IsoUserDataBox..ctor(BoxHeader header, File file, IsoHandlerBox handler)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, BoxHeader parent, IsoHandlerBox handler, Int32 index)
   at TagLib.Mpeg4.BoxFactory.CreateBox(File file, BoxHeader header, IsoHandlerBox handler)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties(Int64 start, Int64 end, IsoHandlerBox handler, List`1 parents)
   at TagLib.Mpeg4.FileParser.ParseTagAndProperties()
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at InvokeStub_File..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
Should be temporarily fixed by https://github.com/jellyfin/jellyfin/pull/11859

And will be improved in 10.10 with https://github.com/jellyfin/jellyfin/pull/11879

**Comment by eightsheep67** [comment]
> Should be temporarily fixed by #11859
> 
> And will be improved in 10.10 with #11879

i tested on 10.9.3, problem still

**Comment by gnattu** [comment]
> > Should be temporarily fixed by #11859
> > And will be improved in 10.10 with #11879
> 
> i tested on 10.9.3, problem still

Because these are not in 10.9.3

**Comment by eightsheep67** [comment]
> > > Should be temporarily fixed by #11859
> 
> > > And will be improved in 10.10 with #11879
> 
> > 
> 
> > i tested on 10.9.3, problem still
> 
> 
> 
> Because these are not in 10.9.3

oh! so 10.9.4 will fix it. can't wait!

**Comment by eightsheep67** [comment]
now i update to 10.9.4, and clean all nfo, jpg etc, just m4a files
<img width="483" alt="屏幕截图 2024-06-02 132827" src="https://github.com/jellyfin/jellyfin/assets/70835718/ac774ea9-e8a9-4e88-8c62-cdd2269e0ed8">
and still cannot fetch artist. just album name and song name.
i found another problem is, i deleted an album folder then refresh the music library, the album still there with no source files. i have to delete it manully

**Comment by eightsheep67** [comment]
i provide a music file with folder structure. see what's wrong with it. 10.9.5 still the same problem.
[test.zip](https://github.com/user-attachments/files/15625594/test.zip)
@gnattu

**Comment by eightsheep67** [comment]
and i found that it seems like reading the right metadata, but it show as musicbrainz link rather than artist name or album name. the link is right to the very artist and album.

**Comment by gnattu** [comment]
Should be fixed in 10.9.6, can you try that?

**Comment by eightsheep67** [comment]
> Should be fixed in 10.9.6, can you try that?

yes, it's fixed in 10.9.6. thanks a lot!
