### ISSUE TITLE
Seeking/Pause doesn't work using dlna

### ISSUE THREAD

**Issue by martynas123** [jellyfin/jellyfin#1291]
**Describe the bug**
Seeking and pausing doesn't work on Samsung Smart TV using dlna. Buttons are disabled on TV.

**Logs**
```
[2019-04-24 10:48:08.076 +03:00] [INF] DLNA Session created for "[TV] Samsung 7 Series (49)" - "UE49MU7050"
[2019-04-24 10:48:18.847 +03:00] [INF] Profile: "Samsung Smart TV", Path: "/media/tv/The IT Crowd/Season 1/The.IT.Crowd.S01E01.Yesterday's.Jam.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-24 10:48:18.847 +03:00] [INF] Profile: "Samsung Smart TV", Path: "/media/tv/The IT Crowd/Season 1/The.IT.Crowd.S01E01.Yesterday's.Jam.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-24 10:48:18.900 +03:00] [INF] Profile: "Samsung Smart TV", Path: "/media/tv/The IT Crowd/Season 1/The.IT.Crowd.S01E02.Calamity.Jen.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-24 10:48:18.901 +03:00] [INF] Profile: "Samsung Smart TV", Path: "/media/tv/The IT Crowd/Season 1/The.IT.Crowd.S01E02.Calamity.Jen.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-24 10:48:20.722 +03:00] [INF] Profile: "Samsung Smart TV", Path: "/media/tv/The IT Crowd/Season 1/The.IT.Crowd.S01E01.Yesterday's.Jam.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-24 10:48:20.723 +03:00] [INF] Profile: "Samsung Smart TV", Path: "/media/tv/The IT Crowd/Season 1/The.IT.Crowd.S01E02.Calamity.Jen.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-24 10:48:20.738 +03:00] [INF] Profile: "Samsung Smart TV", Path: "/media/tv/The IT Crowd/Season 1/The.IT.Crowd.S01E01.Yesterday's.Jam.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-24 10:48:21.311 +03:00] [INF] Profile: "Samsung Smart TV", Path: "/media/tv/The IT Crowd/Season 1/The.IT.Crowd.S01E01.Yesterday's.Jam.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-04-24 10:49:43.780 +03:00] [WRN] HTTP Response 200 to "192.168.10.102". Time (slow): 0:01:22.8845872. "http://192.168.10.218:8096/videos/8d988d3e-133c-391a-7ce3-5f98f1be3e62/stream.mkv?DeviceProfileId=db43959c2c11a41305c2e9608c2bf229&DeviceId=test&MediaSourceId=8d988d3e133c391a7ce35f98f1be3e62&Static=true&AudioStreamIndex=2&Tag=0166b2e466c01c6db90fbce48bb435a4&dlnaheaders=true"
```
**System (please complete the following information):**
 - OS: Ubuntu
 - Jellyfin Version: 10.3.1 (same issue on 10.2.2)
 - Reverse proxy: no

**Additional context**
Pausing/Seeking works using VLC as dlna client.
Pausing/Seeking works using Emby/Plex server on this TV.

**Comment by anthonylavado** [comment]
This _might_ be fixed by #1287, but I thought it didn't affect DLNA clients (I too tried with VLC before the fix, and it worked).

**Comment by Olivertobias** [comment]
I am having the same issue even after I just manually build and installed the hotfix branch 10.3.z
TV: samsung ue55ju6850
OS: debian stretch armhf

Pausing/Seeking not working on TV but it does work on VLC

I found this in my log maybe it helps:

`[2019-04-29 20:33:00.867 +02:00] [ERR] Error ProtocolError getting response from "http://192.168.178.28:9197/upnp/control/AVTransport1"
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
[2019-04-29 20:33:00.905 +02:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, Boolean logRequest, String header)
   at Emby.Dlna.PlayTo.Device.SetPause(CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by nonplusnl** [comment]
This might be related to #1246  - I'm getting the same ProtcolError500 with 10.3.0 and up. Not even when seeking, but it even refuses to start playing.

**Comment by zsarosi** [comment]
The problem still exists in 10.7.7-1 on Ubuntu 20.04 with Samsung TV.

**Comment by DeveloperOl** [comment]
@zsarosi my original issue was fixed. If you still have trouble using the seeking/pausing feature you may want to file a new issue with your individual error message.
