### ISSUE TITLE
Multiple Errors while scanning library, System.FormatException: The input string '73375-jack-ryan' was not in a correct format.

### ISSUE THREAD

**Issue by fa1rid** [jellyfin/jellyfin#12929]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I see this error in the log, but I don't notice any problems while watching the series. The error below is showing for every episode in all season for this specific series only and I don't understand why. If someone have an idea please help. 

The issue is not new, it's been for a while since older versions.

I tried to remove the shows causing the issue, renaming them but with no luck.

Please let me know if you need additional information.

### Reproduction steps

Not sure how to Reproduce this issue, but I guess you need to add the specific shows to the library.

### What is the current _bug_ behavior?

It's showing errors in the log.

### What is the expected _correct_ behavior?

Not to show these errors.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

- OS: Windows 10
- Virtualization: None
- Plugins: Default

### Jellyfin logs

```
[13:39:03] [ERR] [14] MediaBrowser.Providers.TV.SeasonMetadataService: Error in TheMovieDb

System.FormatException: The input string '73375-jack-ryan' was not in a correct format.

  at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)

  at System.Convert.ToInt32(String value, IFormatProvider provider)

  at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)

  at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

[13:39:04] [ERR] [140] MediaBrowser.Providers.TV.SeasonMetadataService: Error in TheMovieDb

System.FormatException: The input string '73375-jack-ryan' was not in a correct format.

  at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)

  at System.Convert.ToInt32(String value, IFormatProvider provider)

  at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)

  at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)



[13:39:34] [ERR] [126] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in TheMovieDb

System.FormatException: The input string '73375-jack-ryan' was not in a correct format.

  at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)

  at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)

  at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)

  at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)


```

Additionally these errors keeps showing as well:

```
[13:39:04] [INF] [140] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season 0 in series The Gold

[13:39:04] [INF] [140] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Specials, Path: , Id: 3c2c8725-080d-4147-554c-7f1da171ada0

[13:39:04] [INF] [140] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season Specials entry for The Gold

[13:39:04] [ERR] [140] MediaBrowser.Providers.TV.SeasonMetadataService: Error in TheMovieDb

```

**Comment by crobibero** [comment]
@scampower3 Could this be related to adding slug provider ids to the TVDB plugin?

**Comment by scampower3** [comment]
It is not related. The cause is more likely due to TheTvdb sending TheMovieDb Id as 73375-jack-ryan, which is how it is like when it is in the url, instead of just 73375. 

Should be fixed by https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/194

**Comment by fa1rid** [comment]
Ok now I understand, but why Jellyfin is getting TMDB ID from TheTvdb in first place rather than searching TMDB directly? Is TheTvdb more reliable than TMDB?

How about that I'm getting a lot of ` Removing virtual season {N}` and `Removing item, Type: Season, Name: Specials` for most of the series every time Jellyfin starts `Validating media library`?

**Comment by scampower3** [comment]
> Ok now I understand, but why Jellyfin is getting TMDB ID from TheTvdb in first place rather than searching TMDB directly? Is TheTvdb more reliable than TMDB?
It's just by the ranking of plugin preference. If you set the TMDB provider to be higher, Jellyfin will retrieve TMDB ID from TMDB. Similarly, if you set the TVDB provider to be higher, Jellyfin will TMDB ID from TVDB if it exist there.

> How about that I'm getting a lot of  Removing virtual season {N} and Removing item, Type: Season, Name: Specials for most of the series every time Jellyfin starts Validating media library?
Should be fixed by https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/195

**Comment by fa1rid** [comment]
> It's just by the ranking of plugin preference. If you set the TMDB provider to be higher, Jellyfin will retrieve TMDB ID from TMDB. Similarly, if you set the TVDB provider to be higher, Jellyfin will TMDB ID from TVDB if it exists there.
> 
I already have TMDB set higher than TVDB in everything. So that's not really the case.

![Image](https://github.com/user-attachments/assets/50d70d1d-7c8e-437a-8143-3610940e6680)


Do you recommend keeping the `MissingEpisodeProvider `and in which priority? I'm not sure what does it do since we have other providers.

**Comment by fa1rid** [comment]
Are the issues resolved for the tvDB  plugin update v18? I see it's already merged. 

I updated the plugin, but I still get the same issues.

**Comment by scampower3** [comment]
Yes. You need to do a full metadata refresh with TVDB as your top metadata provider, or just edit the bad TMDB Id with the metadata editor.

**Comment by fa1rid** [comment]
Which one to choose?
![Image](https://github.com/user-attachments/assets/41c25c39-6f21-4e31-9eaa-4f9be3fd0514)

Will it also fix these kind of errors? :

``` 
Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Season 22", Path: "", Id: ae82e3d9-3b8c-f174-9b58-cf44856c8e04
MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season 24 in series "Mayday"
```

My log keeps getting flooded with these from so many series.

**Comment by Hello-World-Traveler** [comment]
Editing the metadata,  0000-tvshow was shown.

![Image](https://github.com/user-attachments/assets/ed926824-985a-4b30-b017-8f5cb87d7665)

**Comment by fa1rid** [comment]
I'm still facing issue for: "Season Specials Removed", and I receive notification through my Webhook every time I add new content for the same series that the "Season Specials Removed". TV Show Name is "The Gold (2023)"

**Comment by Hello-World-Traveler** [comment]
@fa1rid https://www.themoviedb.org/tv/218351-the-gold There is only season 1? and I couldn't see it on TVDB. I don't think this issue is a bug.

**Comment by theguymadmax** [comment]
Should be fixed with TVDB [Version 19](https://github.com/jellyfin/jellyfin-plugin-tvdb/releases/tag/v19) or later.
