### ISSUE TITLE
Library scan fails with "Cannot store 'NaN' values"

### ISSUE THREAD

**Issue by achalker** [jellyfin/jellyfin#13290]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

A Media Library Scan will fail with an "System.InvalidOperationException: Cannot store 'NaN' values." error.  This happens in a brand new dockerized install (i.e. not upgrading from a previous install).  It appears to be only related to Music libraries.  On a fresh install, Movie and Show libraries will scan successfully and the Music library will begin to scan fine (lots of ffprobe lines in the logs).  After a significant portion of the library is scanned (many thousands of files), the scan will fail with a single error as shown below.  Subsequent attempts to perform a library scan will result in the same identical errors within a minute (after scanning a few dozen additional files at most).  The items that are being scanned are different everytime.

This seems similar to, but not the same as other issues such as #12199 and #11994.  However those issues have "NULL at ordinal 1" in the error.  I've tried the 'FixAudioData' in migrations.xml fix (https://github.com/jellyfin/jellyfin/issues/11994#issuecomment-2168526563) and note that <IsStartupWizardCompleted> is set to True.

Note everything else seems to work fine despite this error (other than it's not clear if the whole library is imported / scanned in)

```
[2024-12-27 21:23:02.374 -05:00] [ERR] [33] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.InvalidOperationException: Cannot store 'NaN' values.
   at Microsoft.Data.Sqlite.SqliteValueBinder.BindDouble(Double value)
   at Microsoft.Data.Sqlite.SqliteValueBinder.Bind()
   at Microsoft.Data.Sqlite.SqliteParameterCollection.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem item, BaseItem topParent, String userDataKey, SqliteCommand saveItemStatement)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(ManagedConnection db, IEnumerable`1 tuples)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Audio.MusicAlbum.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
``` 

### Reproduction steps

Can be easily triggered by deploying a brand new Jellyfin instance via docker compose (deleting all previous config/cache directories first) then going through the initial setup.  Subsequent to that can be triggered from the Scheduled Tasks screen (Scan Media Library) or the Libraries screen (Scan All Libraries).

### What is the current _bug_ behavior?

Media library scan fails everytime

### What is the expected _correct_ behavior?

Media library scan should complete successfully

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.3

### Specify the build version

10.10.3

### Environment

```markdown
- OS: docker (jellyfin/jellyfin)
- Linux Kernel:
- Virtualization: 
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: Standard out of the box with fresh install, no additional ones
- Reverse Proxy:
- Base URL:
- Networking: host
- Storage: local nvme
```

### Jellyfin logs

```shell
[2024-12-27 22:06:20.181 -05:00] [ERR] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.InvalidOperationException: Cannot store 'NaN' values.
   at Microsoft.Data.Sqlite.SqliteValueBinder.BindDouble(Double value)
   at Microsoft.Data.Sqlite.SqliteValueBinder.Bind()
   at Microsoft.Data.Sqlite.SqliteParameterCollection.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem item, BaseItem topParent, String userDataKey, SqliteCommand saveItemStatement)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(ManagedConnection db, IEnumerable`1 tuples)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Audio.MusicAlbum.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-12-27 22:06:20.183 -05:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 0 minute(s) and 25 seconds
```

### FFmpeg logs

```shell

```

**Comment by felix920506** [comment]
Please include at least 20 lines of logs before the issue.

**Comment by achalker** [comment]
Happy to.  Here's the extent of the lines before the error.  Prior to this is just a previous error and similar lines from triggering a previous scan (but with different files being scanned by ffprobe).  Thanks for looking at this!

```
[2024-12-27 22:29:17.586 -05:00] [INF] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 0 minute(s) and 12 seconds
[2024-12-27 22:29:17.828 -05:00] [INF] [32] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/Chalker-OneDrive/TVShows"
[2024-12-27 22:29:17.829 -05:00] [INF] [38] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/Chalker-OneDrive/movies"
[2024-12-27 22:29:17.837 -05:00] [INF] [50] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/Katie-OneDrive/Katie Share/movies2"
[2024-12-27 22:29:18.115 -05:00] [INF] [33] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/media/Chalker2-OneDrive/Chalker 2 Share/music"
[2024-12-27 22:30:50.941 -05:00] [INF] [42] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-12-27 22:30:50.942 -05:00] [ERR] [42] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Invalid token". URL "GET" "/socket".
[2024-12-27 22:31:01.780 -05:00] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/Chalker-OneDrive/TVShows"
[2024-12-27 22:31:01.780 -05:00] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/Chalker2-OneDrive/Chalker 2 Share/music"
[2024-12-27 22:31:01.793 -05:00] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/Chalker-OneDrive/movies"
[2024-12-27 22:31:01.793 -05:00] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/Katie-OneDrive/Katie Share/movies2"
[2024-12-27 22:31:01.794 -05:00] [INF] [42] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-12-27 22:31:01.809 -05:00] [WRN] [42] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-12-27 22:31:01.825 -05:00] [WRN] [42] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-12-27 22:31:11.454 -05:00] [INF] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Chalker2-OneDrive/Chalker 2 Share/music/Various Artists/100% Hits - Best of 2013 (2013)/Various Artists - 100% Hits - Best of 2013 - 02 - Can’t Hold Us.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-12-27 22:31:11.475 -05:00] [INF] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Chalker2-OneDrive/Chalker 2 Share/music/Various Artists/The Heart of Rock ’n’ Roll - 1960-1961, Take Three (1997)/Various Artists - The Heart of Rock ’n’ Roll - 1960-1961, Take Three - 06 - You Can Depend on Me.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-12-27 22:31:11.656 -05:00] [INF] [49] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Chalker2-OneDrive/Chalker 2 Share/music/Various Artists/The Heart of Rock ’n’ Roll - 1960-1961, Take Three (1997)/Various Artists - The Heart of Rock ’n’ Roll - 1960-1961, Take Three - 03 - Breakin' in a Brand New Broken Heart.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-12-27 22:31:11.788 -05:00] [INF] [49] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Chalker2-OneDrive/Chalker 2 Share/music/Various Artists/The Heart of Rock ’n’ Roll - 1960-1961, Take Three (1997)/Various Artists - The Heart of Rock ’n’ Roll - 1960-1961, Take Three - 09 - Don't Bet Money Honey.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-12-27 22:31:11.927 -05:00] [INF] [38] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Chalker2-OneDrive/Chalker 2 Share/music/Various Artists/The Heart of Rock ’n’ Roll - 1960-1961, Take Three (1997)/Various Artists - The Heart of Rock ’n’ Roll - 1960-1961, Take Three - 20 - Look for a Star.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"

```

**Comment by achalker** [comment]
Since the issues I cited above all seem to relate to changes made since version 10.9.3, on a whim I decided to deploy a brand new instance but instead of using the "jellyfin/jellyfin" image, I used "jellyfin/jellyfin:10.9:3" (with empty config/cache directories so it would be a fresh).  I went through the same import of media libraries I was trying before with no issue at all (multiple media library scans worked fine).  I then shutdown the container, changed the image back to "jellyfin/jellyfin" and restarted it.  It went through an automatic migration / upgrade without any issues and is now on version 10.10.3.  Subsequent media library scans work fine (i.e. no more failed tasks).  

Seems like this might be isolated to fresh installs of 10.10.3?

**Comment by gnattu** [comment]
That is a too wide version range between 10.9.3 and 10.10.3, can you check on fresh install of 10.9.4? If my theory is correct that is due to a change to LUFS scanning result parsing and that might yield NaN values for Album LUFS. You can check that by either disable LUFS scan in Library settings for a new 10.10.3 install, or pull the 10.9.4 container and using all defaults and check.

**Comment by achalker** [comment]
Thanks for the suggestion.  I apologize for not being detailed enough, but I was unchecking LUFS scanning in the 10.10.3 installs I did (since I don't have any players capable of benefiting from that).

**Comment by gnattu** [comment]
That is weird. The only fields in theory that can be NaN are LUFS and the ratings. If it is not the LUFS then it could be the ratings getting from the metadata providers are NaN, but that is weird that 10.9.3 does not have the same problem. I really think it is some of your album triggers this because I cannot reproduce this on my collections.

**Comment by achalker** [comment]
Thanks for looking into this.  Happy to close this then since I did find a workaround to get me fully operational.

**Comment by twich1226** [comment]
I just noticed this issue today while investigating a seemingly unrelated issue (i messed up my DVR recordings library/mount). I am running a 10.10.3 docker image from linuxserver.io. It happens every time I run the scheduled task or perform a scan of my Music library. 2 reports isn't much but seems like @achalker and I both experienced a nearly identical issue.

A few things I tried:
1. checked/unchecked LUFS during scan - no change, same error both ways
2. added a new library against the same mnt/folder - same error
3. added a new library against an empty folder - no error
4. Played with metadata providers - no change, same error

**Comment by twich1226** [comment]
Resolved, I do suspect something is doing awry but seems to be a relatively easy fix. Here is what I did:
1. Progressively downgraded to the previous version and tried to scan until I got to 10.9.11 where it succeeded.
2. After the scan succeeded in 10.9.11, I updated to 10.10.0 and scanned successfully again.
3. Updated one last time to 10.10.3 and successfully scanned again.

Seems to be resolved now but wanted to add to the ticket in case anyone else comes across this issue, sorry I never found a "smoking gun"

**Comment by achalker** [comment]
Everything has been running fine for a while, but I upgraded yesterday to version 10.10.6 and the errors started up again.  I'll try the downgrade / scan / update approach to resolve this, but just wanted to document that something is still going on here.

**Comment by felix920506** [comment]
Can you do the following:

1. Create a brand new Jellyfin instance and put only a small number of music files on the server. Would be best if you can make it happen with only one file. 
2. Grab the ffprobe command Jellyfin executes for the problematic file from the log, run it manually and post the output.

**Comment by achalker** [comment]
Sorry, I already when through the downgrade/upgrade process and fixed it.   I will note that one of the things I tried previously was to complete remove the music library.  Even when I did that, the scans still failed, so I'm not sure if it's truly tied to a specific file? If it happens again I'll definitely do this first to try to debug it better.

**Comment by winstonrc** [comment]
I’m also running into this issue on 10.10.6, and I also seem to have it faulting from scanning my music folder.

**Comment by felix920506** [comment]
@NicolasFerec run the ffprobe command manually and post the command along with the output you get when you run it manually

**Comment by astjohn** [comment]
FWIW, I had an entire album with files that had `NaN` in those fields. I adjusted the album with the following bash command to reset those fields. They were all m4a files.

```
for f in "/media/Music/Sia/Healing Is Difficult"/*.m4a; do /usr/lib/jellyfin-ffmpeg/ffmpeg -i "$f" -map 0 -c copy -metadata REPLAYGAIN_ALBUM_GAIN="" -metadata REPLAYGAIN_ALBUM_PEAK="" -metadata REPLAYGAIN_TRACK_GAIN="" -metadata REPLAYGAIN_TRACK_PEAK="" "${f%.m4a}.tmp.m4a" && mv -f "${f%.m4a}.tmp.m4a" "$f"; done
```

This fixed the issue. It seems Jellyfin needs some more defensive error catching code concerning bad metadata values perhaps and hopefully something to prevent the entire library scanning process to be aborted due to a single file.

Hope this helps!
