### ISSUE TITLE
Jellyfin loses access to NVIDIA hardware transcoding until container restart

### ISSUE THREAD

**Issue by italocjs** [jellyfin/jellyfin#14463]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our [forum or chat rooms](https://jellyfin.org/contact/) first to troubleshoot with volunteers, before creating a report.
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After several transcodes or after the system is left running for a while, Jellyfin loses the ability to use NVIDIA NVENC hardware transcoding (Quadro P400). Transcoding attempts fail with `FFmpeg exited with code 187`, and only restarting the container restores functionality. No system-level errors (e.g. dmesg) appear. This GPU is dedicated only to jellyfin, there are no other services using it

### 📌 Observations

* Jellyfin starts with working CUDA/NVENC transcoding.
* After some time or usage, attempts to start CUDA-accelerated transcoding fail with `exit code 187`.
* Restarting the container restores functionality without rebooting host.
* No driver crash or kernel panic appears in logs.
* FFmpeg calls show correct parameters including `-init_hw_device cuda=cu:0`.

---

### Docker compose:
```
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000  # Substitua por exemplo: 1000:1000
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - /fastStorage/docker/jellyfin_config/config:/config
      - /fastStorage/docker/jellyfin_config/cache:/cache
      - type: bind
        source: /largeStorage/media
        target: /media
    restart: 'unless-stopped'
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]

    extra_hosts:
      - 'host.docker.internal:host-gateway'
``` 

### Reproduction steps

1. Run Jellyfin inside a Docker container with NVIDIA runtime and proper access to the GPU.
2. Wait several hours or days; eventually, all hardware transcodes fail.
3. Transcoding commands show `FFmpeg exited with code 187`.
4. Restarting the container resolves the issue temporarily.

### ❌ Actual Behavior
Hardware transcoding becomes unavailable after a period of time, with FFmpeg exiting with code 187.

### ✅ Expected Behavior
Hardware transcoding should work consistently for long-running containers, without requiring container restarts.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.7

### Environment

```markdown
#### Jellyfin

* **Version:** 10.10.7
* **Installation Method:** Docker (image: `jellyfin/jellyfin`)
* **FFmpeg Path:** `/usr/lib/jellyfin-ffmpeg/ffmpeg`
* **HWAccel Config:** Enabled for NVIDIA NVENC (CUDA)

#### Docker

* **Version:** 28.3.1, build 38b7060
* **Runtime:** `nvidia`
* **nvidia-container-toolkit:** Installed and working

#### Host System

* **OS:** Ubuntu 24.04.2 LTS (`noble`)
* **Kernel:** 6.11.0-29-generic
* **GPU:** NVIDIA Quadro P400
* **Driver Version:** 570.133.07
* **CUDA Version:** 12.8

#### `nvidia-smi`


GPU  Name        : Quadro P400
Driver Version  : 570.133.07
CUDA Version    : 12.8
Memory Usage    : 544MiB / 2048MiB
Running Apps    : GNOME Shell, Firefox, Steam


#### `nvidia-container-cli info`


Device Index:   0
Model:          Quadro P400
Architecture:   6.1
```

### Jellyfin logs

```shell
#### Jellyfin Log (ffmpeg)

After failure:


FFmpeg exited with code 187
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 187


Example command that failed:


ffmpeg -init_hw_device cuda=cu:0 -filter_hw_device cu -hwaccel cuda -hwaccel_output_format cuda [...]
-codec:v:0 h264_nvenc [...]


#### System Log (`dmesg`)

No relevant kernel errors or GPU faults found:


(no output for nvidia, error, or fail)


---
```

### FFmpeg logs

```shell

```

**Comment by italocjs** [comment]
As an temporary workaround, i created an script to check if the NVENC is working, if not it restarts the container.

Script:
```sh
#!/bin/bash
CONTAINER_NAME="jellyfin"
FFMPEG_PATH="/usr/lib/jellyfin-ffmpeg/ffmpeg"
CHECK_INTERVAL_MINUTES=30

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') | $1"
}

check_gpu() {
    docker exec "$CONTAINER_NAME" "$FFMPEG_PATH" -init_hw_device cuda=cu:0 -hide_banner -loglevel error -f lavfi -i nullsrc -c:v h264_nvenc -t 1 -f null - > /dev/null 2>&1
    return $?
}

while true; do
    log "Running NVENC check inside container '$CONTAINER_NAME'..."

    if check_gpu; then
        log "✅ GPU NVENC is working."
    else
        log "❌ GPU NVENC FAILED! Restarting container '$CONTAINER_NAME'..."
        docker restart "$CONTAINER_NAME"
    fi

    log "Sleeping for $CHECK_INTERVAL_MINUTES minutes..."
    sleep $((CHECK_INTERVAL_MINUTES * 60))
done

``` 

### Manual test:
```sh
italo@italo-server:~$ ./jellyfin-gpu-watchdog.sh
2025-07-13 13:53:16 | Running NVENC check inside container 'jellyfin'...
2025-07-13 13:53:16 | ❌ GPU NVENC FAILED! Restarting container 'jellyfin'...
jellyfin
2025-07-13 13:53:17 | Sleeping for 30 minutes...


italo@italo-server:~$ ./jellyfin-gpu-watchdog.sh
2025-07-13 13:55:14 | Running NVENC check inside container 'jellyfin'...
2025-07-13 13:55:15 | ✅ GPU NVENC is working.
2025-07-13 13:55:15 | Sleeping for 30 minutes...
```

**Comment by theguymadmax** [comment]
This seems to be an old issue without a proper solution: #9177

In that thread, a script was also created to monitor Jellyfin GPU Access: https://gist.github.com/alexfornuto/4ad3a501facbc780e1d48e3cb3fe02ef

**Comment by felix920506** [comment]
This appears to be something wrong with the container infrastructure rather than Jellyfin itself
cc @nyanmisaka @gnattu

**Comment by nyanmisaka** [comment]
There's nothing Jellyfin can do. A quick search will show you that this is a common issue with NVIDIA GPUs when used with containers like Docker. There are some fixes included that may work, but you'll have to try them out for yourself.

- https://github.com/NVIDIA/nvidia-container-toolkit/issues/48
- https://github.com/NVIDIA/nvidia-container-toolkit/issues/538
- https://github.com/ollama/ollama/issues/6928#issuecomment-2586208913

Alternatively, switch to an Intel Arc GPU and call it a day.

**Comment by felix920506** [comment]
Closing as not a Jellyfin bug.

**Comment by italocjs** [comment]
While i understand is not a jellyfin caused bug, it still a bug and others are very likely to run into it,  **i do not agree with closing the issue**, it should remain open until a proper fix is released (either by automatic restart script or actually discovering the cause).

nvidia is by far the most used gpu, it makes no sense to suggest people to change their hardware. HW is expensive, maybe not a problem for US, but definitely a huge problem for all the rest of the world.

**Comment by nyanmisaka** [comment]
NVIDIA commented in Feb 2023 that ["a fix will be available in the next patch release of all supported NVIDIA GPU drivers"](https://github.com/NVIDIA/nvidia-container-toolkit/issues/48).

It is now 2025, the issue still exists, and NVIDIA has closed the ticket. So I have to assume that this issue will still not be properly fixed when GTX10/Pascal driver support reaches EOL, which is after the next major version 580.xx series.

I have to admit that I am biased against closed source drivers, especially when bugs cannot be fixed in a timely manner. It is precisely because NVIDIA does not follow the conventions of Linux DRM devices and creates many custom device files for user-mode closed source blob drivers and container toolkits to access that these troubles arise.

Therefore I would recommend mentioning this in the [Known Hardware/Driver Issues](https://jellyfin.org/docs/general/post-install/transcoding/hardware-acceleration/known-issues) section of the Jellyfin documentation, and keeping our issue tacker dedicated to tracking issues caused by Jellyfin itself.

**Comment by maru801** [comment]
There are multiple ways of installing and running Jellyfin. This is an issue between Docker and Nvidia GPUs specifically.

**Comment by felix920506** [comment]
@nyanmisaka https://github.com/jellyfin/jellyfin.org/pull/1456
