### ISSUE TITLE
10.11.0.RC4 Files with audio delay relative to the video won't start playing on WebOS

### ISSUE THREAD

**Issue by ErebZx** [jellyfin/jellyfin#14581]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our [forum or chat rooms](https://jellyfin.org/contact/) first to troubleshoot with volunteers, before creating a report.
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When I try to play a .mkv file with audio delay relative to the video on WebOS LG C2, it simply won't start playing, the loading circle keeps spinning indefinitely. This is a new bug on RC4 and it might have something to do with [pull request 14553](https://github.com/jellyfin/jellyfin/pull/14553)

### Reproduction steps

Play any file that has audio delay relative to the video on WebOS LG C2.

### What is the current _bug_ behavior?

Loading circle keeps spinning indefinitely. 

### What is the expected _correct_ behavior?

Playback.

### Jellyfin Server version

Unstable

### Specify the build version

10.11.0.RC4

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
[2025-08-05 01:27:28.270 +02:00] [INF] [17] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Miloš". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2025-08-05 01:27:29.387 +02:00] [INF] [17] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "ffmpeg" "-analyzeduration 200M -probesize 1G -fflags +genpts  -i file:\"C:\Users\Milos\Downloads\Movies\Signs.2002.2160p.WEB-DL.DTS-HD.MA.5.1.DV.HDR.H.265-FLUX.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 dvh1 -strict -2 -bsf:v hevc_mp4toannexb,hevc_metadata=remove_hdr10plus=1 -start_at_zero -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename \"C:\Users\Milos\AppData\Local\jellyfin\cache\transcodes\980251df5878f097992352c66ecccf96-1.mp4\" -start_number 0 -hls_segment_filename \"C:\Users\Milos\AppData\Local\jellyfin\cache\transcodes\980251df5878f097992352c66ecccf96%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -hls_segment_options movflags=+frag_discont -y \"C:\Users\Milos\AppData\Local\jellyfin\cache\transcodes\980251df5878f097992352c66ecccf96.m3u8\""
[2025-08-05 01:28:31.377 +02:00] [ERR] [26] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Unexpected end of request content". URL "POST" "/Sessions/Playing".
[2025-08-05 01:28:31.436 +02:00] [INF] [29] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "C:\Users\Milos\AppData\Local\jellyfin\cache\transcodes\980251df5878f097992352c66ecccf96.m3u8"
[2025-08-05 01:28:31.598 +02:00] [INF] [26] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.18.6" closed
[2025-08-05 01:28:31.640 +02:00] [INF] [29] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2025-08-05 01:28:31.644 +02:00] [INF] [29] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "C:\Users\Milos\AppData\Local\jellyfin\cache\transcodes\980251df5878f097992352c66ecccf96.m3u8"
[2025-08-05 01:28:33.672 +02:00] [INF] [17] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.11.0" playing "Signs". Stopped at "0" ms
[2025-08-05 01:32:15.924 +02:00] [INF] [31] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2025-08-05 01:36:03.918 +02:00] [INF] [32] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
```

### FFmpeg logs

```shell
It doesn't fit here, so I'll attach it.
```

### Client / Browser logs

[FFmpeg.DirectStream-2025-08-05_01-27-29_80cffdd0eac21c7f3236873227d38e84_724a3b2e.log](https://github.com/user-attachments/files/21586106/FFmpeg.DirectStream-2025-08-05_01-27-29_80cffdd0eac21c7f3236873227d38e84_724a3b2e.log)

**Comment by nyanmisaka** [comment]
AFAIK the fMP4 HLS checkbox is off by default on web0s. Please turn it off and try again.

Additionally, this PR has been tested in the HLS.js demo in common browsers (including the HLS reference implementation, Safari), which passes the fMP4 segments directly to the browser player engine. If it doesn't work correctly, it's probably another quirk of web0s.

**Comment by ErebZx** [comment]
It used to be turned off by default, but on 10.11 we need to turn it on in order to get Dolby Vision support, it doesn't work in .ts anymore. [Pull Request 6678](https://github.com/jellyfin/jellyfin-web/pull/6678)
It plays with fMP4 checkbox unchecked, but it falls back to HDR10.

**Comment by nyanmisaka** [comment]
That change wasn't actually tested extensively, and it caused another regression. https://github.com/jellyfin/jellyfin-web/issues/7023

**Comment by ErebZx** [comment]
I compiled the last stable version 10.10.7 with just that change to add extra movflags to fMP4 to take initial audio delay into account, and I still get the same result on WebOS like I get on RC4, file with audio delay doesn't play at all. We can rule out that switching to hls.js on WebOS has anything to do with this issue.

I also did testing with the sample file you provided, and strangely enough, I don't have any issues with it on WebOS. With that demo file, it works just like you expect. Without your change, audio gets out of sync when i trigger transcoding in fMP4, but with your commit it plays fine even on WebOS and when I trigger transcoding in fMP4, delay is there and audio and video are in sync.

The issue is with this file, you can see mediainfo below. When I play the file on WebOS without your commit, it transcodes the audio to ACC because TV doesn't support DTS, and it plays correctly in .mp4 container with fMP4 enabled, respecting the audio delay so audio and video are in sync and it also triggers Dolby Vision. When I play the same file with your commit, ether on 10.10.7.+yourcommit or 10.11.0.RC4 it doesn't play at all, the circle just keeps spinning. 


Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile A compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 46 min
Bit rate                                 : 24.7 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 076 pixels
Display aspect ratio                     : 1.85:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.129
Stream size                              : 18.4 GiB (92%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0050 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1063 cd/m2
Maximum Frame-Average Light Level        : 107 cd/m2

Audio
ID                                       : 2
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 1 h 46 min
Bit rate mode                            : Variable
Bit rate                                 : 2 238 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Delay relative to video                  : 5 s 990 ms
Stream size                              : 1.67 GiB (8%)
Title                                    : DTS-HD MA 5.1
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Comment by nyanmisaka** [comment]
Can you test playback of the file in Chrome browser on desktop? Since Chrome supports HEVC but not DTS, it should trigger the same DirectStream behavior.

If playback fails as it does on web0s, providing the browser's F12 console error log and a video sample would be helpful.

**Comment by timitt** [comment]
> That change wasn't actually tested extensively, and it caused another regression. [jellyfin/jellyfin-web#7023](https://github.com/jellyfin/jellyfin-web/issues/7023)

Seems that my pull request is not liked (at least by people who do not have WebOS TV). I still consider it necessary compared how poorly native HLS works on WebOS even if some very high bitrate videos are not working well. I did test it with many 4K videos, but apparently the bitrates were not high enough to see that issue.

As for this issue:
I did look into this audio delay with HLS issue when I tested my pull request as discussed on forums.
If audio started later than in the first HLS packet then it did not work correctly. I mean if first mp4 file that ffmpeg generated was 10 seconds and audio started on 12 seconds then it just did not work no matter what flags I used with ffmpeg.

I wonder if @ErebZx test case is like that.

But it did work if I made separate audio and video streams (just like HLS examples I found in Internet were). Its just that Jellyfin does not separate streams. Separating those streams would also allow WebOs to play natively eac3 and ac3 audio with hls.js.

These tests were made using jellyfin version of ffmpeg and playing them through hls.js demo. No Jellyfin was involved in my tests.

**Comment by nyanmisaka** [comment]
> > That change wasn't actually tested extensively, and it caused another regression. [jellyfin/jellyfin-web#7023](https://github.com/jellyfin/jellyfin-web/issues/7023)
> 
> Seems that my pull request is not liked (at least by people who do not have WebOS TV). I still consider it necessary compared how poorly native HLS works on WebOS even if some very high bitrate videos are not working well. I did test it with many 4K videos, but apparently the bitrates were not high enough to see that issue.
> 
> As for this issue: I did look into this audio delay with HLS issue when I tested my pull request as discussed on forums. If audio started later than in the first HLS packet then it did not work correctly. I mean if first mp4 file that ffmpeg generated was 10 seconds and audio started on 12 seconds then it just did not work no matter what flags I used with ffmpeg.
> 
> I wonder if [@ErebZx](https://github.com/ErebZx) test case is like that.
> 
> But it did work if I made separate audio and video streams (just like HLS examples I found in Internet were). Its just that Jellyfin does not separate streams. Separating those streams would also allow WebOs to play natively eac3 and ac3 audio with hls.js.
> 
> These tests were made using jellyfin version of ffmpeg and playing them through hls.js demo. No Jellyfin was involved in my tests.

Dolby Vision playback on web0s has always been tricky. Issues keep popping up like a game of whack-a-mole.

This comment is instructive: Jellyfin uses a 6-second HLS time for DirectStream, but the actual segment position is based on the video's GOP. The OP's MKV video has an audio delay of `5 s 990 ms`, so it might just be running into this quirk.

**Comment by ErebZx** [comment]
I can confirm this issue is the same regardless of using hls.js or native hls. It's not that people dislike that pull request, it causes issues and it might not be needed very soon. Good news is that LG has confirmed that multi-channel audio issue is fixed with WebOS 25 version 33.20.65 on this year's models, and the fix is coming to older models soon, probably with WebOS 25. Also, with WebOS 25 LG Player finally supports Dolby Vision Profile 5 & 8 in mkv containers, so even remuxing won't be necessary, this is confirmed on beta versions on C2 and onward. Hopefully WebOS will be more stable when WebOS 25 arrives.

Back to this strange issue, I tested playback on Chrome, and it works as it should, audio transcodes to AAC, audio delay is respected and both audio and video are in sync. I tried again on WebOS, but still the same, it shows the Dolby Vision logo in the corner but the loading circle keeps spinning forever and it never starts playing. I also tried enabling and disabling Use shorter HLS segments option, but it doesn't make any difference, it still won't play.

**Comment by nyanmisaka** [comment]
> Back to this strange issue, I tested playback on Chrome, and it works as it should, audio transcodes to AAC, audio delay is respected and both audio and video are in sync. I tried again on WebOS, but still the same, it shows the Dolby Vision logo in the corner but the loading circle keeps spinning forever and it never starts playing. I also tried enabling and disabling Use shorter HLS segments option, but it doesn't make any difference, it still won't play.

So it's essentially a bug specific to the web0s video player (or media engine) mentioned above, and it doesn't manifest itself anywhere else. It happened to work in the past because FFmpeg incorrectly set the initial decode timestamp of audio packets in fMP4 containers to 0, even though they were actually delayed by several seconds.

The fMP4 player needed to parse and get this value to correctly apply the audio delay, something that was previously overlooked, but somehow web0s relied on this bug to work properly.

**Comment by ErebZx** [comment]
I still find it strange how inconsistent it is when it comes to deciding to apply delay or ignore it.
On 10.10.7 without your commit, my file still plays fine in Chrome with transcoded audio in mp4 container, audio delay is applied, It's the same on WebOS. On the other hand, your demo is out of sync, audio delay is ignored.
On version with your commit, your demo is fixed, my file plays fine in Chrome just like before, but it doesn't play at all on WebOS.

**Comment by nyanmisaka** [comment]
> I still find it strange how inconsistent it is when it comes to deciding to apply delay or ignore it. On 10.10.7 without your commit, my file still plays fine in Chrome with transcoded audio in mp4 container, audio delay is applied, It's the same on WebOS. On the other hand, your demo is out of sync, audio delay is ignored. On version with your commit, your demo is fixed, my file plays fine in Chrome just like before, but it doesn't play at all on WebOS.

The A/V desync issue can be reproduced not only in my sample, but also in the sample provided in the original issue. So I am also curious why this video file works normally in 10.10 and Chrome on your side.

https://github.com/jellyfin/jellyfin/issues/13085#issuecomment-3126060408

**Comment by ErebZx** [comment]
I don't know why it works on 10.10 while your demo doesn't work. 
One more thing came to mind, I went back to 10.11.RC4 and tried to play my file using the built in web browser instead of the Jellyfin client on the TV, and the file plays fine. Video falls back to HDR10 instead of Dolby Vision, audio is transcoded to AAC, delay is applied so everything is in sync. Tried again using WebOS Jellyfin client, and it refused to start playback, same as before. So this might be an issue with WebOS Jellyfin client app, which hasn't been updated in a while.

**Comment by theguymadmax** [comment]
@ErebZx is still an issue?  The hls.js pr was reverted: https://github.com/jellyfin/jellyfin-web/pull/7296

**Comment by ErebZx** [comment]
Yes, it is. It was not caused by hls.js. Updating my TV to WebOS 25 didn't fix it either.
