### ISSUE TITLE
Audio out of sync on recordings

### ISSUE THREAD

**Issue by matthewpritchett** [jellyfin/jellyfin#14713]
### Description of the bug

When trying to play back a recorded tv show from a HdHomerun, the audio and video playback is out of sync when using the “prefer fmp4” option that’s default enabled on the web client. 

### Reproduction steps

Record a live tv show
Play back the live tv show in the web browser
Observe audio out of sync

### What is the current _bug_ behavior?

Audio is out of sync with the video

### What is the expected _correct_ behavior?

Audio and video will play in sync like how it does when watching live tv

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.7

### Environment

```markdown
- OS: Docker
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
No logs
```

### FFmpeg logs

```shell

```

**Comment by matthewpritchett** [comment]
Maybe an idea could be having a “allow fmp4 container” option for libraries so we can just disable it on the entire Recordings library if determining it based on video doesn’t work.

**Comment by matthewpritchett** [comment]
Or maybe even to just treat .ts files as never using fmp4 container due to the potential timestamp issues with them.

**Comment by handyrandyrc** [comment]
Confirmed, this is an issue I experience using the web client.  Also seems slightly out of sync (though less so) on the iOS client.

**Comment by nyanmisaka** [comment]
A similar issue was fixed in 10.11 RC not long ago.

https://github.com/jellyfin/jellyfin/pull/14553

**Comment by matthewpritchett** [comment]
> A similar issue was fixed in 10.11 RC not long ago.
> 
> [#14553](https://github.com/jellyfin/jellyfin/pull/14553)

That looks like it should be the solution from looking at my video files. Will wait until it’s released to check and verify. Thank you!

**Comment by matthewpritchett** [comment]
10.11 fixed this issue. Closing.

**Comment by clockwinder** [comment]
@matthewpritchett 

I'm still having this issue, was there anything additional you tweaked to fix it?

**Comment by matthewpritchett** [comment]
Nope, I do know there seemed to be an issue with iOS and audio sync that was different. Mine was just a case of my local OTA always having an audio delay on stuff. You might want to open a new issue if yours was different? Or I can reopen this if its the same symptoms.

**Comment by clockwinder** [comment]
Mine sounds very similar in that when playing recordings via web-UI the audio is out of sync, whereas I can play the file via VLC and the sync is correct.
