### ISSUE TITLE
Can't play or shuffle album on 10.11.0

### ISSUE THREAD

**Issue by qrhfz** [jellyfin/jellyfin#14900]
### Description of the bug

I upgraded to 10.11.0 RC8 from 10.10.7. In 10.11.0 RC8 when i press shuffle or play it will throw error screen that says:
> Playback Error
> Unable to find a valid media source to play.

Instant mix button still works though.

### Reproduction steps

1. make a copy from 10.10.7
2. start a 10.11.0 RC8 instance
3. open a music album
4. press either play or shuffle

### What is the current _bug_ behavior?

can't play. shows error screen.

### What is the expected _correct_ behavior?

play the album normally

### Jellyfin Server version

10.10.0+

### Specify the build version

10.11.0-rc8

### Environment

```markdown
- OS: linux
- Linux Kernel:
- Virtualization: podman
- Clients: browser
- Browser: firefox
- FFmpeg Version: idk, builtin
- Playback Method: direct play
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: caddy
- Base URL:
- Networking: host
- Jellyfin Data Storage: local ssd
- Media Storage: local hdd
- External Integrations:
```

### Jellyfin logs

```shell
log too long i put in additional notes text field.
```

### FFmpeg logs

```shell

```

### Additional information

Jellyfin log here:
[log_20250929.log](https://github.com/user-attachments/files/22587499/log_20250929.log)

**Comment by theguymadmax** [comment]
https://notes.jellyfin.org/v10.11.0_features#

"After the migration it is recommeded that you perform a full scan though the admin dashboard. We have observed that for some users, some elements might not work properly otherwise (e.g. genres). The first scan after the migration might also take quite a bit longer then usual, though subsequent scans should be as quick as before."

Edit: You'll need to scan your library with the "Search for missing metadata" option.

**Comment by uuuu1234** [comment]
> https://notes.jellyfin.org/v10.11.0_features#
> 
> "After the migration it is recommeded that you perform a full scan though the admin dashboard. We have observed that for some users, some elements might not work properly otherwise (e.g. genres). The first scan after the migration might also take quite a bit longer then usual, though subsequent scans should be as quick as before."
> 
> Edit: You'll need to scan your library with the "Search for missing metadata" option.

I did a full scan and also did the "Search for missing metadata", the issue remains.

**Comment by Haui1112** [comment]
So, the music playback, even after full scan with metadata, is broken. A downgrade is impossible because the database has been changed. I nuked the whole database and will pin the version to 10.10.7 for the foreseeable future. Thank you for working on this, I appreciate the hell out of the app. Still sad that this breaking change happened. Then again, I could have had backups. You live, you learn.

**Comment by Wurzelmann** [comment]
Same problem here: after the upgrade to 10.11.0, music playback is broken, movies/series are unaffected by this. Full library scan and missing metadata scan did nothing to resolve this issue unfortunately.

EDIT: okay, it started working again, it seems the metadata search and replace check took longer than expected and now music playback is possible again...

**Comment by exalented** [comment]
Found this by not being able to play the album but able to play the song in the album.
Scanning my libraries individually solved all playback issues: 

1. Dashboard > Libraries > First do a full scan as recommended
2. Check to make sure plugins are updated
3. If you have deploy > resources > limits make sure you give it some more cores
4. Restart server (docker compose down; docker compose up -d)
5. Dashboard > Libraries > Choose each library and click "Search for missing metadata"

Longest time spent was on my music library. This process took ~30 mins

```
Movies: 886
Series: 32
Episodes: 1,443
Albums: 361
Songs: 3,821
```

**Comment by Shadowghost** [comment]
As mentioned in the release notes this is what you should to do on your music libraries after the initial scan, glad it fixed it for you

**Comment by william-sy** [comment]
Tried the upgrade 3 times now. Each time failed each time more and more scanning, before and after the upgrade 7 restarts of jellyfin before and after the upgrade its just broken. Its just faster to start fresh than upgrade at this point.

**Comment by ghost** [comment]
My music playback is also broken. I cannot rescan the library because i run into this issue: https://github.com/jellyfin/jellyfin/issues/15000

I have ~39000 songs in the library. Had to revert back to 10.10.7

**Comment by muja** [comment]
Really unfortunate. I wasn't even aware that there was a major change and just clicked "apply update". Now all of the apps are broken, Finamp/Supersonic to name a few, albums don't load, some artists won't show up at all.
When the DB has a breaking change, there should definitely be a path to migrate in the other direction. Or at least a backup should be made prior to upgrading... Please tell me one of those methods is possible, I'm happy to shell into the DB if necessary.

**Comment by transcaffeine** [comment]
https://github.com/jellyfin/jellyfin/issues/14900#issuecomment-3426191550

Can confirm this worked for me aswell after the same described problems

**Comment by GreymatterPrison** [comment]
I am having issues with Music Playback. All other media is available with no issues. Log shows NO errors or issues. When trying to playback Music I am met with ``` Playback Error
Unable to find a valid media source to play ```. 

<img width="323" height="88" alt="Image" src="https://github.com/user-attachments/assets/3d305d44-5796-42c0-8d7f-c376c139a036" />

**Comment by ac2323** [comment]
> I am having issues with Music Playback. All other media is available with no issues. Log shows NO errors or issues. When trying to playback Music I am met with `Playback Error Unable to find a valid media source to play`.
> <img alt="Image" width="323" height="88" src="https://private-user-images.githubusercontent.com/196854754/505670212-3d305d44-5796-42c0-8d7f-c376c139a036.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NjMzMTIsIm5iZiI6MTc2MTY2MzAxMiwicGF0aCI6Ii8xOTY4NTQ3NTQvNTA1NjcwMjEyLTNkMzA1ZDQ0LTU3OTYtNDJjMC04ZDdmLWMzNzZjMTM5YTAzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyOFQxNDUwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmNmN2IzNjI5YTNhMmZiYWQ4NzZmNWM3NzVhNWY1NmUxMDZkNjMxY2RkZmNkZDQwMGI0OWY4MWFjODVmMDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0L1ndODYBIbizUwt7oxn97CXvWJJp3EHbUrTOmsjcVA">

Having the same issue, there are no logs for the error beyond what you see on the screen when trying to play music. I'm on 10.11.1

**Comment by Kissyboots** [comment]
I worked around the problem by removing Jellyfin completely (server and client), reinstalling from scratch, deleting all libraries, and then recreating all libraries from scratch, as well.

**Comment by ac2323** [comment]
I restored a backup made from 10.11.2 (database only) onto a clean instance on a brand new LXC and the result is the same.

The only thing that seemingly helped is reinstall Jellyfin on a clean system without migrating anything over.

**Comment by 2mac** [comment]
I was having this issue and after reading this thread and another one about TV show seasons, it seems that running the scan to search for metadata does eventually work.

At first, I saw lots of errors in the log file related to plugins, so I rebooted the entire system and kicked off the scan again. It took quite a long time on my library, and I kicked it off multiple times. I could only see progress in the logs, seeing a few things failing to fetch metadata and the occasional "Updated xxx items" line. Slowly but surely, a few album covers were now clickable on the main page, and after enough waiting, all of them seem to be, including ones I search for.

This is definitely not an ideal user experience, because it is in no way obvious that anything is actually improving unless you go looking in the logs to see that it's even doing anything, and it will still take a while for large libraries before an album you're trying to play is repaired. In fact, my playlists appeared to be completely missing right after the upgrade, but again with enough waiting, they reappeared and play just fine.

For those like me who rolled back at the first sign of trouble after upgrading, try queuing up a few missing metadata scans and going outside for a while. :)

**Comment by william-sy** [comment]
> For those like me who rolled back at the first sign of trouble after upgrading, try queuing up a few missing metadata scans and going outside for a while. :)

But reinstalling from scratch is just 1 re scan and it works. Having my NAS re scanning over and over is not only time consuming, also wears the HDD down (if this is even noticeable in terms of life span is debatable). and I have to keep looking at logs. (now there is a progress bar for this, but if you look quickly you will miss it as its not at a obvious place at all)

So yes, the upgrade path is far from perfect ; and if it fails on you more than 1 time its sometimes faster to just start from scratch (it was in my case anyway)

**Comment by NoxiousPluK** [comment]
I had this same issue, but got it resolved after complete 'Search for missing metadata' scan.
I did however run into an issue that the scan gives no UI feedback that it is still ongoing, so for a while it only worked for about half my music and I couldn't figure out why - spend some hours debugging.

**Environment:**
- Jellyfin 10.11.2+ubu2404 on Ubuntu 24.04 LTS
- Installed via official Jellyfin APT repository (NOT Docker/containerized)
- Repository: https://repo.jellyfin.org/ubuntu (noble/main)
- Upgraded from 10.10.7 → 10.11.2 on 2025-11-12
- Media stored on NFS4 mount (TrueNAS Server)

**Initial symptoms:**
After upgrading to 10.11.2, experienced the same "Unable to find a valid media source to play" error when using Play/Shuffle album buttons.

**Resolution:**
Issue fully resolved after running a complete metadata scan on all music libraries. However, the resolution was delayed because **there was no clear UI indication that the scan was still in progress**. I initially thought the scan had completed, but albums that "failed" were actually just not yet processed.

**Suggestion:** 
Improve scan progress feedback in the UI. Let me know if I should open a separate issue for that.

**Comment by theguymadmax** [comment]
This issue was fixed in 10.11.3 ( #15446). There was a bug in 10.11.0 → 10.11.2 for users migrating their old DB (10.10.x) to 10.11.x. The ancestor IDs were not migrated. This caused several issues, such as not being able to play or shuffle an album, playlists disappearing, plus other issues.

The bug fix only applies to users doing a database migration from 10.10.x to 10.11.3. It does not fix the issue for those already on 10.11.x.

For those on 10.11.x, you have to scan each library with the “scan for missing metadata” option to repopulate the ancestor IDs.
Also, due to other issues, many people have errors such as DB locks, so these scans will sometimes fail, and you may need to scan multiple times for the database to repopulate with the ancestor ID. 

If the scan doesn’t work for you and you have a backup of 10.10.x, then you can restore your backup copy, then re-migrate. Note, there is no rolling back; you must still have a backup copy to try again.

**Comment by marscat5** [comment]
> The bug fix only applies to users doing a database migration from 10.10.x to 10.11.3. It does not fix the issue for those already on 10.11.x.
> 
> For those on 10.11.x, you have to scan each library with the “scan for missing metadata” option to repopulate the ancestor IDs. Also, due to other issues, many people have errors such as DB locks, so these scans will sometimes fail, and you may need to scan multiple times for the database to repopulate with the ancestor ID.
> 
> If the scan doesn’t work for you and you have a backup of 10.10.x, then you can restore your backup copy, then re-migrate. Note, there is no rolling back; you must still have a backup copy to try again.

- @theguymadmax: Thank you very much for the detailed information. May I ask why the developers did not apply the fix for those who are already on 10.11.x or is there a chance, for a fix on 10.11.4?
- I also think the suggestion from @DoogeJ is very helpful. I had the same situation. The GUI just tells me, the refresh process is in a queue. Is there a way to see the queue and the progress? (I used this page from admin dashboard: https://jellyfin/web/#/dashboard/libraries)

**Comment by tw333k** [comment]
after running library scan as suggested...
`[2025-12-07 13:53:57.909 +11:00] [ERR] [53] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Shows/1509364d588992381eca17548392e0ab/Seasons".
System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by SanderK79** [comment]
I also expierence the same issue after he “scan for missing metadata” 

`[2025-12-13 19:59:10.770 +00:00] [ERR] [45] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Shows/2e2fc81d6c2d2190eaa498da60b6ad89/Seasons".
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Controller.Entities.TV.Season.GetItemsInternal(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.FillUserDataDtoValues(UserItemDataDto dto, UserItemData userData, BaseItemDto itemDto, User user, DtoOptions fields)`

Any workaround available ?

**Comment by denilsonsa** [comment]
I have finally decided to search why Jellyfin stopped being able to play a music album, and I have finally found this issue here. Almost one year later.

I wonder how many people still have this issue and either haven't noticed or just assumed it's broken and will be eventually fixed in a newer version.

---

This could have been handled better. If the fix is indeed "for each library, rescan it with a certain parameter (search for missing metadata)", and this fix should have been automatic. Jellyfin should have been able to auto-detect this problem, and should have included this one-time very specific scan in the "Scan Media Library" scheduled task (that most people already have). This would fix the issue for everyone, without requiring each person to look for information.

But, well, this ship has sailed. I'm grateful for the work done on Jellyfin, but I still think Jellyfi should have self-healed itself.
