### ISSUE TITLE
Sorting does not work after upgrading to 10.11.0

### ISSUE THREAD

**Issue by patrickdk77** [jellyfin/jellyfin#15229]
### Description of the bug

Upgraded to 10.11.0 and now when soring a library by date added, date epsiode added, date played, date released, the order seems random, it's not even close to being correct as it was previous to the upgrade. This is happening in all my libraries. series that a years old are shown to be the newest

This is not affecting recently added though.

### Reproduction steps

install 10.0.0, add series, note order, upgrade to 10.11, note order

### What is the current _bug_ behavior?

not in date order

### What is the expected _correct_ behavior?

should be in the date order selected for the library

### Jellyfin Server version

10.10.0+

### Specify version number

10.11.0

### Specify the build version

10.11.0

### Environment

```markdown
- OS:ubuntu 24.04
- Linux Kernel: 6.8
- Virtualization: docker
- Clients: browser
- Browser: brave
- FFmpeg Version: none
- Playback Method: none
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: none
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
[2025-10-26 12:53:12.503 -04:00] [INF] [72] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2025-10-26 12:53:14.210 -04:00] [INF] [72] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2025-10-26 12:53:14.692 -04:00] [INF] [71] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2025-10-26 13:03:02.693 -04:00] [INF] [39] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
```

### FFmpeg logs

```shell

```

**Comment by Shadowghost** [comment]
Should already be fixed by https://github.com/jellyfin/jellyfin/pull/15187 - please close if 10.11.1 fixes this once released

**Comment by patrickdk77** [comment]
Hmm, there is no 10.11.1 release, if there was I would have tested it.

**Comment by Shadowghost** [comment]
As I wrote: "once released", fix was already merged but not released with any version.
Should be available now.

**Comment by patrickdk77** [comment]
It somewhat works with 10.11.1

Show by date episode added works correctly.
But Date Show Added still does not work, it's showing shows where all added recently that are years old.
It says it uses the value from libraries->display->date added behavior, that is set to Use file creation date

in jellyfin it says, Date added: 09/25/2025 in the shows metadata

But I have:
Access: 2023-04-13 21:17:43.687668779 -0400
Modify: 2025-09-25 12:16:25.791401535 -0400
Change: 2025-09-25 12:24:01.344135077 -0400
Birth: 2021-11-06 01:31:40.711826239 -0400

So it's not using creation date, but modified or change date instead now.

**Comment by Shadowghost** [comment]
What happens if you do a replace all metadata on such a show? We fixed some things in the date handling, so it's quite possible that you had bad data in the DB before and it just only showed now.

**Comment by patrickdk77** [comment]
That did not work out :(

<img width="245" height="107" alt="Image" src="https://github.com/user-attachments/assets/5fbefd43-a681-475d-8720-d7d755d212d3" />
This happens for any show I do replace all metadata on, the date goes to 01/01/1901

**Comment by welshtralian** [comment]
Hello. As the title is quite generalised, I would like to add that the sort order (by channel number) on Live TV isn't correct either, it seems to be based on recent channel watched. I've clicked on the radio buttons to recently watched and then back to by channel number to see if that resets the order but it does not.

**Comment by patrickdk77** [comment]
This is really painful. All the date added fields have been reset, on every tv show, music, book, live tv entries.
It seems new items added after 10.11.1 work ok, but anything that was added before 10.11.1 is messed up.

10.11.2 does not fix anything either, they are all still messed up after a rescan.

**Comment by urbenlegend** [comment]
> It seems new items added after 10.11.1 work ok, but anything that was added before 10.11.1 is messed up.

Does that mean deleting the library and recreating it will workaround the issue for now?

**Comment by patrickdk77** [comment]
No, as if you delete it and recreate it, all the dateadded will be the current date. That is not much different from every date being 1901, so same problem, just different value.

**Comment by patrickdk77** [comment]
It does mean, going forward, if the problem is fixed, it will not be wiped out anymore by doing a rescan though.

**Comment by SeHansson** [comment]
Stupid me updated on my Unraid server without checking anything. Now "Recently Added" is complete chaos. I feel very angry with myself!

**Comment by noncrab** [comment]
I'm also seeing similar, but sorting by date played hasn't worked since I upgraded to 10.11.2 (from 10.10.x), including for things I've watched since. Specificailly, when a TV shows library for series showed by "played date" descending, it'll show me things i've never watched at the top.

**Comment by orzechszek** [comment]
I still have sorting problem in 10.11.3

**Comment by choss38** [comment]
I still have this sorting problem in 10.11.5 too.
Recently added in the Home page are ok, but the filter to sort a library by added date doesn't work.

**Comment by maddoglee** [comment]
I'm having a similar problem in 10.11.5, which specified a movie added on the 6 Jan 2026 as being added to my library as the release date (6 Feb 2025). Should I open a new issue? 
or is this related? 
(or am I doing something wrong? is there an option to match date scanned into library to match release date??)
Its a bit frustrating, because the whole functionality of recently added items doesn't work anymore...

**Comment by Gabriel-Aurelius** [comment]
Here's my experience over the last couple weeks and figured I'd add something that might help the devs and other users:

1) I tried upgrading from 10.3 to 11.5 and it buggered everything
2) I wiped and did a fresh install of 11.5, taking the time to re-scan everything
          ~ 3,800 movies, ~ 23,500 tv episodes, and 300 collections
3) Sorting for [Doctor Who](https://www.themoviedb.org/tv/57243-doctor-who/) does not work at all, and specials episodes show before the season rather than after
          Neither Libraries > Display, nor Metadata Manager > Display Order affect them
4) Previously on 10.3 they showed at the end with no issues

These are the steps I took to try and remediate, but none worked:

1) I normally keep the Doctor Who special episodes within their season folder (again, works flawlessly on 10.3)
2) I moved them to the Specials folder and selecting Libraries > Display > "Display specials within seasons they aired in"
3) Dashboard > Scan All Libraries > logout and back in
          This failed to show them within the season folders
4) I moved the episodes back to their respective season folders
5) Metadata Manager > TV Shows (my folder for shows) > Doctor Who
6) Display Order > Original Air Date (this works in 10.3 flawlessly)
          This failed so I searched and found this outstanding issue and made this comment

I know the devs are working on this and I appreciate the FOSS aspect of Jellyfin. I also get that the database upgrades and work that has been done for 10.11 was necessary and at this point we're "failing forward". I wanted to provide an example I hadn't see in this thread with some details that might help the devs figure this one out.

I feel like Doctor Who is the quintessential example to solve for in this problem because both the "Display specials within seasons they aired in" and the "Display Order > Original Air Date" aspects have been tested independently from one another and neither solve this problem. Again, this was done on a clean installation of 11.5 from scratch.

Good luck team

**Comment by dareyouyr** [comment]
I'm using Jellyfin 10.10.7.
When I sort the library by Date Added, the result is identical to sorting by Name.
Other sort options work correctly, and this only happens with Date Added.
So it appears there is a bug where Date Added sorting is incorrectly following Name sorting.

**Comment by ACay047** [comment]
ADD SORTING TO COLLECTIONS SECTION

**Comment by Baldilocks47** [comment]
Adding a distinct trigger mechanism I haven't seen mentioned in this thread, in case it's useful.

Setup: Jellyfin 12.0/12.1 (upgraded from 10.11.x), media on TrueNAS SCALE over CIFS (vfs objects: streams_xattr shadow_copy_zfs ixnas zfs_core io_uring), mounted with serverino.

Confirmed root cause on my system: atime was enabled on the ZFS dataset backing the share. Every read (Jellyfin's directory watchers, playback, thumbnail generation, IntroSkipper analysis, etc.) updates atime, which is metadata TrueNAS's zfs_core VFS module folds into the SMB File ID it exposes to clients. That File ID was drifting every few minutes on files that were never touched — confirmed via repeated stat -c '%i' against the same file, no writes in between, inode changing on each check even with serverino in place and no snapshot tasks running. Jellyfin was reading the changed File ID as "new file, never seen before" and re-stamping DateCreated accordingly. Setting atime=off on the dataset stopped the inode drift entirely (confirmed stable across 7+ minutes, multiple checks).

Separately, and still ongoing even with atime fixed: two of my TV libraries with many similarly-named alternate-version files (a compilation-style series, and a show with many differently-named release variants of the same episodes) continue to get their DateCreated reset on every library scan. Logs show core repeatedly demoting/promoting which file is the "primary" version and then failing to clean up the orphaned LocalAlternateVersion rows:

MediaBrowser.Controller.Entities.BaseItem: Demoting old primary X to alternate of new primary X
...
Jellyfin.Server.Implementations.Item.ItemPersistenceService: Deleting N orphaned LocalAlternateVersion items for video X
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'

This fires on essentially every scan for these two titles specifically, and appears to be Jellyfin's own automatic alternate-version detection re-matching files as "versions of each other" each time, rather than anything user-configured (no "Ungroup Versions" option is available on these items, suggesting they aren't persistently grouped from the UI's perspective).

Can share full logs/DB excerpts if useful for tracking down the alternate-version matching logic specifically.
