### ISSUE TITLE
[regression] 10.11.0 now requires transcoding ALL content

### ISSUE THREAD

**Issue by skellycode** [jellyfin/jellyfin#15242]
### Description of the bug

After upgrading to version 10.11, all content now requires transcoding/remuxing to play where this was not the case previously.
I used to be able to play ALL files from my library (10.10.7) with transcoding/remuxing disabled.  I now cannot play ANY files with transcoding/remuxing disabled (10.11.0).

### Reproduction steps

1) create a user with transcoding disabled and log into the Jellyfin WebUI (tested with Firefox)
2) run a simple file/codec (H264) on an old jellyfin version (such as 10.10.7) via a client of choice (such as via the WebUI).  File will play successfully.
3) run the same file on jellyfin 10.11 via the same client (tested on Firefox, Edge and Android TV) and the file will fail.

### What is the current _bug_ behavior?

Users with transcoding/remuxing disabled are unable to play content.

### What is the expected _correct_ behavior?

Users with transcoding/remuxing disabled should be able to play content as they were in 10.10.7.  I have had to enable transcoding in 10.11 to allow files to play.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.7 and 10.11.0

### Environment

```markdown
- OS: Docker on Debian Bookworm
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking:
- Jellyfin Data Storage:
- Media Storage: Local HDD
- External Integrations: None
```

### Jellyfin logs

```shell
OLD VERSION (i.e. 10.10.7) (WORKING CORRECTLY):
Playback Info
  Player - Html Video Player
  Play method - Direct playing
  Protocol - https
  Stream type - Video
Video Info
  Player dimensions - 1718x1306
  Video resolution - 854x480
  Dropped frames - 0
  Corrupted frames - 0
Original Media Info
  Container - mp4
  Size - 266.6 MiB
  Bitrate - 790 kbps
  Video codec - H264 Main
  Video bitrate - 695 kbps
  Video range type - SDR
  Audio codec - AAC LC
  Audio bitrate - 87 kbps
  Audio channels - 2
  Audio sample rate - 48000 Hz

NEW VERSION (10.11) (REQUIRES TRANSCODING/REMUXING):
Playback Info
  Player - Html Video Player
  Play method - Remuxing
  Protocol - http
  Stream type - HLS
Video Info
  Player dimensions - 1718x1306
  Video resolution - 854x480
  Dropped frames - 0
  Corrupted frames - 0
Remuxing Info
  Video codec - H264 (direct)
  Audio codec - AAC (direct)
Original Media Info
  Container - mp4
  Size - 266.6 MiB
  Bitrate - 790 kbps
  Video codec - H264 Main
  Video bitrate - 695 kbps
  Video range type - SDR
  Audio codec - AAC LC
  Audio bitrate - 87 kbps
  Audio channels - 2
  Audio sample rate - 48000 Hz
```

### FFmpeg logs

```shell

```

### Additional information

Thank you Jellyfin team for your hard work and dedication to the project :)

**Comment by Shadowghost** [comment]
Remux just means we are repackaging the stream to be compatible with the client (e.g. if you have mkv and want to watch on your web browser it likely needs to remux). This is not transcoding and doesn't require a lot of processing power. 10.11 got more strict on this due to issues with some browsers (this is controlled by the supported codec profile supplied to the server by the client)

**Comment by skellycode** [comment]
Thanks for the info.

If remuxing wasn’t needed before, why is it needed now?  It adds ann additional 20% CPU load to my server “uneccessarily” given that it worked flawlessly before?  Even my NVIDIA SHIELD now requires remuxing which it didn’t before (and that natively supports just about everything).  It kind of makes the ability to disable remuxing a useless option?  And again, adds unecessary load to my server CPU.

(Please correct me if I am wrong in anything here!)

**Comment by Bambus3000** [comment]
I second this, I'd really appreciate it if I were able to actually disable remuxing, since it messes  with an anamorphic 576p tv show of mine (not keeping the aspect ratio configured in the original mkv), where as 10.10.7 played the content beautifully. 

Please revert this change, as its downsides far outweigh whatever benefits you've decided it should have. Or make the option to disable the "Allow video playback that requires conversion without re-encoding" actually do it.

**Comment by fazadaoc** [comment]
same here. nearly all content i have now is being transcoded consuming resources and time and losing chapters for example
i used to be able to play in chrome web player nearly any mkv file with various codecs (10.10.7) and now it's transcoding all of them after i've updated to 10.11.1

<img width="409" height="584" alt="Image" src="https://github.com/user-attachments/assets/23b1bac6-6648-44cb-96f8-df339df7e215" />

i tried reverting back to 10.10.7 but now i cannot buil any container whether with 10.11.1 or older 10.10.7

**Comment by baradhili** [comment]
I'm getting this on the docker release - 10.11.3
`[12:04:42] [INF] [12] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for admin. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True [12:04:42] [INF] [22] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /cache/transcodes/41677aee024be18795d58e93d8758f55.m3u8 [12:04:42] [INF] [12] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request [12:04:42] [INF] [12] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -i file:"/anime/Amaenaideyo!!/Ah! My Buddha-2x03-Don't Come Back to Me!!.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -preset veryfast -crf 23 -maxrate 4397816 -bufsize 8795632 -profile:v:0 high -level 41 -x264opts:0 subme=0:me_range=16:rc_lookahead=10:me=hex:open_gop=0 -force_key_frames:0 "expr:gte(t,n_forced*3)" -sc_threshold:v:0 0 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(1024\,576*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(1024/a\,576))/2)*2,format=yuv420p" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "d352e11567f7bdcabb227edab827bde0-1.mp4" -start_number 0 -hls_segment_filename "/cache/transcodes/d352e11567f7bdcabb227edab827bde0%d.mp4" -hls_playlist_type vod -hls_list_size 0 -hls_segment_options movflags=+frag_discont -y "/cache/transcodes/d352e11567f7bdcabb227edab827bde0.m3u8" [12:04:42] [ERR] [22] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 254 [12:04:42] [ERR] [22] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/6f9e8554-2261-804a-46ef-27b00ee700ad/hls1/main/-1.mp4. MediaBrowser.Common.FfmpegException: FFmpeg exited with code 254 at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, Guid userId, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory) at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId) at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable1 segmentLength, Nullable1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable1 enableAutoStreamCopy, Nullable1 allowVideoStreamCopy, Nullable1 allowAudioStreamCopy, Nullable1 breakOnNonKeyFrames, Nullable1 audioSampleRate, Nullable1 maxAudioBitDepth, Nullable1 audioBitRate, Nullable1 audioChannels, Nullable1 maxAudioChannels, String profile, String level, Nullable1 framerate, Nullable1 maxFramerate, Nullable1 copyTimestamps, Nullable1 startTimeTicks, Nullable1 width, Nullable1 height, Nullable1 maxWidth, Nullable1 maxHeight, Nullable1 videoBitRate, Nullable1 subtitleStreamIndex, Nullable1 subtitleMethod, Nullable1 maxRefFrames, Nullable1 maxVideoBitDepth, Nullable1 requireAvc, Nullable1 deInterlace, Nullable1 requireNonAnamorphic, Nullable1 transcodingMaxAudioChannels, Nullable1 cpuCoreLimit, String liveStreamId, Nullable1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable1 audioStreamIndex, Nullable1 videoStreamIndex, Nullable1 context, Dictionary2 streamOptions, Boolean enableAudioVbrEncoding, Boolean alwaysBurnInSubtitleWhenTranscoding) at lambda_method4915(Closure, Object) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager) at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager) at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext) at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context) at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager) at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context) [12:04:42] [INF] [12] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /cache/transcodes/d352e11567f7bdcabb227edab827bde0.m3u8 [12:04:44] [INF] [12] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.11.3 playing Don't Come Back!!. Stopped at 0 ms`

**Comment by erwinkramer** [comment]
Please see https://github.com/jellyfin/jellyfin/issues/15988 as well for another specific transcoding issue on 10.11

**Comment by shawty** [comment]
I vote for roll back here too.  After spending weeks re-encoding loads of my media collection thinking this was my own fault, I am still unable to play anything.

In my case I am running Jellyfin in a virtual machine running Ubuntu on a Hyper-V host, so I don't have any hardware GPU.

Up until now I have always encoded my media for the lowest common denominator of the 3 TV's in my house that are used to play content on, since I updated to 10.11.0 everything is now being forced to be transcoded even though I know that the media does not need it, this has lead to me turning transcoding off in order to troubleshoot this, and now I get the "this file cannot be played on your device", which I know is not at all true because if I put the file on a USB and plug it in to the rear of the TV it plays perfectly fine.

Prior to 10.11.0 I had no problems at all.  media would be loaded and directly played in the JF web-client (as I say I always encoded them into a format that I knew would play on all 3 sets) via the TV's built in HbbTV compatible browser, but now it's jut a straight up NO, of JF sits there in a crashed/hung state forcing me to have to power cycle the device.

All I see in the jellyfin logs over and over is this when I turn transcoding on:

```
[2026-03-23 19:20:17.792 +00:00] [INF] WS "192.168.17.144" request
[2026-03-23 19:21:04.774 +00:00] [INF] User policy for "guest". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2026-03-23 19:21:10.551 +00:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -fflags +genpts  -i file:\"/mnt/lucinda/movies/tvprogs/King of The Hill/Season 06/King of the Hill (1997) - S06E14 - Of Mice and Little Green Men.mp4\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/var/cache/jellyfin/transcodes/e15734fb2422fa26143e884c1122ecb7%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/cache/jellyfin/transcodes/e15734fb2422fa26143e884c1122ecb7.m3u8\""
[2026-03-23 19:21:20.683 +00:00] [INF] FFmpeg exited with code 0
[2026-03-23 19:21:31.302 +00:00] [INF] Deleting partial stream file(s) "/var/cache/jellyfin/transcodes/e15734fb2422fa26143e884c1122ecb7.m3u8"
[2026-03-23 19:21:31.398 +00:00] [INF] WS "192.168.17.144" closed
[2026-03-23 19:21:32.879 +00:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.11.6" playing "Of Mice and Little Green Men". Stopped at "0" ms

```
and this when I turn it off:

```
[2026-03-23 19:32:17.325 +00:00] [INF] WS "192.168.17.144" request
[2026-03-23 19:32:57.171 +00:00] [INF] User policy for "guest". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2026-03-23 19:33:02.074 +00:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.11.6" playing "Of Mice and Little Green Men". Stopped at "0" ms
```

Please, please, please fix this JF team, you guys have by far THE BEST media system on the planet, at least roll it back until you can figure out a better way to deal with this.

**Comment by theguymadmax** [comment]
It looks like the issue is that Jellyfin 10.11.x now correctly detects anamorphic video resolutions, whereas the previous version didn’t classify the same media that way.

The problem is that anamorphic videos have always triggered a server-side remux, since the web client reported them as unsupported.

https://github.com/jellyfin/jellyfin-web/pull/7520 updates this behavior by telling the server that anamorphic videos are supported, which should stop the remuxing.

This fix is planned for the next major Jellyfin release (12.0).

**Comment by shawty** [comment]
@theguymadmax - thanks for the info, do you have an approx. timeline when v12 will be available, I will happily test it and feed it back.

As I say I thought it was my fault, so I re-encoded about a 3rd of my library ( Took weeks :-) ), my target devices are 3 Vestel based Opera-TV, TV sets (2 Toshiba branded, One Polaroid), Videos have always been encoded to h264 with AAC sound as that's the format these devices like best, I have a substantial number of files of many differing resolutions that I can test with.

I'm also about to go build a headless PC to run JF on, something with some actual hardware GPU in, see what happens when I do that, finally on the strength of what I've been reading here, I've just been test running the various FFMpeg commands from the log file directly at the SSH console on my VM, and they transcode without issue, and darn fast too....

Cheers
Shawty

**Comment by theguymadmax** [comment]
No timeline for the next version. But you can test out unstable builds. Each Monday there is a new build based on the current Master. Just browse to the appropriate latest-unstable folder, e.g., Windows: - https://repo.jellyfin.org/files/server/windows/latest-unstable/

Docker: You can use the "unstable" tag

This should only be for testing, so make a full backup if you're installing over an existing 10.11.x installation.

**Comment by n-peugnet** [comment]
> [jellyfin/jellyfin-web#7520](https://github.com/jellyfin/jellyfin-web/pull/7520) updates this behavior by telling the server that anamorphic videos are supported, which should stop the remuxing.
> 
> This fix is planned for the next major Jellyfin release (12.0).

It would be good if this fix could be backported to 10.11. looking at the patch it should be really easy to do.

**Comment by skellycode** [comment]
> > [jellyfin/jellyfin-web#7520](https://github.com/jellyfin/jellyfin-web/pull/7520) updates this behavior by telling the server that anamorphic videos are supported, which should stop the remuxing.
> > This fix is planned for the next major Jellyfin release (12.0).
> 
> It would be good if this fix could be backported to 10.11. linking at the patch it should be really easy to do.

**+1**
I am still on 10.10.7 as this issue is a deal-breaker for my setup.  It appears this would also be the case for others in this thread.

**Comment by skellycode** [comment]
With the push to update to the latest version to address CVE's, a backport solution to this issue now feels like a must.

There are lots of thumbs up for the comments on this issue, so it looks like there are many (like myself) who are refusing to upgrade with this issue still active.

What can we do to get some visibility of this by the devs?

**Comment by Pentaphon** [comment]
> a backport solution to this issue now feels like a must.

I don't understand why this hasn't been done by now.

**Comment by mschumacher69** [comment]
I'm on 10.11 and I'm not facing this issue on Android TV (transcoding disabled on my user). Or is this issue affecting the web player only?

**Comment by shawty** [comment]
> I'm on 10.11 and I'm not facing this issue on Android TV (transcoding disabled on my user). Or is this issue affecting the web player only?

I get it in the web player, and on the app on the T95 TV box I have.  Not tried it on my phone yet though...

With respect to disabling transcoding, when I do this, I just get a message on pretty much every video I try to play that says "Can't Play this file...", even when I know I have pre-encoded them to the lowest common denominator so they play on everything I own.

In fact if I copy the files from my NAS onto USB and plug them in directly my various TV's and sticks play them perfectly fine.

**Comment by mschumacher69** [comment]
Works fine on my Google TV Streamer 🤷🏼‍♂️

**Comment by timsummerer** [comment]
This is a massive problem for my Jellyfin server on my Raspberry Pi 4 B.
I've always relied on powerful clients and now even the LG C1 needs to receive transcoded files for h264 and mp3 for no reason via Jellyfin-Web.

Further, playback via Infuse on an Apple TV 4K (3rd gen/2022) suffers the same behavior unable to play files affected by this, it seems.

I concur this issue needs backporting and is not something to be brushed off as "will fix in next major release"

**Comment by shawty** [comment]
Just done a rebuild of my JF server, running 10.11.11 and this is still showing as a problem.

:-(

**Comment by theguymadmax** [comment]
This issue is expected to be resolved in the upcoming 12.0 release. No additional releases are currently planned for the 10.11.x branch. Closing as fixed

**Comment by shawty** [comment]
@theguymadmax - surely this should be closed as "won't fix" or "not fixed"?

I get that your not planning to do the backport, that's fine, BUT this page is THE number one hit in the search engines when 

searching for this issue, so "Closing as NOT Fixed" or "Closing as Won't Fix in 10.11.x" to communicate that intention to future persons is surely the correct response.

Helping people who get stuck with this, means no more additions to this thread, and less work for the team.

**Comment by shawty** [comment]
For those that land here in future - This issue has been Closed as "**Not Fixed**", you will need to be using the V12 branch when it is released.

**Comment by JPVenson** [comment]
thats not how this works. You have the clear info that the issue has been fixed and will be released in the next major version.

**Comment by shawty** [comment]
But you haven't fixed it in this version, and the title of the issue is exactly why search results end up here.

You HAVE fixed it in V12 - but the title for this issue does not say V12, and it's the title that the search engines will index.

So No I disagree with you... this particular is not fixed, and so "Close as NOT Fixed" is appropriate.

**Comment by JPVenson** [comment]
dude that is not how this works. This is fixed in code that is what this ticket is about.

also the title says 10.11.0 and we cannot technomagically fix an version from a year ago.

**Comment by shawty** [comment]
I'm not asking you to fix a version from a year ago, your really not getting what I'm saying here.

When you search in the search engines for help on this issue and esp if you include the version number, this issue is the first one that pops up.  Now I know the story behind it, I have been following what's been happening, and I know V12 is out there.

That would be perfectly fine, and the end of it all.... IF this was something that only technically inclined folks used....

But it's NOT.... it's an app used by everyone from little old grandmas to rocket scientists, and I can guarantee you right now your average joe on the street who just want's to watch his movies again, is going to do exactly:

Search Error
Find This Thread
Scroll directly to the bottom to see if there is a fix
See the message saying it's fixed
Open a new thread telling you it's not fixed and ask for help

So, the correct thing to do is to close the issue with something like:

"Closed, will not fix in V10.11.0, you will need to upgrade to V12 to fix"

**Comment by n-peugnet** [comment]
> also the title says 10.11.0 and we cannot technomagically fix an version from a year ago.

Of course 10.11.**0** cannot be fixed but the 10.11.x branch can.
This issue is one of the reason we are still blocked on 10.10.x, and I really don't understand how [this simple patch](https://github.com/jellyfin/jellyfin-web/pull/7520.patch) cannot be backported to 10.11.x:

```diff
diff --git a/src/scripts/browserDeviceProfile.js b/src/scripts/browserDeviceProfile.js
index 1b63b4a03a11..abff2b5846cf 100644
--- a/src/scripts/browserDeviceProfile.js
+++ b/src/scripts/browserDeviceProfile.js
@@ -297,8 +297,22 @@ function supportedDolbyVisionProfileAv1(videoTestElement) {
 }
 
 function supportsAnamorphicVideo() {
-    // Tizen applies the aspect ratio correctly
-    return browser.tizenVersion >= 6;
+    // Most modern browsers/platforms correctly apply SAR (Sample Aspect Ratio) during playback,
+    // stretching non-square pixels to the correct display aspect ratio.
+    //
+    // Tizen 6+ confirmed working in commit 08f8b2d2f. WebOS 5+ is similar (2020+ LG TVs).
+    // Desktop browsers, Edge UWP (Xbox), and mobile platforms all handle anamorphic correctly.
+    //
+    // Platforms NOT included (need testing): vidaa, hisense, ps4, titanos, operaTv, vega
+    return browser.tizenVersion >= 6
+        || browser.web0sVersion >= 5
+        || browser.chrome
+        || browser.firefox
+        || browser.safari
+        || browser.edgeChromium
+        || browser.edgeUwp
+        || browser.iOS
+        || browser.android;
 }
 
 function getDirectPlayProfileForVideoContainer(container, videoAudioCodecs, videoTestElement, options) {
```

I mean, it simply changes a single line!
