### ISSUE TITLE
Direct play of local files returns HTTP 500 with Content-Length mismatch on 10.11.1; clients show PlaybackError.mediadecodeerror

### ISSUE THREAD

**Issue by 77x7** [jellyfin/jellyfin#15295]
### Description of the bug

Direct play of any local item fails immediately on Jellyfin 10.11.1. The server returns HTTP 500 and logs show System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (...) followed by System.ArgumentOutOfRangeException (Parameter 'count') in Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync. Clients display PlaybackError.mediadecodeerror. Switching the same titles to HLS/transcode succeeds. This began after updating to 10.11.1 and occurs on all my devices.

Example server errors while attempting direct play of /Videos/{ItemId}/stream(.mkv):

Response Content-Length mismatch: too few bytes written (25 of 457467263) then ArgumentOutOfRangeException (Parameter 'count') in SendFileFallback.SendFileAsync. 

### Reproduction steps

Run Jellyfin Server 10.11.1 on Windows 10.

In Jellyfin Media Player, start playback of any local video that should direct play.

Observe playback stops immediately with PlaybackError.mediadecodeerror.

Check server log for the Content-Length mismatch and SendFileFallback.SendFileAsync exceptions for the GET /Videos/{ItemId}/stream(.mkv) request.

### What is the current _bug_ behavior?

Direct play returns HTTP 500 and drops the connection.

Server logs show Content-Length mismatch and ArgumentOutOfRangeException inside SendFileFallback.SendFileAsync. 

Happens for every file tested, including small files around 45 MB.

Transcoding to HLS works and plays as expected (ffmpeg invoked, segments produced).

### What is the expected _correct_ behavior?

Direct play should stream the file successfully without server exceptions, with correct Content-Length handling and no client errors.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.11.1

### Environment

```markdown
OS: Windows 10.0.19045 x64.
Virtualization: none
Clients: Jellyfin Media Player 1.12.0 on Windows; also reproduced with an older JMP 1.11.1 on Windows.
Browser: N/A for direct play; Web client works when transcoding
FFmpeg Version: 7.1.2-Jellyfin.
Playback method: Direct Play fails; HLS/transcode succeeds
Hardware acceleration: available (CUDA etc.) for transcode; not used for direct play.
GPU model: RTX 3080
Installed plugins: Playback Reporting, Custom Tabs, Media Bar, File Transformation, Namo InPlayerEpisodePreview.
Reverse proxy: none (Kestrel listening on 0.0.0.0)
Base URL: none
Networking: host
Jellyfin data storage: local disk
Media storage: local disks (D:, E:)
External integrations: none relevant
```

### Jellyfin logs

```shell
Attached
```

### FFmpeg logs

```shell
also attached
```

### Relevant screenshots or videos

[log_20251029_redacted.log](https://github.com/user-attachments/files/23202372/log_20251029_redacted.log)

[FFmpeg.Transcode-2025-10-29_08-15-36_7ffa860f5c7d79656d9771e7a25c7155_c2406abd.log](https://github.com/user-attachments/files/23202377/FFmpeg.Transcode-2025-10-29_08-15-36_7ffa860f5c7d79656d9771e7a25c7155_c2406abd.log)

### Additional information

Began after updating to 10.11.1.

Reproduces with every local file tested, regardless of codec or size.

No reverse proxy.

Disabling custom CSS and removing plugins did not change behavior.

You guys have made an incredible piece of software, i really really appreciate al your work ❤️

**Comment by LeGmask** [comment]
I can confirm that I reproduce this issue

**Comment by pohuing** [comment]
This same issue also happens when using the webOS jellyfin client.

**Comment by n1coh** [comment]
A bit more straightforward :

`mpv http://192.168.1.10:8096/Items/67a8b49862c73bccf31cdd1e34894674/Download\?api_key\=xxx`

```jellyfin  | [09:36:55] [ERR] [30] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /Items/67a8b49862c73bccf31cdd1e34894674/Download.
jellyfin  | System.ArgumentOutOfRangeException:  (Parameter 'count')
jellyfin  | Actual value was 447062409.
jellyfin  |    at Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync(Stream destination, String filePath, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
jellyfin  |    at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin  |    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin  |    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin  |    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
jellyfin  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
jellyfin  |    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
jellyfin  | [09:36:55] [ERR] [30] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HNGNHBGDJ527", Request id "0HNGNHBGDJ527:00000001": An unhandled exception was thrown by the application.
jellyfin  | System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (25 of 447062409).```

**Comment by Shadowghost** [comment]
Should be fixed by #15263

**Comment by northernpowerhouse** [comment]
> Should be fixed by [#15263](https://github.com/jellyfin/jellyfin/pull/15263)

@Shadowghost unfourtunately not, this is on jellfin 10.11.2

`[2025-11-03 14:24:09.490 +01:00] [INF] Running query planner optimizations in the database... This might take a while
[2025-11-03 14:24:09.507 +01:00] [INF] Stopping directory watching for path "/mnt/symlib/tv"
[2025-11-03 14:24:09.508 +01:00] [INF] Stopping directory watching for path "/store/tv"
[2025-11-03 14:24:09.510 +01:00] [INF] Disposing "CoreAppHost"
[2025-11-03 14:24:09.510 +01:00] [INF] Disposing "MusicBrainzArtistProvider"
[2025-11-03 14:24:09.510 +01:00] [INF] Disposing "MusicBrainzAlbumProvider"
[2025-11-03 14:24:09.511 +01:00] [INF] Disposing "KodiSyncQueuePlugin"
[2025-11-03 14:24:09.513 +01:00] [INF] Disposing "PluginManager"
[2025-11-03 14:24:09.521 +01:00] [INF] Kestrel is listening on "0.0.0.0"
[2025-11-03 14:24:09.523 +01:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2025-11-03 14:24:09.524 +01:00] [INF] Loading assemblies
[2025-11-03 14:24:09.525 +01:00] [INF] Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Kodi Sync Queue_15.0.0.0/Jellyfin.Plugin.KodiSyncQueue.dll"
[2025-11-03 14:24:09.528 +01:00] [INF] Loaded assembly "LiteDB, Version=5.0.15.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27" from "/var/lib/jellyfin/plugins/Kodi Sync Queue_15.0.0.0/LiteDB.dll"
[2025-11-03 14:24:09.535 +01:00] [INF] Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2025-11-03 14:24:09.535 +01:00] [INF] Defined LAN exclusions: []
[2025-11-03 14:24:09.535 +01:00] [INF] Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2025-11-03 14:24:09.535 +01:00] [INF] Filtered interface addresses: ["127.0.0.1", "192.168.1.180", "172.17.0.1", "172.18.0.1", "172.19.0.1", "172.20.0.1"]
[2025-11-03 14:24:09.535 +01:00] [INF] Bind Addresses ["0.0.0.0"]
[2025-11-03 14:24:09.535 +01:00] [INF] Remote IP filter is "Allowlist"
[2025-11-03 14:24:09.535 +01:00] [INF] Filtered subnets: []
[2025-11-03 14:24:09.540 +01:00] [INF] SQLite connection string: "Data Source=/var/lib/jellyfin/data/jellyfin.db;Cache=Default;Pooling=True"
[2025-11-03 14:24:09.540 +01:00] [INF] SQLITE connection pragma command set to: 
"PRAGMA locking_mode=NORMAL;
PRAGMA journal_size_limit=134217728;
PRAGMA synchronous=1;
PRAGMA temp_store=2;
"
[2025-11-03 14:24:09.540 +01:00] [INF] The database locking mode has been set to: NoLock.
[2025-11-03 14:24:09.541 +01:00] [INF] Prepare system for possible migrations
[2025-11-03 14:24:09.551 +01:00] [INF] There are 0 migrations for stage CoreInitialisation.
[2025-11-03 14:24:09.565 +01:00] [INF] KodiSyncQueue is starting...
[2025-11-03 14:24:09.565 +01:00] [INF] Creating DB Repository...
[2025-11-03 14:24:09.591 +01:00] [INF] Loaded plugin: "Kodi Sync Queue" "15.0.0.0"
[2025-11-03 14:24:09.592 +01:00] [INF] Loaded plugin: "TMDb" "10.11.2.0"
[2025-11-03 14:24:09.592 +01:00] [INF] Loaded plugin: "Studio Images" "10.11.2.0"
[2025-11-03 14:24:09.592 +01:00] [INF] Loaded plugin: "OMDb" "10.11.2.0"
[2025-11-03 14:24:09.593 +01:00] [INF] Loaded plugin: "MusicBrainz" "10.11.2.0"
[2025-11-03 14:24:09.593 +01:00] [INF] Loaded plugin: "AudioDB" "10.11.2.0"
[2025-11-03 14:24:09.621 +01:00] [INF] There are 0 migrations for stage AppInitialisation.
[2025-11-03 14:24:09.625 +01:00] [INF] Kestrel is listening on "0.0.0.0"
[2025-11-03 14:24:09.753 +01:00] [WRN] The WebRootPath was not found: "/var/lib/jellyfin/wwwroot". Static files may be unavailable.
[2025-11-03 14:24:09.760 +01:00] [INF] Running startup tasks
[2025-11-03 14:24:09.761 +01:00] [INF] Retention task scheduled
[2025-11-03 14:24:09.761 +01:00] [INF] Watching directory "/store/tv"
[2025-11-03 14:24:09.763 +01:00] [INF] Watching directory "/mnt/symlib/tv"
[2025-11-03 14:24:09.765 +01:00] [INF] Daily trigger for "Remove Old Sync Data" set to fire at 2025-11-04 00:01:00.000 +01:00, which is 09:36:50.2342726 from now.
[2025-11-03 14:24:09.766 +01:00] [INF] Daily trigger for "Generate Trickplay Images" set to fire at 2025-11-04 03:00:00.000 +01:00, which is 12:35:50.2339914 from now.
[2025-11-03 14:24:09.766 +01:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 2025-11-04 02:00:00.000 +01:00, which is 11:35:50.2336287 from now.
[2025-11-03 14:24:09.779 +01:00] [INF] Found ffmpeg version "7.1.2"
[2025-11-03 14:24:09.793 +01:00] [INF] Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "ac4", "dca", "flac", "mp3", "truehd"]
[2025-11-03 14:24:09.807 +01:00] [INF] Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2025-11-03 14:24:09.823 +01:00] [INF] Available filters: ["bwdif_cuda", "bwdif_opencl", "deinterlace_qsv", "deinterlace_vaapi", "flip_vulkan", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemapx", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "transpose_cuda", "transpose_opencl", "transpose_vaapi", "transpose_vulkan", "vpp_qsv", "yadif_cuda", "yadif_opencl", "zscale", "alphasrc"]
[2025-11-03 14:24:10.002 +01:00] [INF] Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2025-11-03 14:24:12.767 +01:00] [INF] "Clean Transcode Directory" Completed after 0 minute(s) and 0 seconds
[2025-11-03 14:24:12.789 +01:00] [INF] "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2025-11-03 14:24:12.871 +01:00] [INF] FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2025-11-03 14:24:12.871 +01:00] [INF] ServerId: "6cb83c03b887445ea2fc5565a7e30d55"
[2025-11-03 14:24:12.871 +01:00] [INF] Core startup complete
[2025-11-03 14:24:12.871 +01:00] [INF] Startup complete 0:00:03.3579661
[2025-11-03 14:24:14.198 +01:00] [INF] "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2025-11-03 14:24:22.207 +01:00] [INF] User policy for "joe". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2025-11-03 14:24:22.606 +01:00] [ERR] Error processing request. URL "GET" "/Videos/1c697910ba7c315654f75ae58251f480/stream".
System.ArgumentOutOfRangeException:  (Parameter 'count')
Actual value was 724877578.
   at Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync(Stream destination, String filePath, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2025-11-03 14:24:22.607 +01:00] [ERR] Connection id ""0HNGQR8TQK3GF"", Request id ""0HNGQR8TQK3GF:00000001"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (25 of 724877578).
[2025-11-03 14:24:31.317 +01:00] [INF] WS "192.168.1.53" request
[2025-11-03 14:24:33.201 +01:00] [INF] Plugin Settings Requested...
[2025-11-03 14:24:33.267 +01:00] [INF] Sync Requested for UserID: '"6bea8e4960bc4c2585035eb3ae65f114"' with LastUpdateDT: '"2025-11-02T22:55:59Z"'
[2025-11-03 14:24:33.347 +01:00] [INF] Added: 0, Removed: 0, Updated: 0, Changed User Data: 0
[2025-11-03 14:24:33.347 +01:00] [INF] Request Finished Taking "00:00:00.0774780"
[2025-11-03 14:25:19.320 +01:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2025-11-03 14:25:31.319 +01:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2025-11-03 14:25:43.319 +01:00] [INF] Lost 1 WebSockets.
[2025-11-03 14:25:45.151 +01:00] [INF] WS "192.168.1.72" request
[2025-11-03 14:25:49.958 +01:00] [INF] User policy for "joe". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2025-11-03 14:25:50.358 +01:00] [ERR] Error processing request. URL "GET" "/Videos/1c697910ba7c315654f75ae58251f480/stream".
System.ArgumentOutOfRangeException:  (Parameter 'count')
Actual value was 724877578.
   at Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync(Stream destination, String filePath, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2025-11-03 14:25:50.359 +01:00] [ERR] Connection id ""0HNGQR8TQK3GU"", Request id ""0HNGQR8TQK3GU:00000001"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (25 of 724877578).`

**Comment by f1nlay** [comment]
Also still seeing this on 10.11.2 - seems to be related to #15279 in my case as my library uses symlinks. Is it worth closing this as a dupe of #15279 - is everyone else with this issue also using symlinked files within their library?

**Comment by northernpowerhouse** [comment]
>  is everyone else with this issue also using symlinked files within their library?
 I am, yes, but the linked issue also mentions not finding symlinked files in library scans, and I'm not having that problem.

**Comment by xwy2756** [comment]
Yes, I also used symbolic links on Windows to organize my media library. The same issue occurs when using URLs to play the media in external players. Using the built-in player is fine. Here is the log:

025-11-04 18:16:54.844 +08:00] [ERR] [29] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Items/8be902717a0b03698534118e6866aa7e/Download".
System.ArgumentOutOfRangeException:  (Parameter 'offset')
Actual value was 44982306.
   at Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync(Stream destination, String filePath, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2025-11-04 18:16:54.853 +08:00] [ERR] [29] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HNGRB475QLO6"", Request id ""0HNGRB475QLO6:00000001"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (25 of 269819).

**Comment by agrif** [comment]
I'm also seeing this problem with symlinked media on Linux. I do not have the problem with library scans, just playback.

**Comment by Shadowghost** [comment]
#15263 was not merged into 10.11.2, it should fix this issue.

**Comment by ivanjx** [comment]
i think this issue is related to the other issue i mentioned in the pr so im tagging this issue as well

**Comment by theguymadmax** [comment]
This issue may be fixed in 10.11.5. Please confirm.

**Comment by Issam2204** [comment]
I still have the issue but not with all media files.

`[22:55:11] [INF] [9] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for issam. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[22:55:11] [INF] [9] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[22:55:11] [INF] [9] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:"/media/tv/Example/Season 1/Example - S01E01 - WEBDL-2160p.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "122342098fce9820d2dbfdc76c5e67d9-1.mp4" -start_number 0 -hls_segment_filename "/cache/transcodes/122342098fce9820d2dbfdc76c5e67d9%d.mp4" -hls_playlist_type vod -hls_list_size 0 -hls_segment_options movflags=+frag_discont -y "/cache/transcodes/122342098fce9820d2dbfdc76c5e67d9.m3u8"
[22:55:12] [INF] [15] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /cache/transcodes/122342098fce9820d2dbfdc76c5e67d9.m3u8
[22:55:12] [INF] [15] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[22:55:12] [INF] [15] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[22:55:12] [INF] [15] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -ss 00:02:24.644 -noaccurate_seek -fflags +genpts -f matroska  -i file:"/media/tv/Example/Season 1/Example - S01E01 - WEBDL-2160p.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "122342098fce9820d2dbfdc76c5e67d9-1.mp4" -start_number 24 -hls_segment_filename "/cache/transcodes/122342098fce9820d2dbfdc76c5e67d9%d.mp4" -hls_playlist_type vod -hls_list_size 0 -hls_segment_options movflags=+frag_discont -y "/cache/transcodes/122342098fce9820d2dbfdc76c5e67d9.m3u8"
[22:55:12] [ERR] [19] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HNI3VR9UP6N8", Request id "0HNI3VR9UP6N8:0000000E": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (10640472 of 10648152).`

**Comment by mythbuster74** [comment]
> This issue may be fixed in 10.11.5. Please confirm.

Still present in 10.11.5 for me

**Comment by marcosmurakami** [comment]
I have the same problem on 10.11.3, with multiple files. I noticed that this issue started occurring on a user who is far away, outside my home network. Then I limited his throughput on the users' "Internet streaming bitrate limit (Mbps)". I will do some tests.
Also, when this error happens, my zpool gets degraded. scrubbing, and getting it clean, the zpool gets back online with no issues. But I am wondering if this keeps happening, it might corrupt my data.

**Comment by marcosmurakami** [comment]
> I have the same problem on 10.11.3, with multiple files. I noticed that this issue started occurring on a user who is far away, outside my home network. Then I limited his throughput on the users' "Internet streaming bitrate limit (Mbps)". I will do some tests. Also, when this error happens, my zpool gets degraded. scrubbing, and getting it clean, the zpool gets back online with no issues. But I am wondering if this keeps happening, it might corrupt my data.

Just an update about this. I had changed the "Internet streaming bitrate limit (Mbps)" to 10Mbps for each external user and set to 100Mbps to internal users(home network like tvs, ipads, etc), and I have not had this problem again so far.
