### ISSUE TITLE
Default subtitles - Portuguese language

### ISSUE THREAD

**Issue by maghuro** [jellyfin/jellyfin#15642]
### Description of the bug

Latest version of Jellyfin Server - 10.11.3

On used profile, subtitles, right now we have 3 Portuguese subtitles options - Portuguese (which selects country variant which is found first), Portuguese (Portugal) and Portuguese (Brazil).
When selecting variant Portugal or Brazil and saving, the config doesn't stick and it saves the Portuguese (default, no country variant) version.

It should stick with country variant.

### Reproduction steps

1 - go to profile, subtitles
2 - chose Portuguese country variant (Portugal or Brazil)
3 - save
4 - it doesn't stick, and defaults to Portuguese (generic).

### What is the current _bug_ behavior?

It doesn't stick with country Portuguese variant.

### What is the expected _correct_ behavior?

It should stick with country variant.

### Jellyfin Server version

10.11.3

### Specify the build version

10.11.3

### Environment

```markdown
Not related.
```

### Jellyfin logs

```shell
[2025-11-27 00:00:00.142 +00:00] [INF] [21] Jellyfin.Plugin.PlaybackReporting.TaskCleanDb: Playback Reporting Data Trim
[2025-11-27 00:00:00.179 +00:00] [INF] [21] Jellyfin.Plugin.PlaybackReporting.TaskCleanDb: MaxDataAge : 3
[2025-11-27 00:00:00.185 +00:00] [INF] [21] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: DeleteOldData : "delete from PlaybackActivity where DateCreated < '2025-08-27 00:00:00.1800827'"
[2025-11-27 00:00:00.275 +00:00] [INF] [21] Jellyfin.Plugin.PlaybackReporting.Data.ActivityRepository: Default journal_mode for "/config/data/playback_reporting.db" is "delete"
[2025-11-27 00:00:00.286 +00:00] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Playback Reporting Trim Db" Completed after 0 minute(s) and 0 seconds
[2025-11-27 00:00:01.123 +00:00] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Playback Reporting Trim Db" set to fire at 2025-11-28 00:00:00.000 +00:00, which is 23:59:58.8770012 from now.
[2025-11-27 01:32:19.033 +00:00] [INF] [46] Emby.Server.Implementations.IO.LibraryMonitor: "Stranger Things" ("/media/Séries/Stranger.Things") will be refreshed.
[2025-11-27 01:32:22.267 +00:00] [INF] [22] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Temporada Desconhecida" entry for "Stranger Things"
[2025-11-27 01:32:32.084 +00:00] [ERR] [54] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetLanguage(String language, String mediaPath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2025-11-27 01:32:38.844 +00:00] [ERR] [3] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetLanguage(String language, String mediaPath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2025-11-27 01:32:40.499 +00:00] [INF] [30] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Stranger Things"
[2025-11-27 01:32:40.537 +00:00] [INF] [30] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Temporada Desconhecida", Path: "", Id: fe6470c6-40fd-41d3-17dd-360a848069c5
[2025-11-27 01:32:41.527 +00:00] [INF] [30] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Temporada 5" entry for "Stranger Things"
[2025-11-27 01:38:47.774 +00:00] [INF] [45] Emby.Server.Implementations.IO.LibraryMonitor: "Stranger Things" ("/media/Séries/Stranger.Things") will be refreshed.
[2025-11-27 01:38:49.634 +00:00] [INF] [16] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Temporada Desconhecida" entry for "Stranger Things"
[2025-11-27 01:38:54.050 +00:00] [ERR] [45] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetLanguage(String language, String mediaPath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2025-11-27 01:38:58.531 +00:00] [INF] [45] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Stranger Things"
[2025-11-27 01:38:58.534 +00:00] [INF] [45] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Temporada Desconhecida", Path: "", Id: fe6470c6-40fd-41d3-17dd-360a848069c5
[2025-11-27 01:47:23.206 +00:00] [INF] [64] Emby.Server.Implementations.IO.LibraryMonitor: "Stranger Things" ("/media/Séries/Stranger.Things") will be refreshed.
[2025-11-27 01:47:24.921 +00:00] [INF] [16] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Temporada Desconhecida" entry for "Stranger Things"
[2025-11-27 01:47:27.755 +00:00] [ERR] [38] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetLanguage(String language, String mediaPath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2025-11-27 01:47:32.353 +00:00] [INF] [38] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Stranger Things"
[2025-11-27 01:47:32.360 +00:00] [INF] [38] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Temporada Desconhecida", Path: "", Id: fe6470c6-40fd-41d3-17dd-360a848069c5
[2025-11-27 01:51:52.911 +00:00] [INF] [45] Emby.Server.Implementations.IO.LibraryMonitor: "Stranger Things" ("/media/Séries/Stranger.Things") will be refreshed.
[2025-11-27 01:51:54.182 +00:00] [INF] [22] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Temporada Desconhecida" entry for "Stranger Things"
[2025-11-27 01:51:57.701 +00:00] [ERR] [20] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetLanguage(String language, String mediaPath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2025-11-27 01:51:59.453 +00:00] [INF] [57] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Stranger Things"
[2025-11-27 01:51:59.454 +00:00] [INF] [57] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Temporada Desconhecida", Path: "", Id: fe6470c6-40fd-41d3-17dd-360a848069c5
[2025-11-27 01:59:48.552 +00:00] [INF] [57] Emby.Server.Implementations.IO.LibraryMonitor: "Stranger Things" ("/media/Séries/Stranger.Things") will be refreshed.
[2025-11-27 01:59:49.708 +00:00] [INF] [16] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Temporada Desconhecida" entry for "Stranger Things"
[2025-11-27 01:59:52.520 +00:00] [ERR] [64] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetLanguage(String language, String mediaPath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2025-11-27 01:59:54.743 +00:00] [INF] [64] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Stranger Things"
[2025-11-27 01:59:54.744 +00:00] [INF] [64] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Temporada Desconhecida", Path: "", Id: fe6470c6-40fd-41d3-17dd-360a848069c5
[2025-11-27 02:00:01.008 +00:00] [INF] [41] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extrair Imagens dos Capítulos" set to fire at 2025-11-28 02:00:00.000 +00:00, which is 23:59:58.9934706 from now.
[2025-11-27 02:00:06.069 +00:00] [INF] [45] Emby.Server.Implementations.Chapters.ChapterManager: Skipping chapter image extraction for "PSArips.com | Twisted.Metal.S02E09.1080p.10bit.WEBRip.6CH.x265.HEVC-PSA" as the average chapter duration 0 was lower than the minimum threshold 10000000
[2025-11-27 02:00:07.876 +00:00] [INF] [45] Emby.Server.Implementations.Chapters.ChapterManager: Skipping chapter image extraction for "À Procura de Dory" as the average chapter duration 0 was lower than the minimum threshold 10000000
[2025-11-27 02:00:08.086 +00:00] [INF] [45] Emby.Server.Implementations.Chapters.ChapterManager: Skipping chapter image extraction for "Monstros e Companhia" as the average chapter duration 0 was lower than the minimum threshold 10000000
[2025-11-27 02:00:08.093 +00:00] [INF] [45] Emby.Server.Implementations.Chapters.ChapterManager: Skipping chapter image extraction for "Monstros: A Universidade" as the average chapter duration 0 was lower than the minimum threshold 10000000
[2025-11-27 02:00:08.123 +00:00] [INF] [45] Emby.Server.Implementations.Chapters.ChapterManager: Skipping chapter image extraction for "O Corcunda de Notre Dame" as the average chapter duration 0 was lower than the minimum threshold 10000000
[2025-11-27 02:00:08.166 +00:00] [INF] [45] Emby.Server.Implementations.Chapters.ChapterManager: Skipping chapter image extraction for "Pinóquio" as the average chapter duration 0 was lower than the minimum threshold 10000000
[2025-11-27 02:00:08.230 +00:00] [INF] [45] Emby.Server.Implementations.Chapters.ChapterManager: Skipping chapter image extraction for "Sonhos e Comboios" as the average chapter duration 0 was lower than the minimum threshold 10000000
[2025-11-27 02:00:08.275 +00:00] [INF] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Extrair Imagens dos Capítulos" Completed after 0 minute(s) and 8 seconds
[2025-11-27 03:00:01.172 +00:00] [INF] [53] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Gerar imagens de truques" set to fire at 2025-11-28 03:00:00.000 +00:00, which is 23:59:58.9276617 from now.
[2025-11-27 03:00:16.522 +00:00] [INF] [35] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Gerar imagens de truques" Completed after 0 minute(s) and 16 seconds
[2025-11-27 03:27:01.130 +00:00] [INF] [18] Emby.Server.Implementations.IO.LibraryMonitor: "Stranger Things" ("/media/Séries/Stranger.Things") will be refreshed.
[2025-11-27 03:27:06.039 +00:00] [INF] [24] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "Episódio 4", Path: "/media/Séries/Stranger.Things/Stranger.Things.S05E04.Chapter.Four.Sorcerer.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv", Id: 5a0d81dc-12df-a315-7df6-1d41660ded74
[2025-11-27 03:28:47.717 +00:00] [INF] [33] Emby.Server.Implementations.IO.LibraryMonitor: "Stranger Things" ("/media/Séries/Stranger.Things") will be refreshed.
[2025-11-27 03:28:47.973 +00:00] [INF] [38] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "Episódio 4", Path: "/media/Séries/Stranger.Things/Stranger.Things.S05E04.Chapter.Four.Sorcerer.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264-Kitsune.mkv", Id: cae017c0-0c6c-b372-1317-fc5fe0fe759d
[2025-11-27 03:55:38.351 +00:00] [INF] [46] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "mrasquinho". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2025-11-27 03:55:39.429 +00:00] [INF] [57] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8
[2025-11-27 03:55:39.551 +00:00] [INF] [57] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 11/27/2025 03:55:39
[2025-11-27 03:55:39.553 +00:00] [INF] [57] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2025-11-27 03:55:39.554 +00:00] [INF] [57] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2025-11-27 03:55:39.665 +00:00] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:55:59.553 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : "10.0.0.230"
[2025-11-27 03:55:59.634 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = "24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:55:59.634 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = "cd4f4a7ac5564937a98c30f301ede5ba"
[2025-11-27 03:55:59.635 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 1
[2025-11-27 03:55:59.636 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = "24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:55:59.636 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = "cd4f4a7ac5564937a98c30f301ede5ba"
[2025-11-27 03:55:59.637 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = "DirectPlay"
[2025-11-27 03:55:59.638 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = "Jellyfin Android"
[2025-11-27 03:55:59.638 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = "Xiaomi 14T Pro"
[2025-11-27 03:55:59.639 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = "Stranger Things - s05e01 - Episódio 1"
[2025-11-27 03:55:59.640 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = "24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:55:59.640 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = "Episode"
[2025-11-27 03:55:59.641 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : All matches, playback registered
[2025-11-27 03:55:59.642 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback tracker found, adding playback info : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:55:59.643 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[2025-11-27 03:55:59.784 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[2025-11-27 03:56:00.424 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:56:20.502 +00:00] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:56:41.392 +00:00] [INF] [30] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:57:02.292 +00:00] [INF] [30] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:57:22.302 +00:00] [INF] [61] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:57:42.674 +00:00] [INF] [47] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:58:02.782 +00:00] [INF] [61] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:58:23.744 +00:00] [INF] [47] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:58:43.991 +00:00] [INF] [47] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:59:04.975 +00:00] [INF] [9] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:59:25.572 +00:00] [INF] [9] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 03:59:46.272 +00:00] [INF] [9] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 04:00:06.674 +00:00] [INF] [61] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 04:00:27.407 +00:00] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 04:00:47.434 +00:00] [INF] [15] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 04:01:07.725 +00:00] [INF] [61] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-11-27 04:01:28.490 +00:00] [INF] [9] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "e4751c9aa6928b2bcd4f4a7ac5564937a98c30f301ede5ba-cd4f4a7ac5564937a98c30f301ede5ba-24b7a79949104904d6c663f8c87de8d8"
[2025-
```

### FFmpeg logs

```shell

```

**Comment by crobibero** [comment]
Same issue as https://github.com/jellyfin/jellyfin/issues/15106
A fix has been merged for 10.11.4

**Comment by maghuro** [comment]
Not the same bug as that.
That one is for searching for subtitles, the one I opened is about choosing default language, not downloading it.

**Comment by crobibero** [comment]
It is a symptom of the same bug.

**Comment by JamesHolson** [comment]
Are there any news on this? The problem still persists in version 10.12.0, the country variant in the "Preferred subtitle language" setting doesn't stick when saving and reverts to plain "Portuguese".
