### ISSUE TITLE
User logins are being corrupted intermittently

### ISSUE THREAD

**Issue by admitguy** [jellyfin/jellyfin#15714]
### Description of the bug

On version 10.11.3 and 10.11.4, I’ve noticed multiple users on my server being unable to logon with their credentials intermittently. This happens across all connected apps as well (e.g. jellyseerr). I was baffled for a while, and determined if I log in as an admin and update any setting on the user (library access, permissions, etc.) the issue resolves itself. I have also verified it’s not a password issue, because I have been able to regain access for an account without modifying the password at all. The bigger issue is i’ve been locked out of my admin account twice and was almost unable to recover. 

I’m running Jellyfin via docker container and restarting the container didn’t help at all.

### Reproduction steps

1. Attempt to log into jellyfin
2. you will see a “Unable to connect to server” error message.
3. log in as an admin and view the user account to verify it exists

### What is the current _bug_ behavior?

Unable to login with correct credentials

### What is the expected _correct_ behavior?

Login works.

### Jellyfin Server version

10.11.3

### Specify the build version

10.11.4

### Environment

```markdown
- OS:Unraid
- Linux Kernel:
- Virtualization: Docker
- Clients:
- Browser: Safari, Firefox, chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Nginx Proxy manager
- Base URL:
- Networking: bridge
- Jellyfin Data Storage:
- Media Storage:
- External Integrations: Jellystat, Jellyseerr, Jellysweep, jellyplex-watched
```

### Jellyfin logs

```shell
logs are not loading at the moment… will try to update the ticket once I get them
```

### FFmpeg logs

```shell

```

**Comment by Raul824** [comment]
Would like to add more details and logs to this same error, I have been observing.
I think some cleanup task is corrupting the user instead of cleaning up the old sessions its corrupting the user.
Below are the sequence of events.

1. User got corrupted.
2. Try forgot password doesn't work.
3. Try reset password which also doesn't work.
4. Try taking a backup and the new backup doesn't contain the user which got corrupted.
5. Change any setting in the user like allow media download and save changes.
6. Now able to login as user.
7. Even forgot password works.



Below are the logs when tried step 2 and 3.

```[10:43:08] [ERR] [42] Jellyfin.Database.Implementations.JellyfinDbContext: Error trying to save changes.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Jellyfin.Database.Implementations.JellyfinDbContext.<>c__DisplayClass62_0.<<SaveChangesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Jellyfin.Database.Implementations.Locking.NoLockBehavior.OnSaveChangesAsync(JellyfinDbContext context, Func`1 saveChanges)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
[10:43:08] [ERR] [42] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Users/ForgotPassword.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Jellyfin.Database.Implementations.JellyfinDbContext.<>c__DisplayClass62_0.<<SaveChangesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Jellyfin.Database.Implementations.Locking.NoLockBehavior.OnSaveChangesAsync(JellyfinDbContext context, Func`1 saveChanges)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Jellyfin.Server.Implementations.Users.UserManager.UpdateUserInternalAsync(JellyfinDbContext dbContext, User user)
   at Jellyfin.Server.Implementations.Users.UserManager.UpdateUserAsync(User user)
   at Jellyfin.Server.Implementations.Users.UserManager.UpdateUserAsync(User user)
   at Jellyfin.Server.Implementations.Users.UserManager.StartForgotPasswordProcess(String enteredUsername, Boolean isInNetwork)
   at Jellyfin.Api.Controllers.UserController.ForgotPassword(ForgotPasswordDto forgotPasswordRequest)
   at lambda_method149078(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by hal-shin** [comment]
I also get this issue, it's happened thrice so far. Debugging with AI, I've narrowed it down to bad database state. Running the following fixes the problem for me:

```
sudo systemctl stop jellyfin
sudo rm -f /var/lib/jellyfin/data/jellyfin.db-wal /var/lib/jellyfin/data/jellyfin.db-shm
sudo sqlite3 /var/lib/jellyfin/data/jellyfin.db "PRAGMA quick_check;"
sudo systemctl start jellyfin
```

For whatever reason, it appears that the write-ahead logs and the shared memory file seems to get corrupted.

**Comment by theguymadmax** [comment]
We are aware of the but problem, but haven't tracked down the cause. This closed thread https://github.com/jellyfin/jellyfin/issues/14367 also had some discussion. Restarting Jellyfin usually solves the issue.

**Comment by fubar-coder** [comment]
It still happens on 10.11.6

**Comment by d10sfan** [comment]
I'm seeing the same issue, logs are in the ticket here - https://github.com/jellyfin/jellyfin/issues/16304

**Comment by GAumala** [comment]
I found this exact same exception today on my logs. For days I couldn't login with my admin user.

I can confirm that simply restarting jellyfin fixes it 👍

**Comment by beankylla** [comment]
Same issue here.
restarting jellyfin fixes the issue but the recurrence is somewhat annoying.
It only affects login if I’m already logged in somewhere it continues working.
New logins are impossible either via separate app or web UI

**Comment by beankylla** [comment]
> I also get this issue, it's happened thrice so far. Debugging with AI, I've narrowed it down to bad database state. Running the following fixes the problem for me:
> 
> ```
> sudo systemctl stop jellyfin
> sudo rm -f /var/lib/jellyfin/data/jellyfin.db-wal /var/lib/jellyfin/data/jellyfin.db-shm
> sudo sqlite3 /var/lib/jellyfin/data/jellyfin.db "PRAGMA quick_check;"
> sudo systemctl start jellyfin
> ```
> 
> For whatever reason, it appears that the write-ahead logs and the shared memory file seems to get corrupted.

does this solve it permanently or does fix it until the next time?

**Comment by ketsapiwiq** [comment]
(just stating the obvious but if restarting the service fixes it anyway (or are some versions of this bug only fixed with removal of these 2 files no matter how many times you restart?), I guess there is no proof WAL or SHM are related to this (although credible, it could be hallucinated))

**Comment by fcassata** [comment]
This is something that happened once every few weeks, but in the last week or so, after updating to latest JF and Infuse, it happens multiple times a day, making JF unusable. I can restart JF when it happens, but my wife can't.

**Comment by ketsapiwiq** [comment]
@fcassata I may be wrong but if it's caused by a db corruption, maybe changing config for db locking to Pessimistic or Optimistic and/or disabling extensions could help: https://jellyfin.org/docs/general/administration/troubleshooting/#database-locked-errors

**Comment by fcassata** [comment]
> [@fcassata](https://github.com/fcassata) I may be wrong but if it's caused by a db corruption, maybe changing config for db locking to Pessimistic or Optimistic and/or disabling extensions could help: https://jellyfin.org/docs/general/administration/troubleshooting/#database-locked-errors

Thanks will try this. Just noticed the LXC clause at the bottom too, kinda wild that running it that way just won't work and won't be fixed. JF shouldn't need a full VM, and neither the unecessary in-between layer of Docker.

**Comment by joshuarmost** [comment]
I am still having this issue on 10.11.8. Has anyone found a lead for fixing this bug? Does the database edits fix the issue?

**Comment by mtgmarshall** [comment]
Also still having this issue, affects certain users from logging into connected seerr accounts

**Comment by Hoborific** [comment]
Also facing this on v10.11.8, restarting daily at this point to try and avoid.

**Comment by JasperTheCrow** [comment]
v10.11.8 - Just happened to me on one of my admin accounts. Really freaked me out at first, glad its a known issue. I got back in after changing failed login attempts from 3 to 10 (knowing now any account setting would of restored it)

**Comment by amarevite** [comment]
I just want to add my two cents that I was having this issue and it turned out to be an underlying hardware problem (shout out `smartctl -x` for helping me confirm that). Even reading the database file would throw an I/O error. I was able to use `ddrescue` to recover the majority of the jellyfin.db file, then use [sqlite's built in .recover option](https://sqlite.org/recovery.html#recovery_using_the_recover_command_in_the_cli) to rebuild the database. I have everything copied over to a new drive and as far as I can tell it's all working great. quick_check and integrity_check both return "ok". Just wanted to put this here in case someone in the future runs into this problem.

*Editing this message as a reply so I don't clutter the actual discussion:*
@fubar-coder I'm aware, I just wanted to mention my situation since I had very similar symptoms and thought it was this bug at first. It was moreso for a hypothetical person like myself coming across this issue who might not realize they have a hardware issue (and not actually this bug).

**Comment by fubar-coder** [comment]
@amarevite I assume that this might not be related for the following reasons:

- It happens to a lot of people using Jellyfin and it's not reasonable to assume that all those people suddenly have a hardware failure
- It only happens since the EF Core migration
- The problem is gone after a restart of the Jellyfin instance (no PC restart, file system check/recovery or SQLite database recovery required)
- Everything else seems unaffected
- The problem is not an I/O error, but a concurrency error

**Comment by FarawayMagnet** [comment]
other than restarting daily, has anybody found a reliable way to mitigate this issue proactively? it's become quite frustrating to deal with reactively.

**Comment by kiwichick888** [comment]
> Restarting Jellyfin usually solves the issue.

I'm seeing this in v10.11.8 and, previously, on 10.11.6. It stopped for a couple of months but started again yesterday. It's happening for other users but also for me and I'm the admin. Logging in using username triggers the error but using Quick Connect works fine. Restarting JF does fix it but only for the next log in - logging out and back in after that triggers the error again.

**Comment by JPVenson** [comment]
fixed by https://github.com/jellyfin/jellyfin/pull/15368
