### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by DarkVirtue** [jellyfin/jellyfin#1858]
**Describe the bug**
When attempting to log in via the web interface, the page displays a "Connection Failure" message. The Kodi plugin receives a 500 error when it tries to log in.

**To Reproduce**
1. Go to the Jellyfin server's web page.
2. Enter valid credentials.
3. Click "Sign in"

**Expected behavior**
Successful login.

**Logs**
```
[2019-10-07 19:10:50.278 -04:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Common.Cryptography.PasswordHash.Parse(String storageString)
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Debian 10 (Server), Kubuntu 19.04 (Client)
 - Browser: Firefox 69.0.1
 - Jellyfin Version: 10.4.0.0
 - Reverse proxy: HAProxy 1.8.19

**Comment by DarkVirtue** [comment]
Found the issue:
While editing my profile this morning right after upgrading to 10.4.0.0, I had inadvertently cleared my password.
Firefox auto-filled the "current password" field and left the new password fields open. I happened to hit the "save" button and unwittingly saved a blank password.
Some clearer error reporting or extra confirmation before changing a password (or maybe before setting a blank password) may be worth consideration.

**Comment by lord-carlos** [comment]
I also just updated my jellyfin docker and can't login. While the UI also says connection error I get a slight different error on the server side:
```
System.ArgumentException: String doesn't contain enough segments
Parameter name: storageString
   at MediaBrowser.Common.Cryptography.PasswordHash.Parse(String storageString)
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

Seems to be at the same class though.

**Comment by lord-carlos** [comment]
I downgraded and that worked. Then I upgraded again and was still authenticated. But when another user tried to login it did not work. Same error. String doesn't contain enough segments.

**Comment by iotku** [comment]
Similarly on the windows side of things I get this when attempting (and failing) to login

> [07:50:11] [ERR] Error processing request
System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 0.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerCycleDetected(Int32 maxDepth)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreBytes(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeToUtf8Bytes[TValue](TValue value, JsonSerializerOptions options)
   at Emby.Server.Implementations.Data.SqliteUserRepository.UpdateUser(User user)
   at Emby.Server.Implementations.Library.UserManager.UpdateUser(User user)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

When trying to login on https://github.com/jellyfin/jellyfin/commit/79f9887625bdc5ae5afead89387603023a34570e and above, has an issue for a while so I've been sticking on a nightly prior to that which logs in fine with the same credentials.

**Comment by anthonylavado** [comment]
@iotku I think that *just* got fixed.

**Comment by iotku** [comment]
@anthonylavado 

Still happening here on master jellyfin (e3f1f62a8bb5377c80e3c26331915db7e0fe2fa4) and master jellyfin-web (https://github.com/jellyfin/jellyfin-web/commit/21a794d845cac388c13b5526114bf8985e86abdf)

Error from last comment in console and

"Connection Failure: We're unable to connect to the selected server right now. Please ensure it is running and try again." on the login page

**Comment by nextlooper42** [comment]
So Jellyfin just locked me out after week of setting up clean installation and organizing with "Connection Failure" message on Stable 10.4. Any idea how to solve this?

**Comment by joshuaboniface** [comment]
So for anyone locked out, can you try this "fix": uninstall Jellyfin (but don't purge) and reinstall it. I have no idea why but this just fixed this issue for me and I'm at a total loss to explain why.

**Comment by PrplHaz4** [comment]
@joshuaboniface any idea if there is an equivalent fix for the docker container?  I can't seem to get this to clear in my test container (upgrade from 10.4.0 -> nightlies -> broken at some point -> 10.4.1 fixed -> nightlies broken)

Even copying in my "prod" config files/db, I still get the `object cycle` error with the nightlies...

**Comment by anthonylavado** [comment]
cc @Z3ROGRAV1TYx, I think this is the issue you're experiencing.

**Comment by lord-carlos** [comment]
My problem seems to have been fixed with 10.4.1 `String doesn't contain enough segments`
👍

**Comment by Z3ROGRAV1TYx** [comment]
> 

> So for anyone locked out, can you try this "fix": uninstall Jellyfin (but don't purge) and reinstall it. I have no idea why but this just fixed this issue for me and I'm at a total loss to explain why.

Am on 10.4.1, and yes I am having this same issue. I have just tried reinstalling Jellyfin and at first it didn't seem to work. But it seems to have reset all the passwords to blank, so all I had to do was not input anything into the password fields. (Note I already tried this before reinstall and it didn't work, so the reinstall did do this). I can now get into all the accounts. I tried logging out of them all and using their passwords. All seemed to work.

**BUT**, I currently cannot get the Easy Pin codes to work at all (Yes I am connected locally).
I tried resetting them a few times. They just say "Invalid username or password, please try again".

**Comment by anthonylavado** [comment]
@Z3ROGRAV1TYx Thanks

For those with a PIN: https://github.com/jellyfin/jellyfin/issues/1850

**Comment by gerroon** [comment]
Reinstalling does not fix for me. I have 10.4.1-1 "String doesn't contain enough segments" is still and issue for me.

**Comment by JustAMan** [comment]
Can we have this "not enough segments" be extracted to its own issue? Tracking two issues in one is counter-productive.

**Comment by BugFixesAndPerformanceImprovements** [comment]
I'm experiencing the same after having a clean install run for about two days, adding and scanning libraries. Had to restart the OS (Windows 7 SP1 x64) after which the "connection failure" message is displayed when trying to log in through the web GUI.

Uninstalled, kept data, reinstalled and still the same result.

Using version v10.4.3-x64

Error message in the log:
```
[2019-12-19 01:52:52.807 +02:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Common.Cryptography.PasswordHash.Parse(String storageString)
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by Z3ROGRAV1TYx** [comment]
Hmm I'm personally having no issues with pin login on 10.4.3

**Comment by rystaf** [comment]
Got the same error message. Assuming it happened after saving some changes to my profile and possibly inadvertently set my password blank like @DarkVirtue said. I was able to log in again after resetting my password.

**Comment by BugFixesAndPerformanceImprovements** [comment]
I've tried several times (with newly generated PINs) to reset the password, but nothing happens when clicking "submit" and the following error is shown in the log:

```
[2020-01-13 01:58:53.110 +02:00] [ERR] Error processing request
MediaBrowser.Common.Extensions.ResourceNotFoundException: No Users found with a password reset request matching pin DD-BA-49-E6
   at Emby.Server.Implementations.Library.DefaultPasswordResetProvider.RedeemPasswordResetPin(String pin)
   at Emby.Server.Implementations.Library.UserManager.RedeemPasswordResetPin(String pin)
   at MediaBrowser.Api.UserService.Post(ForgotPasswordPin request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by JustAMan** [comment]
@Bond-009 @dkanada @anthonylavado  does this ring a bell for you?

**Comment by christiansgesp** [comment]
I just had this problem (4th March 2020), I solved easily... just use your username as always but leave the password field blank and you'll be able to log in.

**Comment by JustAMan** [comment]
This is not how password reset was expected to work... it was expected to set password to the pin.
Good to know a workaround exists, though!

**Comment by BugFixesAndPerformanceImprovements** [comment]
After doing a clean installation with the latest version (10.5.0) and numerous restarts, I am no longer receiving this error.
