### ISSUE TITLE
Subtitles load after a while and can be out of sync when resuming

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#2547]
**Describe the bug**
When i watch anime on my phone the subtitles can take up to 30 seconds to appear, eventhough there should have been subtitles already.
when they appear they do show the correct text, but im just missing the first 30 seconds of the conversation.
When i skip through a video or resume, the timing of the subtitles is off, this can be a minor difference, but i also had a few times where it was 2 sentences off.
i have to quit and resume again to try and get the subtitles to line up correctly.
or i have to watch the video from the beginning, then the timing is always correct.(i just miss the first bit when i do that).
Also the issue is there that subtitles dont work at all when playing on the android app.

**System (please complete the following information):**
 - OS: Unraid (some linux version?)
 - Virtualization: Docker
 - Clients: Android and Chrome on Android
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.0
 - Playback: Any
 - Installed Plugins: Opensubtitles(these subs are not always from the plugin), Anime, Audio, MusicBrainz
 - Reverse Proxy: nginx-proxy-manager(docker container for nginx with a userfriendly UI)
 - Base URL: jellyfin.mydomain.com
 - Networking: Bridge
 - Storage: XFS

**To Reproduce**
just try to play a video on your (android)  phone and skip around to a different part of the video.
In the app you wont get subtitles, and on chrome the subtitles will be out of sync.
note: you can also see that the subs will take a while to load on chrome.

**Expected behavior**
The subtitles should have the correct timing.

hypothesis:
there are probably a seperate timer for the subtitles, that timer does not correspond the playback time of the video and gets out of sync when the video needs to buffer like when its skipped.
As for the delay, i think the video starts playing as soon as its buffered, but the subs have a lower priority and thus are only loaded after the video is buffered.

potential fixes, keep in mind that i didnt look at the code (yet) and thus might be totally wrong.
I will try to look into the code soon so i try can help out.

potential fix for the delay before subs appear:
load subtitles before the video, this means that the first transcoding process also can be done while the subtitles are being send, this way you dont have a performance difference.
what i think happens now:
1. Transcode video part.
2. send video part.
3. repeat step 1 and 2 untill the buffer is full enough to play the video
4. send subs
What i think would fix this problem:
1. Transcode video part.
2. (While transcoding) send subs (based on my idea that its the whole file being send)
3. send video part.
4. repeat step 1 and 3 untill the buffer is full enough to play the video

Potential fix for the unsynced subs:
What i think is happening now:
1. user skips
2. video stops
3. client requests different video parts
4. subtitles pause
5. client gets new video parts
6. subtitles timer is already wrong and somehow it can resume playback around the correct time but being slightly off.
what might fix this:
not using a different timer for the subs and using the timer that is already being used for showing current playback time(unless that is also out of sync).

**Comment by eltiel** [comment]
What's the format of the subs that you're having problems with?

**Comment by accountForIssues** [comment]
I'm pretty sure it's the same issue as my now [stale Issue](https://github.com/jellyfin/jellyfin-web/issues/560).

I didn't update it as I was able to direct play everything and this seems to have solved my original issue albeit with the new 10.5 update this [Issue](https://github.com/jellyfin/jellyfin/issues/2507) has come up.

@ikomhoog might be right that there might be two different timers working and since the video seeking doesn't sync exactly to the exact timestamp, the subs are out-of-sync at every resume/seek.

**Comment by ikomhoog** [comment]
the subtitles are either .srt or embedded in the MKV video file.
Both have the same problem.

**Comment by yocosweet** [comment]
the same problem…

**Comment by eltiel** [comment]
> the subtitles are either .srt or embedded in the MKV video file.
> Both have the same problem.

If it is SRT, it's very likely related to this issue: https://github.com/jellyfin/jellyfin/issues/2507. Try padding the sub file with 1024 chars to see if it works.

As for embedded subs, what format is it in? So far I did not encounter delayed embedded subs, but would be glad to test it out myself if you could point me to the source of your problematic media.

But I certainly can agree with you that subs can be out of sync especially after frequent skipping. I didn't raise an issue because I couldn't reliably reproduce the problem in a quantifiable manner.

**Comment by ikomhoog** [comment]
I cannot reproduce the problem on windows either, this is probably because of the higher internet speeds or maybe direct play.
on my phone i set the quality to 720P 4MB while the quality of the file is 1080P.
on my browser its always direct play 


this is the file that i can easily reproduce the errors with. just play the file  and you will see that it takes a long time for the subs to load.
try to skip a few times and you will see that the subtitles will be out of sync.
once you stop viewing in the middle of the video and resume it, you will see that the subtitles will also be out of sync.

Also while testing here just now while at work and using 4G Data speeds , the subtitles take ages to load, might be minutes before they show up.

Details:
File: https://www.ettv.to/torrent/763643/horriblesubs-infinite-dendrogram-01-1080p-mkv
i have this issue while using quicksync or nvenc, software decoding is to slow to be usable on my system.
CPU: 4820K
Threads: 1, this is more than enough for transcoding 1080P for PC
GPU: 1060 6G
RAM: 32GB, with usually 18GB available, this barely gets filled up by the jellyfin transcoding temp directory.
internet speeds: Gigabit connection to router with 250Mb/s down and 25Mb/s up.

**Comment by eltiel** [comment]
> this is the file that i can easily reproduce the errors with. just play the file and you will see that it takes a long time for the subs to load.

I tried the file you pointed out. When transcoding, there is no delay in subs. The first line is "Tokyo" at 7 secs. When DirectStreaming, there is a minor delay - subs typically appear at about 11-12 secs but there is no "loss' i.e. if you allow the subs to load and rewind the video, the subs will reappear correctly. This is unlike the problem I reported where the first kilobyte of the SRT file is entirely lost.


> try to skip a few times and you will see that the subtitles will be out of sync.

I tried this a reasonable number of times, cannot reproduce. Subs are still perfectly in sync.


> once you stop viewing in the middle of the video and resume it, you will see that the subtitles will also be out of sync.

Subs take a while to load, maybe 2-3 seconds, but it will eventually sync up perfectly as well.

**Comment by yocosweet** [comment]
Chrome works fine, Safari will have subtitles out of sync

**Comment by ikomhoog** [comment]
On PC i cannot reproduce the error either, even with 30+ skips it seems synced perfectly.
On Android however, i can just skip a few times and it will be out of sync by 5 lines of subtitles.
i made a screen recording: https://youtu.be/NIlt1BDSoYU
I found a new problem, Subtitles dont show up at all, i sat through the whole episode waiting for them to appear, they didnt.
i just recorded a small bit of it not appearing.
when i turn the subs off and on again they do work, and with correct timing (might be a little bit off but im fine with this amount).
then i started skipping, subs got slightly desynced, but when i went crazy while skipping back and fort the subs got out of sync by 20 seconds.
the voice says "I'm ray starling" at 2:33 in this video and the subs appear at 2:54
there is a lot of randomness involved with how much the subs get out of sync each skip, but i had a 2-3 second delay while just using jellyfin normally(not skipping like a madman as i did now).

**Comment by accountForIssues** [comment]
> I found a new problem, Subtitles dont show up at all, i sat through the whole episode waiting for them to appear, they didnt.
[Check](https://github.com/jellyfin/jellyfin/issues/2507#issuecomment-595581475) whether the sub file has BOM. On 10.5, subtitle files without BOM are not loaded and subtitle files with BOM, the first 1024 bytes are not loaded. The subtitles work fine in 10.4.3.

**Comment by Rassilion** [comment]
I have same problem, but it's worse on ps4 browser. Only one skip enough for cause de-sync and sometimes crashes browser.

The file I tested;
![image](https://user-images.githubusercontent.com/1886248/76497272-bb8b1300-644b-11ea-9dec-c8ca325ce7bf.png)

**Comment by ikomhoog** [comment]
@accountForIssues the subtitles are embedded(which the thread you linked also still has problems with), and they do show up when i turn them off and on again.
"The subtitles work fine in 10.4.3" they didnt that thread is just a different issue, i had this issue from before 10.4 but didnt have the time to dive further into it.

**Comment by Rassilion** [comment]
@ikomhoog is subtitle de-sync issue happened before 10.5.0? initial subtitle load delay is a known issue #935 not a bug, it waits feature request to be accepted.

**Comment by ikomhoog** [comment]
@Rassilion Yes i noticed it before, only by a small amount (except 1 time where it was delayed 5 seconds).
But since i didnt have the time to do more research, i just kept it to myself.

i can "fix" the sync issue by setting "burn subtitles" to "all complex formats" in the user/subtitles settings.
although it takes significantly more rendering power, since i cannot skip further than it has rendered.
when i try to do that it just renders on and doesnt play the video anymore.
i need to try and figure-out if it is due to rendering power(131fps rendering so i doubt it) or something else, but that will be a seperate issue.

**Comment by ikomhoog** [comment]
small update on the settings.
i was searching for a more low power build for my server and found out that apparently my cpu (i7-4820K) doesnt have quicksync.
But i set hardware transcoding to "quicksync" and its faster than "none".
maybe this causes the problem.

**Comment by Artiume** [comment]
> small update on the settings.
> i was searching for a more low power build for my server and found out that apparently my cpu (i7-4820K) doesnt have quicksync.
> But i set hardware transcoding to "quicksync" and its faster than "none".
> maybe this causes the problem.

Open your ffmpeg logs and look for Stream Mapping. It should look something like this
```
Stream mapping: Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264)) Stream #0:1 -> #0:1 (dts (dca) -> mp3 (libmp3lame)) 
 ```
Libx264 is software based. The HWA based coders should have their name in the mapping.

**Comment by ikomhoog** [comment]
Where can i find the ffmpeg logs?
I only see the normal logs in de log folder

**Comment by kxzaon** [comment]
It seems that we have a problem that is not just UTF-8 or BOM. (my srt are encoding with both #2507) Besides Internal subtitles that don't work with 10.5.2 (It is fixed #2653), external subtitles works perfectly fine on my Linux desktop with Firefox but they are completely out of sync after I'm seeking forward on the movie file on my android phone (with the official app and also with firefox preview). And my friends tells me that he has the same problem on his Ipad with Safari. 
My server's version is 10.5.2. I can't tell for sure if it was working before 10.5.0 but I don't remember anything like this.

**Comment by Artiume** [comment]
> Where can i find the ffmpeg logs?
> I only see the normal logs in de log folder

@ikomhoog If you see only normal logs then you aren't invoking ffmpeg and you are Direct Playing. When you are watching a stream, click Playback Info to see what it reports.

@kxzaon Have you tested 2653 yet? It might fix the sync issue if you dont recall this being an issue before.

**Comment by kxzaon** [comment]
> 
> @kxzaon Have you tested 2653 yet? It might fix the sync issue if you dont recall this being an issue before.
Yes I'm using docker jellyfin-nightly_20200325 from linuxserver.io with the fix included. And indeed the internal subs are back. But they suffer of the same problem, they desync when we seek forward or backward.

**Comment by iwalton3** [comment]
On Reddit the user 6P2C-TWCP-NB3J-37QY says that the subtitles don't appear for 30 seconds but do appear after seeking backwards. I suspect that the subtitle extraction itself can simply take a while. An experiment with `mkvmerge` and `ffmpeg` subtitle extraction seems to agree with this, as it appears to have to read the entire mkv file to extract subtitles. This could take a while if users are using a slow storage medium.

One possible solution would be to stream the output. The command:
```bash
ffmpeg -loglevel quiet -i file.mkv -map 0:s:0 -f srt -
```
will stream `srt` subtitles out of a file as they are being read. It might be worthwhile to look into streaming the subtitles or breaking them into chunks to speed up load times.

Another option would be to extract subtitles as part of a scheduled task or scan. Text subtitles usually use a rather small amount of space.

**Comment by ikomhoog** [comment]
@Artiume im pretty sure that im transcoding, as i specifically set my 1080p file to stream at 720p 4MB and the jellyfin dashboard shows that im transcoding.

this is what i can find in the normal logs, maybe that gives some info:
`/usr/local/bin/ffmpeg -ss 00:04:00.000 -c:v h264_cuvid -resize 1280x720 -noaccurate_seek -i file:"/tv/Infinite Dendrogram/Season 1/Infinite Dendrogram - S01E01 - The Beginning of Possibility.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset default -b:v 3808000 -maxrate 3808000 -bufsize 7616000 -profile:v high -force_key_frames:0 "expr:gte(t,240+n_forced*3)" -copyts -vf "subtitles='/tv/Infinite Dendrogram/Season 1/Infinite Dendrogram - S01E01 - The Beginning of Possibility.mkv:si=0'" -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000 -f hls -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 80 -hls_segment_filename "/cache/temp/transcoding-temp/transcoding-temp/transcoding-temp/transcodes/transcodes/transcodes/transcodes/9c7cf49848b66bc6c4436676fafdcc89%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/temp/transcoding-temp/transcoding-temp/transcoding-temp/transcodes/transcodes/transcodes/transcodes/9c7cf49848b66bc6c4436676fafdcc89.m3u8"`

@iwalton3 i like the idea of processing/extracting subtitle data during a scheduled task

**Comment by mariusoei** [comment]
> It seems that we have a problem that is not just UTF-8 or BOM. (my srt are encoding with both #2507) Besides Internal subtitles that don't work with 10.5.2 (It is fixed #2653), external subtitles works perfectly fine on my Linux desktop with Firefox but they are completely out of sync after I'm seeking forward on the movie file on my android phone (with the official app and also with firefox preview). And my friends tells me that he has the same problem on his Ipad with Safari.
> My server's version is 10.5.2. I can't tell for sure if it was working before 10.5.0 but I don't remember anything like this.

I'm having the same problem on 10.5.3 in the Android app. No problem on the web player on Windows with Brave browser, Chrome or Firefox either.
I thought the problem was with the app, so I opened an issue there: jellyfin/jellyfin-android#301

**Comment by definitio** [comment]
I still have the problem on Firefox.

**Comment by amatriain** [comment]
Same here. It happens in Firefox, both desktop (linux) and mobile (Android). It also happens with the native Android client. When playing videos in Kodi (jellyfin plugin in add-on mode, both Linux and Android) the problem doesn't happen.

**Comment by mikalauskas** [comment]
Same for iOS (Expo)

**Comment by GeorgeGedox** [comment]
The issue is still present in the current Android build and for me at least, it makes watching media impossible on the phone.

**Comment by Akasen** [comment]
I'm also going to report that on android that this sub desync on some videos. I've got some videos with the .ASS subs in them. They work fine on desktop, but just doesn't work on the mobile apps or even mobile browser with Firefox (untested on Chrome on Android)

I'm using the 2.0 RC5 at the moment just to see if a fix was there, none.

**Comment by Plinz** [comment]
On browser client, I also have problems to load embedded subtitles on mkv file ("Fetching Additional Data"), for a 14Gb movie it take 20/30 minutes to get the subtitles loaded. I'm using a the linuxserver.io docker for jellyfin version 10.6.4, hardware acceleration with VAAPI (I check on logs it' working), browser Firefox, reverse proxy : nginx-proxy-manager.

**Comment by makitsune** [comment]
I'm having this issue as well using Safari on iOS

**Comment by gabrielgbs97** [comment]
Same issur here, as others described. In Android browsers (Firefox, Chrome) and app (as others pointed out, it is a web based app)...

**Comment by TheNamelessWonderer** [comment]
This is still an issue in 10.7-RC2 with the new JavaScript subs. Restarting the server or playback doesn't seem to resolve it but it plays without any issues in Jellyfin-MPV-SHIM. The client is an iPad running 14.3 and the latest Jellyfin iOS app.

**Comment by tianzhuang55** [comment]
same issue with official 10.7.0, server run on docker of synology DS920+, client on iOS

**Comment by Victor4X** [comment]
This is still an issue, and the subtitles appear at the same time as this message in the console: `MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction completed for file: /path/to/video.mkv to /path/to/subtitles.ass`
So I would think that https://github.com/jellyfin/jellyfin/issues/2547#issuecomment-604222130 is on the right track.

**Comment by icanotc** [comment]
still an issue for me on ios and web, im on 10.7.0 currently

**Comment by sumeetkpatel** [comment]
I am having this exact problem with MKV files with embedded SSA Subtitles inside from Android Phones. 
I don't have any issue with the same server but on PC via the Chrome Web Client.

Both phones exhibit the no subitles until reselected or seeking, and sync is off.

Server Jellyfin Version: 10.6.4
Mobile Client: Jellyfin Android 2.2.3 (POCO X3)
Mobile Client: Jellyfin Android 2.2.3 (Galaxy A52 5G)

**Comment by foux** [comment]
Same issue here on the iOS and Android client

**Comment by tknx** [comment]
Same problem on subbed things on iOS client. Using most up to date docker. Especially if I skip ahead the subtitles can even appear minutes ahead of where they should be.

**Comment by adamhl8** [comment]
I'm having a similar issues on the Android client. Everything works perfectly fine on PC with the web client. My subtitles are separate, non-embedded .srt files. The subtitles basically run "slow" and are often 5-10 seconds behind the video.

**Comment by michpas** [comment]
Same issue. Using 10.7.5
Playback android. 
Videoplayer: default internal webplayer
Subtitles sync are off

**Comment by akhilesh171** [comment]
I've got the same issue on android. This issue also occurs if I just seek a video to my last played position by clicking on the seeking bar timeline.

I've tried allowing subtitle extraction on the fly to see if it makes any difference and unfortunately it doesn't.

**Comment by icanotc** [comment]
after a month of using jellyfin, it seems like the subtitle loads slow for me, only when the subtitle is embedded in the mkv file, I think it's because jellyfish have to read the entire file to extract the subtitles. since if I have a .ass file, the subtitles load instantly.

**Comment by DarrienG** [comment]
Obviously not an amazing solution, but I too can confirm burning in subtitles fixes it. Makes the iOS client much more usable though.

**Comment by dausruddin** [comment]
I am having the same issue. I watch mostly anime and they are using styled ASS/SSA a lot. Even after a minute, the subtitle don't show up. I waited for a while and rewinding a few times until appears. It is exhausting process when I need to do this for every single episodes.

**Comment by mugalugs** [comment]
I have the same issue on 10.7.6, with the android client using the web player, subtitles go in our out of syncing as seeks are performed back and forth. However changing the android client to use the native player seems to resolve this issue and in my brief testing had no issues.

**Comment by lyz-code** [comment]
Still an issue in 10.7.7, it works well in linux but, it get's delayed in Safari

**Comment by mkelzeer** [comment]
I have that in 10.7.7 as well on both Android & iOS.

**Comment by Earl0fPudding** [comment]
Is there at least a quickfix for this we can use until this properly gets fixed?
I already tried rearranging the subtitles in the MKV container as stream 0 and putting the subtitles into a separate .ass or .srt file, although nothing solved this problem (tested on 10.7.7 with the Android app).

**Comment by eltiel** [comment]
> Is there at least a quickfix for this we can use until this properly gets fixed? I already tried rearranging the subtitles in the MKV container as stream 0 and putting the subtitles into a separate .ass or .srt file, although nothing solved this problem (tested on 10.7.7 with the Android app).

I gave up trying to fix this problem and ended up using an external player.

**Comment by Earl0fPudding** [comment]
@eltiel Okay thanks, I just installed MPV on Android and just copy the stream URL of the episodes and play them in MPV. This is a bit inconvenient but it at least does the job without subtitles out of sync. 
I hope this get fixed anytime soon.

**Comment by eltiel** [comment]
> @eltiel Okay thanks, I just installed MPV on Android and just copy the stream URL of the episodes and play them in MPV. This is a bit inconvenient but it at least does the job without subtitles out of sync. I hope this get fixed anytime soon.

Since you're already using the Jellyfin Android app, there is an easier way. Install either VLC or MX Player and configure via the Client Settings to use external player. When you hit play, it should automatically trigger the selected player.

**Comment by mkelzeer** [comment]
ExoPlayer (Integrated player) also works fine. The web player (default) is the bugged one.

**Comment by cloudiesky** [comment]
> > @eltiel Okay thanks, I just installed MPV on Android and just copy the stream URL of the episodes and play them in MPV. This is a bit inconvenient but it at least does the job without subtitles out of sync. I hope this get fixed anytime soon.
> 
> Since you're already using the Jellyfin Android app, there is an easier way. Install either VLC or MX Player and configure via the Client Settings to use external player. When you hit play, it should automatically trigger the selected player.

That causes another problem. External player or Exoplayer plays with the original stream without transcoding. Bad for remote access.
Jellyfin Android TV is a solution in my case. But the interaction is bad for cell phone.

**Comment by TheNamelessWonderer** [comment]
> > > @eltiel Okay thanks, I just installed MPV on Android and just copy the stream URL of the episodes and play them in MPV. This is a bit inconvenient but it at least does the job without subtitles out of sync. I hope this get fixed anytime soon.
> > 
> > 
> > Since you're already using the Jellyfin Android app, there is an easier way. Install either VLC or MX Player and configure via the Client Settings to use external player. When you hit play, it should automatically trigger the selected player.
> 
> That causes another problem. External player or Exoplayer plays with the original stream without transcoding. Bad for remote access. Jellyfin Android TV is a solution in my case. But the interaction is bad for cell phone.

Set a bitrate limit or just turn down the bitrate in options when not on the same network as the server.

**Comment by dawidgarus** [comment]
I have the same issue. Some suggest that it may be cause by subtitle extraction but I don't think that's the case. I have simple MKV file without embedded subtitles:

```
ffmpeg version n5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, matroska,webm, from 'xyz.1080p.bluray.x264.mkv':
  Metadata:
    ENCODER         : Lavf59.16.100
  Duration: 02:18:06.70, start: 0.000000, bitrate: 11336 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 9.259000
      Metadata:
        title           : 00:00:00.000
    Chapter #0:1: start 9.259000, end 103.061000
      Metadata:
        title           : 00:00:09.259
[...]
    Chapter #0:49: start 7627.578000, end 8286.699000
      Metadata:
        title           : 02:07:07.578
  Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x800 [SAR 1:1 DAR 12:5], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 02:18:06.694000000
  Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)
    Metadata:
      DURATION        : 02:18:06.698000000

```
And subtitles in separate srt file:
```
﻿1
00:00:02,800 --> 00:00:08,300
...
```
Server:
```
Server: 634917eb2322
Version: 10.7.7
Operating System: Linux
Architecture: X64
```
And I subtitles are out of sync when resuming the playback on iOS Safari 14.4.1 and LG TV's webOS using web client.
It works fine on Firefox 99.

Right now, this issue is a dealbreaker for me and probably most users that are not from English speaking country.

**Comment by m33ts4k0z** [comment]
This(subs out of sync on resume) is still an active issue and occurs on mobile devices only(or at least Android). With every browser and the android app using the web player. Exoplayer or external players dont have this issue but they cant seem to play DTS audio and jellyfin doesnt transcode it so its unusable. The Android TV app on the other hand doesnt suffer from this issue using the web player. The subs work perfectly fine including DTS audio.

**Comment by dannymichel** [comment]
> This(subs out of sync on resume) is still an active issue and occurs on mobile devices only(or at least Android). With every browser and the android app using the web player. Exoplayer or external players dont have this issue but they cant seem to play DTS audio and jellyfin doesnt transcode it so its unusable. The Android TV app on the other hand doesnt suffer from this issue using the web player. The subs work perfectly fine including DTS audio.

I can confirm it's still an issue. is there a proposed fix?

**Comment by DarrienG** [comment]
> I can confirm it's still an issue. is there a proposed fix?

Quick fix is to burn in subtitles during playing. 

Settings -> subtitles -> burn subtitles 

Set to all or to complex formats (I have complex formats). 

It will require transcoding on playback but I have zero issues when I do this.

**Comment by dannymichel** [comment]
> > I can confirm it's still an issue. is there a proposed fix?
> 
> Quick fix is to burn in subtitles during playing.
> 
> Settings -> subtitles -> burn subtitles
> 
> Set to all or to complex formats (I have complex formats).
> 
> It will require transcoding on playback but I have zero issues when I do this.

Unfortunately this *workaround* won't work for me as burning subtitles on rclone mounted videos can take up to 3+ minutes for a video to just start.

**Comment by DarrienG** [comment]
Yeah it's an imperfect workaround, but a workaround nonetheless.

With that said you should probably consider looking into something like NFS especially if you're using your remote storage for video streaming. You'll get much better performance.

**Comment by dannymichel** [comment]
> NFS

i use rclone/mergerfs whick i can't not use because my sonarr/radarr etc. requires it.

**Comment by dannymichel** [comment]
> Yeah it's an imperfect workaround, but a workaround nonetheless.
> 
> With that said you should probably consider looking into something like NFS especially if you're using your remote storage for video streaming. You'll get much better performance.

this is pretty much my entire setup https://wikiold.servarr.com/Cloud_Setup

**Comment by das800** [comment]
this is still an issue on the android app

**Comment by dannymichel** [comment]
> this is still an issue on the android app

Might this be something that is being looked into for the release of 10.8?

**Comment by dannymichel** [comment]
Burning fails 50% of the time, other 50, takes 30 seconds to a minute to load
Extraction is immediate
https://youtu.be/jraQOg7L_xI

**Comment by cvium** [comment]
> no one seems to know what the problem is

Well...

With HLS specifically, there's a couple of _known_ and _theoretical_ issues. Just to name a few:

1. The HLS playlist isn't accurate, it's just a static playlist with 3s or 6s segments. This is _not_ within margin of error for remuxes as ffmpeg will cut before keyframes
2. Subtitles are extracted separately and played by timestamp with no frame corrections
3. Since segment lengths are inaccurate, the player's timestamp might not match the segment's PTS
4. Seeking is inaccurate due to the aforementioned segment length issue

So what's a possible solution? Put the subtitles in the HLS manifest.

**Comment by das800** [comment]
@cvium im not too familiar with HLS, just read up on it, but your saying that the lines in the M3U8 file that denote the length of the .ts file are just wrong? that what causes the seeking issues and subsequent subtitle issues?

but the app itself cuts up my .mkv for HLS right? so it should be able to know what the exact length of each segment it (by which i mean, even if doesnt now, that should be possible). so is it just a matter of looking at the part where the M3U8 files are prepped and checking if the code is storing the correct segment lengths?

if so then where is that code? i'll learn as much C# as it takes to help fix this

**Comment by cvium** [comment]
How the segments are made is very much internal to ffmpeg. We can only do so much.

In order for the server to start serving the file to you, it creates a fake hls manifest as we do not know the length of the segments or even the number of segments until ffmpeg is done.

Some work has been put into 10.8 already to create a more accurate playlist, but I've yet to see how it performs in the wild.

It's not something that is easy to fix and how clients implement the HLS spec can also influence the outcome.

**Comment by tophat17** [comment]
same issue here. My subs are out of sync no matter what sub-track I try. I have tried 3 sub tracks.

**Comment by dausruddin** [comment]
2 years later, this still an issue

Server: `10.8.1`
Android App: `2.4.4`

**Comment by random-human-being** [comment]
One of my friend just reported the same issue: using the web client via browser every sub track is out of sync by more than 30 sec.

Server: official docker container 10.8.1
Client: Firefox on Windows 10, direct play

**Comment by garret** [comment]
How is it possible that such issue has not been solved after two years? I cannot believe this is such a small issue like people are not watching movies with subtitles. 
I experience the out of sync subtitles problem both with latest android jellyfin app and with jellyfin for tyzen (on my Samsung tv). Jellyfin is installed on my raspberry pi 4b (raspberry pi os, 64 bit) via docker (jellyfin version 10.8.4). Unfortunately, cannot use the "burn subtitles" option since my raspberry pi is not such powerful. 
This is quite demotivating and pushes me to go back to other solutions like Plex.

**Comment by BaldissaraMatheus** [comment]
Does the development team have any plan to work on that? It's been a deal breaker for me too

**Comment by gabrielgbs97** [comment]
I have been with these issues for a year. The 'old' solution was to force transcoding (download in 1080 and playback in 720p, from mobile there is no difference) and burn subtitles (All). Today I discovered that there is a plugin that extracts embedded subtitles: https://github.com/jellyfin/jellyfin-plugin-subtitleextract

You need Jellyfin 10.8.1 to appear on plugin Catalog, but it's an easy upgrade for docker users.

This 'fixed' the issue for me (I would call it a workaround ...). Now I got DirectPlay + Subs with no out of sync issues, better buffering latency, etc. Plugin creates a task that you can execute on demand, still you can put a trigger (i.e. every day) after the very first extraction. Keep in mind that first subtitle extraction can take hours depending on the size of your media library (mine took 1h per TB maybe?), luckily it does not need to read 100% of file sequentially. Later runs will process only new files.

**Comment by KingYonatan** [comment]
> I have been with these issues for a year. The 'old' solution was to force transcoding (have media as 1080p and playback in 720p, from mobile there is no difference) and burn subtitles (All). Today I discovered that there is a plugin that extracts embedded subtitles: https://github.com/jellyfin/jellyfin-plugin-subtitleextract
> 
> You need Jellyfin 10.8.1 to appear on plugin Catalog, but it's an easy upgrade for docker users.
> 
> This 'fixed' the issue for me (I would call it a workaround ...). Now I got DirectPlay + Subs with no out of sync issues, better buffering latency, etc. Plugin creates a task that you can execute on demand, still you can put a trigger (i.e. every day) after the very first extraction. Keep in mind that first subtitle extraction can take hours depending on the size of your media library (mine took 1h per TB maybe?), luckily it does not need to read 100% of file sequentially. Later runs will process only new files.

Hey, I installed the plugin and ran the task but I don't see where the subtitles are saved. This issue is really aggravating and there is little documentation on how to use the plugin. Where are the extracted subtitles?

**Comment by anthonylavado** [comment]
@KingYonatan The subtitles get saved in a cache directory for Jellyfin to use them when playing back the video. It's named with the video's item ID from the database.

**Comment by das800** [comment]
been 3 years now. subtitles are still busted on android clients

**Comment by tknx** [comment]
I am actually thinking about going back to Plex.  

Although just like Plex, adding in music streaming and other stuff is mission creep while fundamentals are still broken.

**Comment by manuel-rw** [comment]
This may not be the solution we're hoping for, but "Findroid" as a third party app fixed the synchronisation issues for me - this is only a temporary solution though...

*Note: Findroid seems to have issues with complex subtitles, so it might not work for all scenarios*

**Comment by adamhl8** [comment]
I've been waiting to switch to jellyfin for almost 3 years now. This is the only issue that's keeping me from doing so :(

**Comment by cloudiesky** [comment]
It's fixed to me. With 10.8.9, Burning SUBs can be set as ALL. So, no more pain to play remotely with transcoding.

**Comment by michpas** [comment]
Hey Cloudiesky,
This sounds interesting.
Could you point me to the location of this setting of 'burning subs' all?

**Comment by BaldissaraMatheus** [comment]
Burning subs does force transcode, no? While playing mkv files without burning subs on firefox my server cpu consumption goes up to 40%, with burning subs it goes to over 90%. Also you cannot make this setting default for all users, every user has to enable it on subtitle settings menu

**Comment by cellulosa** [comment]
Any update on this issue?

**Comment by gabrielgbs97** [comment]
> Burning subs does force transcode, no? While playing mkv files without burning subs on firefox my server cpu consumption goes up to 40%, with burning subs it goes to over 90%. Also you cannot make this setting default for all users, every user has to enable it on subtitle settings menu

Right, burning subs is the cannonball solution for this...

**Comment by MartinFialka** [comment]
I also experienced this issue on Android TV Chromecast Jellyfin app.
So far it seems I have found a solution:

- In jellyfin app go to settings
- Playback / Preffered media player
- Swith to LibVLC (experimental)
- play movie again -> subtitles are fixed even when scrubbing through the move + resume also works fine.

I'm not sure but maybe you might need to install VLC app to see the option in step 3.
So far I haven't found any downsides.

**Comment by KazuhiraDokky** [comment]
> 

This fixed the issue for me, thank you! I did not need to install the VLC app for option 3 on Android TV at least. Forwarding and rewinding here and there in the film does not make the subtitles show up at the wrong time.

**Comment by AlbeyAmakiir** [comment]
Oddly, I've only just started having this issue after upgrading my motherboard and CPU. I generally watch though the WebOS 3 app, streamed to my tv on the local network. Before the change, I never had issues with subtitles. Now they fall out of sync over time, or when I seek.

Old Motherboard: ASUS P8Z68-V  
New Motherboard: Gigabyte Z590 UD  
Old CPU: Intel i5 2nd Gen  
New CPU: Intel i5 10th Gen

Not sure if this will be useful in tracking anything down, but it seemed notable.

**Comment by pipanni** [comment]
Hi everyone, Jellyfin newbie here.

I don't have any "Playback / Preffered media player" settings on my Jellyfin app. Where can I find this? I'm also a victim of the "out of sync subtitles" bug :P

**Comment by wkbt** [comment]
> I have been with these issues for a year. The 'old' solution was to force transcoding (have media as 1080p and playback in 720p, from mobile there is no difference) and burn subtitles (All). Today I discovered that there is a plugin that extracts embedded subtitles: https://github.com/jellyfin/jellyfin-plugin-subtitleextract
> 
> You need Jellyfin 10.8.1 to appear on plugin Catalog, but it's an easy upgrade for docker users.
> 
> This 'fixed' the issue for me (I would call it a workaround ...). Now I got DirectPlay + Subs with no out of sync issues, better buffering latency, etc. Plugin creates a task that you can execute on demand, still you can put a trigger (i.e. every day) after the very first extraction. Keep in mind that first subtitle extraction can take hours depending on the size of your media library (mine took 1h per TB maybe?), luckily it does not need to read 100% of file sequentially. Later runs will process only new files.

This doesn't fix the issue for me. And LibVLC as mentioned by someone else, does "fix" it, but makes the video stutter when using subtitles instead.

**Comment by AIndoria** [comment]
> I also experienced this issue on Android TV Chromecast Jellyfin app. So far it seems I have found a solution:
> I'm not sure but maybe you might need to install VLC app to see the option in step 3. So far I haven't found any downsides.

Downsides:

1. The seeking holds black screen while seeking/a second or so longer. Exoplayer seeking is fast on the other hand.
2. It's not foolproof. I've managed to desync subs this way. Often it takes fiddling back and forth with forwardx10, pause, see if it fixed it, back x10 etc. It's incredibly frustrating.

The fact that you can't use Jellyfin reliably on TV/android is ...actually a drealbreaker. I just moved all of my stack to use Jellyfin and discover this issue lol.

**Comment by wkbt** [comment]
> > I also experienced this issue on Android TV Chromecast Jellyfin app. So far it seems I have found a solution:
> > I'm not sure but maybe you might need to install VLC app to see the option in step 3. So far I haven't found any downsides.
> 
> Downsides:
> 
>     1. The seeking holds black screen while seeking/a second or so longer. Exoplayer seeking is fast on the other hand.
> 
>     2. It's not foolproof. I've managed to desync subs this way. Often it takes fiddling back and forth with forwardx10, pause, see if it fixed it, back x10 etc. It's incredibly frustrating.
> 
> 
> The fact that you can't use Jellyfin reliably on TV/android is ...actually a drealbreaker. I just moved all of my stack to use Jellyfin and discover this issue lol.

I've moved over to using Kodi on my Chromecast, with the Jellyfin addon. Works well enough, but would be awesome if the Jellyfin app would be fixed. So Kodi + Jellyfin is my current recommendation.

**Comment by KazuhiraDokky** [comment]
> > > I also experienced this issue on Android TV Chromecast Jellyfin app. So far it seems I have found a solution:
> > > I'm not sure but maybe you might need to install VLC app to see the option in step 3. So far I haven't found any downsides.
> > 
> > 
> > Downsides:
> > ```
> > 1. The seeking holds black screen while seeking/a second or so longer. Exoplayer seeking is fast on the other hand.
> > 
> > 2. It's not foolproof. I've managed to desync subs this way. Often it takes fiddling back and forth with forwardx10, pause, see if it fixed it, back x10 etc. It's incredibly frustrating.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The fact that you can't use Jellyfin reliably on TV/android is ...actually a drealbreaker. I just moved all of my stack to use Jellyfin and discover this issue lol.
> 
> I've moved over to using Kodi on my Chromecast, with the Jellyfin addon. Works well enough, but would be awesome if the Jellyfin app would be fixed. So Kodi + Jellyfin is my current recommendation.

I also moved to Kodi on Chromecast and on my Android TV. The VLC "workaround" was short lived as the issues suddenly reappeared. Also I got a major audio downgrade, the volume took a major nosedive. Still an issue on Kodi as well but at least I can increase the audio myself for each title so not too bad. Also the subtitle add-on on Kodi is really great! 
Had some issues setting it up but once it was up and running it is better.

Also... Moving to almost 4 years with this, I really wish it could be fixed so the Jellyfin Android/TV app is good enough.

**Comment by rodrigogonegit** [comment]
Also experiencing this unfortunately.

**Comment by dawidgarus** [comment]
@jellyfin-bot the issue has not been fixed

**Comment by felix920506** [comment]
Multiple people encountering, marking as confirmed

**Comment by Saturate** [comment]
I also have issues with this on a Android TV client.

**Comment by cloudiesky** [comment]
It may possiblely something mess up with the Subrip format.  I have try extern and embedded SRT subtitle, neither of them could sync. But with trans them in to ASS, subtitles always sync correctly.

**Comment by arzezio7** [comment]
It still persists. Using LIbVLC does not help because it will stretch any anamorphic format and there is no option to adjust it unlike ExoPlayer.

**Comment by emanuelbaltaretu** [comment]
This single one issue has kept me away from jellyfin for years... Once in a while i set up everything again with the latest release in hope the subtitles were finally fixed and work on my LG C1, guess maybe next year 😞

**Comment by emanuelbaltaretu** [comment]
> I'm having a similar problem suddenly on two TVs both running WebOS (LG) one on LAN (direct play) and another at another location (transcoding). Specifically noticing it with Subrip on high bitrate / filesize files. "Fetching additional data" never goes away and the subs never seem to show up. The same files/subs play fine with web and JF media players. Have not yet had the chance to exhaust every angle but hoping the Subtitle Extract plugin will work.

This single one issue has kept me away from jellyfin for years... Hunted by the "Fetching additional data" message...Once in a while i set up everything again with the latest release in hope the subtitles were finally fixed and work on my LG C1, guess maybe next year 😞

**Comment by rnyn** [comment]
> This single one issue has kept me away from jellyfin for years... Hunted by the "Fetching additional data" message...Once in a while i set up everything again with the latest release in hope the subtitles were finally fixed and work on my LG C1, guess maybe next year 😞

I seem to have mostly sorted the problem for me with some workarounds which i found in some comments here and on reddit 

1.  I used the Subtitle Extract plug-in to extract the subtitles from the media (took a looooong time to go through the whole library, as in weeks, but subsequently it runs once a day on stuff you add and is quick). 
2. On the webOS player, I set it the user settings so there is no preferred or default subtitle language, i.e. movies do not start with subs, you have to manually choose them after pressing play. 

Still leaves some things to be desired, sure, but that has worked for me so even 20 GB files don't do the fetching additional data thing anymore.

**Comment by viown** [comment]
Can confirm that subtitles are no longer out of sync when resuming or seeking with 10.9.2

**Comment by Insprill** [comment]
The issue is not fixed for me with v10.9.2. The startup delay and desync are still present in Firefox v126.0 and the IOS app v1.5.0 (5.5.0.0, expo 43.0.0). I haven't tested any other clients.

**Comment by wkbt** [comment]
> Can confirm that subtitles are no longer out of sync when resuming or seeking with 10.9.2

After some limited testing I can also confirm that the issue seems to have been solved on the Android TV app with 10.9.2.

**Comment by Mi3liX9** [comment]
I am facing this issue with 10.9.2 also

**Comment by rodrigogonegit** [comment]
Can confirm I'm still experiencing too.

**Comment by ToXinE** [comment]
this is even worse when hardware transcoding is enabled for me.

**Comment by franl08** [comment]
i did not have this problem with previous versions of Jellyfin, but in 10.9.2 web version it is impossible to watch something with subtitles.

**Comment by ToXinE** [comment]
any news ?

**Comment by wkbt** [comment]
Still having this issue on 10.9.7 and latest Jellyfin for Android TV app. My "fix" is to run Jellyfin through Kodi, but I prefer the lightness of the Jellyfin app... if subtitles would work properly.

**Comment by CiroPen** [comment]
I started having this issue with jellyfin web last month after reinstalling jellyfin (10.9.6) on my newly formatted home server. Before on some version earlier than 10.9.2 the issue was not present.

**Comment by CiroPen** [comment]
Just done some extra testing to provide actually useful information. When this bug is present, it is instantly noticeable any time I play any video with subtitles and I imagine any other users with similar media trying out jellyfin for the first time would see it as a deal breaker.

OS: Windows 11
Player: Jellyfin Web

I tested various versions of Jellyfin Server to check whether the bug is present:
- Version 10.8.13: No bug, subtitles are fine
- Version 10.9.0: No bug, subtitles are fine
- Version 10.9.1: Bug is present, subtitles are super early when seeking (i.e. skipping opening song of anime episode, skipping seconds with the arrow keys or manually selecting a timestamp on the seek bar)

The same issue is present when using 10.9.6 server on Linux.

From here it looks like the bug (re-?)appeared in version 10.9.1.

**Comment by tsieczko** [comment]
I face the same issue. 
OS: Debian
Player: Web and Android (issue occurs with web player but not Integrated player) 

Things that seem to fix it for me include disabling hardware transcoding OR disabling "Prefer fMP4-HLS Media Container" under Playback settings.

**Comment by Lampan-git** [comment]
I have this issues as well.
It only occurs "Prefer fMP4-HLS Media Container" and transcoding, either with hardware acceleration or without. I have this issue both in 10.9.11 and 10.10. 
This is really annoying and should be prioritized imo. Especially when "Prefer fMP4-HLS Media Container" is required for HEVC direct stream

**Comment by viown** [comment]
A work around is available on web: Profile -> Subtitles -> "Always burn in subtitles when transcoding"

**Comment by davidguy3237** [comment]
New Jellyfin user here that just experienced this same issue.

linuxserver's docker-jellyfin version 10.10.1 running in UNRAID version 6.12.13. I don't have any experience with previous versions of Jellyfin.

Tested on Firefox, Safari, Chrome, and iPad/iOS app (not Swiftfin).

Just reaffirming others experience that it only happens when transcoding while "Prefer fMP4-HLS Media Container" is enabled in the Advanced section of Playback settings. For me it doesn't seem to matter whether hardware acceleration is enabled or not, as long as it is transcoding. 

No issues with direct playback.

Disabling "Prefer fMP4-HLS Media Container" fixes the timing.
Enabling "Always burn in subtitle when transcoding" in the Subtitles settings also works if you want to keep "Prefer fMP4-HLS Media Container" turned on.

**Comment by sbmf21** [comment]
I started experiencing this as well a couple weeks ago, turning off `Prefer fMP4-HLS Media Container` does seem to fix the synchronization issue however I noticed that there's still a time offset when it's transcoding, I haven't found another issue about that and I think it could be related?
Anyway I tested it and with a lot of media (mostly mkv hvec/av1 sources) when I play them and it's transcoding there's a couple seconds offset, like the transcoded media is anywhere between 1-5 seconds offset to the source. Having both direct play open in one client and transcoding in the other gave different images on the same timestamp. I also found that skipping ahead or back to parts that haven't yet been transcoded changes the offset, so sometimes skipping makes the offset worse and sometimes it's suddenly gone.

My setup:
Jellyfin 10.10.1 on Debian 12.7 (Linux kernel 6.10.11) and it's web client
Using an Arc A310 for hw transcoding (same results with my old GTX 1070)
Jellyfin windows client 1.11.1

**Comment by WatToDoWad** [comment]
In my opinion, the original issue referenced by this issue **4 years ago** is not the same issue currently experienced in 10.9.x, and the newer issues, #11825 #11995 #12164, closed by @felix920506 should have been consolidated and preferred over this one. Nevertheless, the current issue experienced is **different** from what the title suggest, and a more accurate title could've been "_Subtitles are out-of-sync when resuming or seeking_". Just food for thought.

> I started experiencing this as well a couple weeks ago, turning off `Prefer fMP4-HLS Media Container` does seem to fix the synchronization issue however I noticed that there's still a time offset when it's transcoding, I haven't found another issue about that and I think it could be related? Anyway I tested it and with a lot of media (mostly mkv hvec/av1 sources) when I play them and it's transcoding there's a couple seconds offset, like the transcoded media is anywhere between 1-5 seconds offset to the source. Having both direct play open in one client and transcoding in the other gave different images on the same timestamp. I also found that skipping ahead or back to parts that haven't yet been transcoded changes the offset, so sometimes skipping makes the offset worse and sometimes it's suddenly gone.
> 
> My setup: Jellyfin 10.10.1 on Debian 12.7 (Linux kernel 6.10.11) and it's web client Using an Arc A310 for hw transcoding (same results with my old GTX 1070) Jellyfin windows client 1.11.1

I have started doing a fairly deep dive into the issue and can confirm that while replaying the same media offline, the subtitle to timestamp offset is **identical**, but the audio & visual to timestamp offset is **different**.  Perhaps the title should be "_**Transcoded content is randomly offset during resumption and seeking**_" to highlight the fact that the issue _could_ be the audio/visual streams and not the subtitles.

---

One thing I noticed that might be relevant (again, not confident), was the difference in how the player seems to be retrieving the streams between the fMP4 container and the normal container. Surely the initial stream should not be `-1`? 

| how fmp4 seems to do streams | and how it should be? |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/9467518b-f607-4e0d-96ff-a0eb831d80d9) | ![Image](https://github.com/user-attachments/assets/b2233e8e-53de-4c75-be48-02a0daf4588e) |
| ![Image](https://github.com/user-attachments/assets/9fdbabe2-51f7-4fab-ac74-606350fe95b6) | ![Image](https://github.com/user-attachments/assets/ec502ea5-211b-4057-82a0-3f8ad3bcd263) |

**Comment by gnattu** [comment]
Transcoding almost always changes timing due to syncing and hardware encoder constraints and we do have an option in 10.10 where you can force burn in when transcoding is triggered. In subtitle settings.

**Comment by gnattu** [comment]
@WatToDoWad I’m sorry but I have to hide your lengthy reply because the conclusion you draw from your observation is wrong and will mislead more users. Fragmented mp4 will have an initial fragment without any of the actual frames and that is completely normal. This container is designed to work differently from MPEG-TS.

**Comment by WatToDoWad** [comment]
> Transcoding almost always changes timing due to syncing and hardware encoder constraints and we do have an option in 10.10 where you can force burn in when transcoding is triggered. In subtitle settings.

Yet this wasn't an issue pre-10.9, so clearly something _has_ changed between 10.8 and 10.9 which has caused this issue to surface. I might add that this issue also occurs with remuxed medias and I shouldn't have to force transcoding for subtitles to get it to sync up when the issue occurs.

> [@WatToDoWad](https://github.com/WatToDoWad) I’m sorry but I have to hide your lengthy reply because the conclusion you draw from your observation is wrong and will mislead more users. Fragmented mp4 will have an initial fragment without any of the actual frames and that is completely normal. This container is designed to work differently from MPEG-TS.

That is understandable, but in that case can you also hide the previous replies before 10.8 as outdated then? Alternatively, I will repost my original comment sans the "incorrect" portion.

--- 

Original response:

In my opinion, the original issue referenced by this issue **4 years ago** is not the same issue currently experienced in 10.9.x, and the newer issues, #11825 #11995 #12164, closed by @felix920506 should have been consolidated and preferred over this one. Nevertheless, the current issue experienced is **different** from what the title suggest, and a more accurate title could've been "_Subtitles are out-of-sync when resuming or seeking_". Just food for thought.

> I started experiencing this as well a couple weeks ago, turning off `Prefer fMP4-HLS Media Container` does seem to fix the synchronization issue however I noticed that there's still a time offset when it's transcoding, I haven't found another issue about that and I think it could be related? Anyway I tested it and with a lot of media (mostly mkv hvec/av1 sources) when I play them and it's transcoding there's a couple seconds offset, like the transcoded media is anywhere between 1-5 seconds offset to the source. Having both direct play open in one client and transcoding in the other gave different images on the same timestamp. I also found that skipping ahead or back to parts that haven't yet been transcoded changes the offset, so sometimes skipping makes the offset worse and sometimes it's suddenly gone.
> 
> My setup: Jellyfin 10.10.1 on Debian 12.7 (Linux kernel 6.10.11) and it's web client Using an Arc A310 for hw transcoding (same results with my old GTX 1070) Jellyfin windows client 1.11.1

I have started doing a fairly deep dive into the issue and can confirm that while replaying the same media offline, the subtitle to timestamp offset is **identical**, but the audio & visual to timestamp offset is **different**.  Perhaps the title should be "_**Transcoded content is randomly offset during resumption and seeking**_" to highlight the fact that the issue _could_ be the audio/visual streams and not the subtitles.

**Comment by gnattu** [comment]
> Yet this wasn't an issue pre-10.9, so clearly something has changed between 10.8 and 10.9 which has caused this issue to surface. I might add that this issue also occurs with remuxed medias and I shouldn't have to force transcoding for subtitles to get it to sync up when the issue occurs.

This is total illusion. The only thing has changed is that fmp4 was not enabled as default pre 10.9. 10.8 will behave the same way if you enable prefer fmp4 but unfortunately chrome did not work with that option in 10.8 so most people did not even have a chance to even realize that.

Timing information being altered after transcoding is the anticipated behavior, and this issue will only worsen with fmp4 since we can only seek to keyframes to maintain audio and video synchronization. With mpegts, it can perform accurate seeking to the precise time and frame, which makes the subtitles appear more synchronized. What’s more, the keyframe interval is significantly different after transcoding, resulting in a more significant deviation in the seek position. For remuxing, we already have a workaround that ensures most videos have subtitles synchronized after remuxing. For a small portion videos that still have this issue during remuxing are likely to have a very poor keyframe interval that is not friendly with HLS, causing the seek frame to be different from the intended frame, leading to out-of-sync subtitles once again. 

I understand you want to be helpful and I appreciate your time spent on doing experiments, but I’m sorry and we already know all the things you found. Those are currently how things works with no easy workaround. The always burn in when transcoding option is the easiest workaround we can implement and it is already landed with 10.10 release. Just enable that option will make things work for most of the use cases, at least for most of my own media.

**Comment by cstoicescu** [comment]
Can confirm for all the folks out there: There is a problem with x265 on Chrome and Firefox  if you have enabled (**Prefer fMP4-HLS Media Container** ), which i personally prefer. On **Edge** it works fine with this option. On the codecs support, it states that Chrome and Firefox do not fully support x265. So either Disable HLS container or Force Burn in any Transcode subtitle

**Comment by LoganTann** [comment]
> A work around is available on web: Profile -> Subtitles -> "Always burn in subtitles when transcoding"

I confirm this workaround works. You'll need to restart the web page for the changes to take effect.
It's unfortunate that this parameter can only be configured by the user, rather than applying it for everybody in the server.

**Comment by LeonidasLK** [comment]
can confirm this happens to me also.

**Comment by andrei-indreies** [comment]
Hello guys! Do you have updates on this issue? All my movies got subtitles and I got 12 users, so turning always burn option is a pain. I got this issue on samsung tvs, lg tvs, android tvs, ipad and iphones.

**Comment by gigante154** [comment]
The key finding from my testing is that the behavior is entirely client-dependent:

Works: On a PC using the Chrome browser and Jellyfin Media Player , I can stop and resume playback without any subtitle sync issues.

Fails: The desync issue occurs consistently on the latest Jellyfin Android app (both on my smartphone and Android TV) and on a PC using the Firefox browser.

**Comment by mirino75** [comment]
The desync issue occurs consistently on the latest Jellyfin Android app . I changed value in app "Settings/Client settings/Video Player type" from Web Player to Integrated player and everything is ok.

**Comment by ananthb** [comment]
Same issue on my Chromecast with Google TV app. Subtitles go out of sync on seeking or pausing for a while. I'm able to get tham back in sync by stopping and restarting playback.

**Comment by KimPig** [comment]
In Edge browser the subtitles stay in sync, but in Browsers like Vivaldi and Opera they are already out of sync from the very start. I still haven’t been able to figure out the root cause.

**Comment by olafur-palsson** [comment]
I'm having this issue pretty much every time I skip/seek on Android.

Currently I'm doing this to "fix" it.
1. Go to menu.
2. Play random show
3. Go to menu.
4. Play original show

I can see a couple of potential fixes but I don't know the code base so some of these probably make no sense:
* "Reset subs" button that just resets the player entirely. 
* Subs are a frontend element that plays based on video timestamp.
* Suspend subtitle timer while loading and resume afterwards (I feel like the subs timing move around the same as the amount of time to seek).
* "Always burn in subtitles" probably tricky because of codec variety.

I think rendering subs on the frontend is probably the best way to do it since the timer of the video is pretty accurate, I think.

**Comment by guillaumeperes** [comment]
Hello, any updates in this issue?

**Comment by Pentaphon** [comment]
This happens fairly often even on the latest Android TV client with directplay using media3.

**Comment by PeachesMLG** [comment]
> This happens fairly often even on the latest Android TV client with directplay using media3.

You can replicate this with directplay?

I know there is a bug with transcoding where ffmpeg provides noaccurate_seek

You can try this yourself if you run an ffmpeg command and setting a -ss 00:10:00.000 (e.g. start at 14 minutes) and adding -noaccurate_seek - you can see although you told ffmpeg to start at 10 minutes it actually starts at like 9 minutes 48 seconds for example.

So the way client thinks its playing at 10 minutes in (since thats what it told ffmpeg to transcode) but ffmpeg actually started playing at 9:48. So the subtitles are playing at the correct time however the video is not synced correctly.



However I have not seen any issues with this on direct play since it doesnt transcode the media

**Comment by tuzidaguai** [comment]
> > This happens fairly often even on the latest Android TV client with directplay using media3.
> 
> You can replicate this with directplay?
> 
> I know there is a bug with transcoding where ffmpeg provides noaccurate_seek
> 
> You can try this yourself if you run an ffmpeg command and setting a -ss 00:10:00.000 (e.g. start at 14 minutes) and adding -noaccurate_seek - you can see although you told ffmpeg to start at 10 minutes it actually starts at like 9 minutes 48 seconds for example.
> 
> So the way client thinks its playing at 10 minutes in (since thats what it told ffmpeg to transcode) but ffmpeg actually started playing at 9:48. So the subtitles are playing at the correct time however the video is not synced correctly.
> 
> However I have not seen any issues with this on direct play since it doesnt transcode the media

Is the situation you're describing the same problem I encountered? I'm not personally sure.
https://github.com/jellyfin/jellyfin-webos/issues/253

**Comment by gorucci** [comment]
I have not tested it extensively, but from my experience, subtitle desync during transcoding can be caused by dropped frames. 
Moreover, it looks like the desync shift time is close to the number of dropped frames divided by the media's fps. 

Client: safari on macos.

**Comment by italocjs** [comment]
> I have not tested it extensively, but from my experience, subtitle desync during transcoding can be caused by dropped frames. Moreover, it looks like the desync shift time is close to the number of dropped frames divided by the media's fps.
> 
> Client: safari on macos.

Also on safari/macOs,  after reading this i noticed you are right, i have dropped frames here.
```
Play method Re-muxing
Player dimensions 3840x2160 
Video resolution 1920x1080
Dropped frames
283
```

This has been a pretty long issue, i`ve had it for years, refreshing the page works, but its a but annoying to do every few minutes. Happens both on a macbook air m4 (safari) and on a dell g15 (edge).

**Comment by pau1h** [comment]
Hi, I am also experiencing this. Is there anything I can work on to fix this bug?

**Comment by wellloaded** [comment]
Jellyfin is a really great software. I mean it.
This of the subtitles off-sync really is the very only issue I would mention, everything else is working extremely well on my side.
Somehow this also surprises me, higher complex issues have been resolved by the skilled developers in the recent past, but this very issue reference is now 6 years old and as far as I can tell there's no light at the end of the tunnel.

When it happens my workaround is to roll back 10-20 or even 30 seconds then most of the time it is re-syncing properly or stay off sync but an amount of time that is acceptable. Still a work-around though.

**Comment by Jurrer** [comment]
for anyone having the issue
1. Chrome can direct play most of the formats. No transcode no issue.
2. Force burn in subtitles when transcoding. You can set it per user in Settings -> Subtitles

Edit1: Sometimes transcoding happens on older devices because they don't have hardware support.
