### ISSUE TITLE
Infuse client can't log in unless user is admin user

### ISSUE THREAD

**Issue by grigsby** [jellyfin/jellyfin#3599]
I'm sorry, I don't know if this is a bug with the Infuse client, or with Jellyfin.

**Describe the bug**
For Infuse client (v 6.4.6 on iOS and tvOS/AppleTV), when adding Jellyfin media server and entering the Username and Password, the client returns an error and is not allowed to log in unless the user has "Allow this user to manage the server" check (i.e. is an admin user) on the Jellyfin server.

**System (please complete the following information):**
 - OS: Unraid running jellyfin/jellyfin:nightly ("10.6.0 undefined") docker container
 - Virtualization: Docker
 - Clients: Infuse Pro 6.4.6 on iOS 13, iOS 14, and tvOS
 - Browser: n/w
 - Jellyfin Version: nightly, including nightly-20200711
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: N/A (same issue happens even when server IP address and port is specified)
 - Base URL: [e.g. none, yes: /example]
 - Networking: Bridge
 - Storage: local disks on Unraid

**To Reproduce**
1. Open Infuse client on iOS, ipadOS, or tvOS
2. Click on Settings (gear icon)
3. Click on "Add Files"
4. Click on "+ Add Media Server"
5. Click on "Other Jellyfin..."
6. Enter server address, username, and password for a NON ADMIN user
7. Click on "Save"
8. Pop-op dialog says "An error occurred" and the user can not log in.

If you go into the Jellyfin server and enable "Allow this user to manage the server" the Infuse client can now log in properly.

**Expected behavior**
Add Jellyfin server to Infuse client as normal, without having to enable "Allow this user to manage the server" for every user.

**Logs**
Jellyfin log shows:
```
[2020-07-19 00:42:40.370 -07:00] [ERR] [59] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://jellyfin.mydomain.org/Users/AuthenticateByName"
System.FormatException: Input string was not in a correct format.
   at ServiceStack.Text.DefaultMemory.ParseGeneralStyleGuid(ReadOnlySpan`1 value, Int32& len) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 629
   at ServiceStack.Text.DefaultMemory.ParseGuid(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 414
   at ServiceStack.Text.Common.DeserializeBuiltin`1.<>c.<GetParseStringSpanFn>b__7_6(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeBuiltin.cs:line 72
   at ServiceStack.Text.Jsv.JsvReader.<>c__DisplayClass2_0.<GetParseFn>b__0(String v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Jsv\JsvReader.Generic.cs:line 18
   at Emby.Server.Implementations.Services.StringMapTypeDeserializer.PopulateFromMap(Object instance, IDictionary`2 keyValuePairs)
   at Emby.Server.Implementations.Services.RestPath.CreateRequest(String pathInfo, Dictionary`2 queryStringAndFormData, Object fromInstance)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(IRequest httpReq, RestPath restPath, Dictionary`2 requestParams, Object requestDto)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(HttpListenerHost host, IRequest httpReq, RestPath restPath, ILogger logger)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-19 00:42:40.386 -07:00] [INF] [56] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "Wife" has succeeded.
[2020-07-19 00:42:40.392 -07:00] [INF] [56] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 844897bf-b69d-4014-bb67-d1e2acfbb3c1
[2020-07-19 00:42:40.613 -07:00] [ERR] [56] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "User does not have admin access". URL: "http://jellyfin.mydomain.org:443/Library/VirtualFolders"
[2020-07-19 00:44:16.668 -07:00] [INF] [90] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:192.168.1.1" request
[2020-07-19 00:44:41.724 -07:00] [ERR] [100] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://jellyfin.mydomain.org/Users/AuthenticateByName"
System.FormatException: Input string was not in a correct format.
   at ServiceStack.Text.DefaultMemory.ParseGeneralStyleGuid(ReadOnlySpan`1 value, Int32& len) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 629
   at ServiceStack.Text.DefaultMemory.ParseGuid(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\DefaultMemory.cs:line 414
   at ServiceStack.Text.Common.DeserializeBuiltin`1.<>c.<GetParseStringSpanFn>b__7_6(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeBuiltin.cs:line 72
   at ServiceStack.Text.Jsv.JsvReader.<>c__DisplayClass2_0.<GetParseFn>b__0(String v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Jsv\JsvReader.Generic.cs:line 18
   at Emby.Server.Implementations.Services.StringMapTypeDeserializer.PopulateFromMap(Object instance, IDictionary`2 keyValuePairs)
   at Emby.Server.Implementations.Services.RestPath.CreateRequest(String pathInfo, Dictionary`2 queryStringAndFormData, Object fromInstance)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(IRequest httpReq, RestPath restPath, Dictionary`2 requestParams, Object requestDto)
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(HttpListenerHost host, IRequest httpReq, RestPath restPath, ILogger logger)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by anthonylavado** [comment]
Fixed in an upcoming update to Infuse.

**Comment by anthonylavado** [comment]
Fixed in today's update to Infuse (6.4.7).

**Comment by UrTerrible** [comment]
I am having a similar issue now. 

`[2023-10-10 21:12:40.301 +00:00] [INF] Authentication request for "james" has succeeded.
[2023-10-10 21:12:40.301 +00:00] [INF] Current/Max sessions for user "james": 6/0
[2023-10-10 21:12:40.302 +00:00] [INF] Reissuing access token: "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
[2023-10-10 21:12:40.516 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was forbidden.
[2023-10-10 21:12:40.648 +00:00] [ERR] Error processing request. URL "GET" "/InfuseSync/UserFolders/1d53c68e128c42f6a62242add5336a3a".
System.ArgumentNullException: Value cannot be null. (Parameter 'g')`

**Comment by felix920506** [comment]
@UrTerrible Hi, please head to our Matrix/Discord channels for help with troubleshooting: https://jellyfin.org/contact

**Comment by puellaexmachina** [comment]
This same error is still occurring on my end with Infuse 7.7.2. If an account isn't an admin user, it can't sign in. When I grant that user admin rights, they can sign in -- and after the first time, they no longer require admin rights.

It's so weird. The only thing that I've changed on my server is putting it behind a HTTPS-based reverse proxy, but I doubt that would actually do anything. I'm still connecting on port 443 with HTTPS anyways.

**Comment by bitboxer** [comment]
I can confirm this. People need to have admin rights to be able to login to jellyfin using infuse. Can you please re-open this?

**Comment by felix920506** [comment]
Report to infuse, it's not a problem on our end
