### ISSUE TITLE
Playback of FLAC fails on iOS

### ISSUE THREAD

**Issue by Schroedingers-Cat** [jellyfin/jellyfin#3726]
**Media Info of the file**
[flac.txt](https://github.com/jellyfin/jellyfin/files/4986573/flac.txt)

**Logs**

[Jellyfin-FLAC.txt](https://github.com/jellyfin/jellyfin/files/4986641/Jellyfin-FLAC.txt)

**FFmpeg Logs**
No FFmpeg log entry created when playing back a FLAC file from iOS.

**Server System:**
 - OS: Ubuntu 18.04, Docker
 - Jellyfin Version: 10.6.0
 - Hardware settings & device: No hardware acceleration enabled, i3-4130
 - Reverse proxy: nginx
 - Other hardware notes: media ro mounted
 
**Client System (please complete the following information):**
 - Device: Apple iPhone SE (2020), ~Apple iPad Pro~ (fixed), MacBook Pro 13 (working fine)
 - OS: iOS 13.6-14.4, macOS 10.15.6
 - Client: Webbrowser and Jellyfin App
 - Browser (if Web client): Firefox, Safari
 - Client and Browser Version: Firefox 27.0-32.0 (iOS), Safari ? (iOS), Firefox 81 (macOS)

Playback of FLAC files works on macOS 10.15.6/Safari 14, Windows and Android.

**Comment by nyanmisaka** [comment]
@YouKnowBlom 
CODEC name [`fLaC`](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices/hls_authoring_specification_for_apple_devices_appendixes#3151794) have not been implemented in `HlsCodecStringFactory.cs`

**Comment by Schroedingers-Cat** [comment]
@nyanmisaka on-the-fly-transcoding to something lossy would be preferred to save bandwith when the client is not in the same local network.

**Comment by YouKnowBlom** [comment]
> @YouKnowBlom 
> CODEC name [`fLaC`](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices/hls_authoring_specification_for_apple_devices_appendixes#3151794) have not been implemented in `HlsCodecStringFactory.cs`

Do we allow FLAC over HLS? If so that seems like a design flaw as it shouldn't be supported by .ts

**Comment by nyanmisaka** [comment]
> Do we allow FLAC over HLS? If so that seems like a design flaw as it shouldn't be supported by .ts
Well. Currently we do not allow flac in mepgts. But directplay should support it.

**Comment by nyanmisaka** [comment]
> @nyanmisaka on-the-fly-transcoding to something lossy would be preferred to save bandwith when the client is not in the same local network.

I managed to play flac on my iPad Pro Gen3 with iOS 13.6. Jellyfin is the latest 10.6.1.
Seems that you have set the audio bitrate limit, but I did not find this option in the web client.

**Comment by dkanada** [comment]
It's in the user settings under playback.

**Comment by Schroedingers-Cat** [comment]
@nyanmisaka I updated the docker image to 10.6.1 and I can playback flac files in my iPad Pro now, too. But it still fails on the iPhone SE.

**Comment by nyanmisaka** [comment]
> It's in the user settings under playback.

The Music quality settings is definitely missing in web client. But it appears in Android client.
![16099CB3-DAE1-418B-BF81-CE7A5F7B0670](https://user-images.githubusercontent.com/14953024/88657627-cdbcd380-d104-11ea-9811-03ff868aa021.jpeg)

**Comment by Schroedingers-Cat** [comment]
@nyanmisaka on my iPhone, that setting is present in both the App and the Webbrowser.
<img width="375" alt="Bildschirmfoto 2020-07-28 um 13 33 46" src="https://user-images.githubusercontent.com/6382400/88660584-8a437480-d0c6-11ea-84bd-b5eb1acf6490.png">

**Comment by thornbill** [comment]
I'm seeing the same issue with WAV and FLAC on _some_ iOS devices.

iPhone 7+ iOS 13.4.1: Not working
iPad (7th gen) iOS 13.5.1: Working

**Comment by anthonylavado** [comment]
Running an iPhone X with iOS 13.6.
I can report that it works when playing *locally* (same network), but if I try externally, it fails.

There's an error message in the log about exceeding the bitrate limit.

At the same time, I don't see the mentioned Music Quality Playback settings on either desktop or mobile (browser/iOS Expo app).

**Comment by thornbill** [comment]
Logs for iPhone where playback is broken:
```
jellyfin-test_1  | [16:41:33] [DBG] [68] Emby.Server.Implementations.Data.SqliteItemRepository: GetItemList query time (slow): 12.8372ms. Query: select type,data,EndDate,ChannelId,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,IsInMixedFolder,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,ProviderIds,TotalBitrate,ExtraType,ExternalId,OwnerId from TypedBaseItems A where type=@type AND CleanName=@Name
jellyfin-test_1  | [16:41:33] [INF] [68] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: {"Name": null, "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": 0, "MaxAlbumArtHeight": 0, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 8000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 128000, "MaxStaticMusicBitrate": null, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 0, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": "mp3", "AudioCodec": "mp3", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "aac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "aac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "flac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "alac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "alac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "wav", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": "aac", "Type": "Audio", "VideoCodec": null, "AudioCodec": "aac", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [], "$type": "DeviceProfile"}
jellyfin-test_1  | [16:41:33] [INF] [68] MediaBrowser.Api.Playback.MediaInfoService: User policy for Bill. EnableAudioPlaybackTranscoding: True
jellyfin-test_1  | [16:41:33] [INF] [68] MediaBrowser.Api.Playback.MediaInfoService: Bitrate exceeds DirectStream limit: media bitrate: 1277424, max bitrate: 800000
jellyfin-test_1  | [16:41:33] [INF] [68] MediaBrowser.Api.Playback.MediaInfoService: Bitrate exceeds DirectStream limit: media bitrate: 1277424, max bitrate: 800000
jellyfin-test_1  | [16:41:33] [INF] [69] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: {"Name": null, "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": 0, "MaxAlbumArtHeight": 0, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 8000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 128000, "MaxStaticMusicBitrate": null, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 0, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": "mp3", "AudioCodec": "mp3", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "aac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "aac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "flac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "alac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "alac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "wav", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": "aac", "Type": "Audio", "VideoCodec": null, "AudioCodec": "aac", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [], "$type": "DeviceProfile"}
jellyfin-test_1  | [16:41:33] [INF] [69] MediaBrowser.Api.Playback.MediaInfoService: User policy for Bill. EnableAudioPlaybackTranscoding: True
jellyfin-test_1  | [16:41:33] [INF] [69] MediaBrowser.Api.Playback.MediaInfoService: Bitrate exceeds DirectStream limit: media bitrate: 1277424, max bitrate: 800000
jellyfin-test_1  | [16:41:33] [INF] [69] MediaBrowser.Api.Playback.MediaInfoService: Bitrate exceeds DirectStream limit: media bitrate: 1277424, max bitrate: 800000
```

Logs for iPad where playback is working:
```
jellyfin-test_1  | [16:44:05] [INF] [184] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: {"Name": null, "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": 0, "MaxAlbumArtHeight": 0, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 8000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 128000, "MaxStaticMusicBitrate": null, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 0, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": "mp3", "AudioCodec": "mp3", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "aac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "aac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "flac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "alac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "alac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "wav", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": "aac", "Type": "Audio", "VideoCodec": null, "AudioCodec": "aac", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [], "$type": "DeviceProfile"}
jellyfin-test_1  | [16:44:05] [INF] [184] MediaBrowser.Api.Playback.MediaInfoService: User policy for nopass. EnableAudioPlaybackTranscoding: True
jellyfin-test_1  | [16:44:05] [DBG] [184] Emby.Server.Implementations.HttpServer.HttpResultFactory: Setting range response values for /media/omv-pi/media/music/Various Artists/Ben Prunty Music - FTL/Ben Prunty Music - FTL - 01 Space Cruise (Title).flac. RangeRequest: bytes=0-1 Content-Length: 2, Content-Range: bytes 0-1/38322738
jellyfin-test_1  | [16:44:05] [INF] [82] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: {"Name": null, "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": 0, "MaxAlbumArtHeight": 0, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 8000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 128000, "MaxStaticMusicBitrate": null, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 0, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": "mp3", "AudioCodec": "mp3", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "aac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "aac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "flac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "alac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "alac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "wav", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": "aac", "Type": "Audio", "VideoCodec": null, "AudioCodec": "aac", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [], "$type": "DeviceProfile"}
jellyfin-test_1  | [16:44:05] [INF] [82] MediaBrowser.Api.Playback.MediaInfoService: User policy for nopass. EnableAudioPlaybackTranscoding: True
jellyfin-test_1  | [16:44:05] [DBG] [82] Emby.Server.Implementations.HttpServer.HttpResultFactory: Setting range response values for /media/omv-pi/media/music/Various Artists/Ben Prunty Music - FTL/Ben Prunty Music - FTL - 01 Space Cruise (Title).flac. RangeRequest: bytes=0-38322737 Content-Length: 38322738, Content-Range: bytes 0-38322737/38322738
jellyfin-test_1  | [16:44:05] [DBG] [82] Emby.Server.Implementations.HttpServer.HttpResultFactory: Transmit file /media/omv-pi/media/music/Various Artists/Ben Prunty Music - FTL/Ben Prunty Music - FTL - 01 Space Cruise (Title).flac
jellyfin-test_1  | [16:44:05] [INF] [159] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: {"Name": null, "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": 0, "MaxAlbumArtHeight": 0, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 8000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 128000, "MaxStaticMusicBitrate": null, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 0, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": "mp3", "AudioCodec": "mp3", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "aac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "aac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "flac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "alac", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4a", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "m4b", "AudioCodec": "alac", "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": "wav", "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": "aac", "Type": "Audio", "VideoCodec": null, "AudioCodec": "aac", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [], "$type": "DeviceProfile"}
jellyfin-test_1  | [16:44:05] [ERR] [95] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: The operation was canceled. URL: http://jellyfin-test:8096/Audio/deb2be35c0723aed577814bb9dfb88a4/universal?UserId=36169f00290e42f3b67d638d93285f2d&DeviceId=409A350D-3691-4AC6-8AB9-D0A2C961E79C&MaxStreamingBitrate=247058823&Container=mp3%7Cmp3,aac,m4a,m4b%7Caac,flac,alac,m4a,m4b%7Calac,wav&TranscodingContainer=aac&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1596041023691&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false
jellyfin-test_1  | [16:44:05] [INF] [159] MediaBrowser.Api.Playback.MediaInfoService: User policy for nopass. EnableAudioPlaybackTranscoding: True
jellyfin-test_1  | [16:44:05] [DBG] [159] Emby.Server.Implementations.HttpServer.HttpResultFactory: Setting range response values for /media/omv-pi/media/music/Various Artists/Ben Prunty Music - FTL/Ben Prunty Music - FTL - 01 Space Cruise (Title).flac. RangeRequest: bytes=786432-38322737 Content-Length: 37536306, Content-Range: bytes 786432-38322737/38322738
jellyfin-test_1  | [16:44:06] [DBG] [95] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId=1596041023691 isUsedPaused: False
```

The device profile is identical for both devices. This test was on the same server, same network, and with the same media file.

**Comment by thornbill** [comment]
Results of testing with git bisect 10.5.5 to 10.6.0:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
93568be3e7bb653e4ddbe1e8876e36ca423c6bf3
1d86084653c1f437da04edd82a627ed02480375b
6d8ab50be9467743dff040738f08d5914e7a6cc4
5cf44e77362e0bd4d32c639457994bf22d0cf237
adb789a802438f756492326b0c036bc77d70cea1
02f6ced07ac306c2cc2857684890cebc4f84c1e9
4d9171f69196ed9335e10b3c2fffbd1c53aeff8b
fbd02a493b3284f50a70380db866be02f5226c4e
2cecde658b2bd4a97999c737005c7b06c63b8813
455e46444510bae9aeac544e9cd28735a40ce856
306f7b3c309da4d88d643d050338b0168b430a0b
3a5333228fc28c511c7a2d44ea0bc036c0474ccf
d5a924772b0b25808beb3405a041a037bbc679c8
5e1be0d4f0ac6ec4aa5f30ab617b544a38420c1a
6c2139a4c12d7ddc9d9f92d8b40a6480d0dbc209
46006a1aff5759e9843813a9d31dc79672af71d5
61e65d032ecb1d2bf614e018f4a0dd925300cfde
8a69300bf55bdf323ceabf68b2888dab3040e883
ebd589aa86abb7bdbc9ab981cb8f4c908f790ac1
43221fc26b46ac8d55b8bac7cec859dc8ec3883b
a3140f83c6461164658303d1bb7c1d992cfd9802
bb947718eaee3a8381d9b9e6ed926676de39d7c9
2aaecb8e148aef6cda67797fa4227a8ebcf7e5bb
3a5df3d06000a209e308f21cebf9aeb4c3fa9a5b
eba488a0f8d8783386f12e656d8dbd625acc557b
680dd95292504c642ad04a571437785d6e0e4d05
We cannot bisect more!
```

**Comment by thornbill** [comment]
This seems to be a combination of several issues all combined into a perfect storm.

1. Network detection appears to have been partially broken by #3007. Docker containers in bridge mode now report `IsInNetwork` as false where it previously returned true. Causing the web interface to use external network bitrate limits.

2. The maximum bitrate for iOS devices is hardcoded to `800000` in the web interface. (Maybe this is for legacy reasons? It seems to have been around since the beginning of the fork.) https://github.com/jellyfin/jellyfin-web/blob/e7180e2633a228c2f3e65616358313fa23eb5795/src/components/appRouter.js#L243-L245

3. iPads were not being identified as iOS devices in some cases. Causing them to **not** use the hardcoded value. (Fixed by https://github.com/jellyfin/jellyfin-web/pull/577)

**Comment by thornbill** [comment]
Well #4053 seems to have only fixed progressive playback. HLS streaming still appears broken, so I’m reopening this. 😐

**Comment by Schroedingers-Cat** [comment]
Playback of FLAC files is also broken on macOS 10.15.6 using Firefox 81, but works fine using Safari 14. I updated the issue's description.

**Comment by thornbill** [comment]
This should be fixed by https://github.com/jellyfin/jellyfin/pull/4384. Needs verified.

**Comment by Artiume** [comment]
is this still an issue?

**Comment by nyanmisaka** [comment]
It doesn't happen anymore on my iOS devices. I hope more iOS users can leave comments here.

**Comment by Schroedingers-Cat** [comment]
It seems to be partially fixed. I upgraded my docker image yesterday and can confirm that it's working on:
* iOS 13 iPad Pro Jellyfin app
* macOS 10.15 with Firefox and Safari

It is however still failing on iOS 13 with the iPhone SE (2020).

**Comment by nyanmisaka** [comment]
@Schroedingers-Cat 
Both direct play and transcoding to aac (manually bitrate limit) works on iOS 14.2 with the iPhone 7 Plus.

Are you using Jellyfin in local or external network?

If in external, can you set the music bitrate to a lower value to force transcoding and see it is work?

**Comment by Schroedingers-Cat** [comment]
@nyanmisaka all tests were done within my local network, the server being in the same network. Music transcoding bitrate is set to "auto". I also tried manually setting music transcoding to the lowest bitrate, bit playback still doesn't start on my iPhone SE. 

When trying to playback via Firefox on the iPhone SE, there's an error message basically stating that the client isn't compatible with the media and that the server isn't sending a compatible media format.

**Comment by nyanmisaka** [comment]
Music bitrate setting only works when you are not in local network.

Can you switch to cellular network and refresh the page and try again?

**Comment by Schroedingers-Cat** [comment]
When I do that, the app shows me the error message from the browser test above.

**Comment by nyanmisaka** [comment]
This means FLAC direct play failed. Transcoding to AAC is also failed.
Technically iPhone SE 2020 should support FLAC on iOS 13.

May I get this FLAC music?

**Comment by Schroedingers-Cat** [comment]
It fails for all my flac files, but here's something that's freely available and that's also failing on my iPhone SE 2020:
https://pepper-mint-audio.itch.io/return-of-the-tentacle-ost

**Comment by nyanmisaka** [comment]
The problem may not be the FLAC file itself.
We are all running builds newer than 20201124. The only difference could be iOS 13 vs iOS 14.

**Comment by Schroedingers-Cat** [comment]
Not sure if it's a 13 vs 14 thing because flac playback works on iOS 13 on my iPad Pro.

**Comment by nyanmisaka** [comment]
But iPad OS has better MSE support.

All my FLAC work on iPhone 7 Plus, I have run out of clues. I'll ask my friend to try on his SE 2020.

**Comment by Darkwolf1515** [comment]
iPhone 8 with ios14 and iPad os14, all flac files work for me, only audio issue I’ve experienced is .wavs stop playing when I lock the screen (in prism not Jellyfin but I felt it was worth a mention)

**Comment by Essasetic** [comment]
Just tested an iPhone 8 on iOS 14.2! FLAC files work fine (I'll see if I can test it on other devices later).

**Comment by Schroedingers-Cat** [comment]
I upgraded my iPhone SE (2020) to iOS 14.4 and the issue with flac files persists. That should rule out iOS 13vs14 as a factor contributing to this issue.

**Comment by gidoBOSSftw5731** [comment]
One of my users is on the newest iOS stable (specifics TBD) and has been streaming FLACs from my 10.6.4 server. Is this still an issue? and can't the server just transcode to wav or "close to lossless" AAC (high bitrate ofc, I dont know a ton about how AAC works by memory)

**Comment by Schroedingers-Cat** [comment]
@gidoBOSSftw5731 iOS is only one factor. The other factor seems to be hardware.
Flac streaming works fine with my iOS 13 iPad Pro Gen 2 but fails on my iPhone SE (2020). Further details are in my posts above.

If there’s any additional info I can get to find out why transcoding fails on this specific device, I’m happy to do that.

**Comment by gidoBOSSftw5731** [comment]
Alright, well the only phones I can test with are iphone 8+'s and older, while this sounds like a newer device issue, but I'll keep tuned in to see if you find a fix.

**Comment by rderensy** [comment]
> this sounds like a newer device issue

I tried on my iPhone 11 Pro and iPhone 12 and flac files work on both. I tried different sample rate and bit depth but they all work. Running Jellyfin 10.7.0 and iOS 14.4.1.

**Comment by Schroedingers-Cat** [comment]
Happy to report that playback of FLAC files now works also on my iPhone SE (2020) with the server at v10.8,1 and the Jellyfin Mobile (iOS) app at v1.5.0 (5.5.0.0) with Expo Version 43.0.0 and the iPhone SE on iOS v14.8.1.

**Comment by SirFulscht** [comment]
Still getting the same error on iPad 4th gen IOS 10.3.3 hen playing FLAC files through Safari browser.

Playback Error

This client isn't compatible with the media and the server isn't sending a compatible media format.

Tried the versions 10.8.5 and 10.8.1 and getting the same error. Unfortunately, I cannot install any IOS client because of the OS version.

**Comment by srcrist** [comment]
Original issue closed by https://github.com/jellyfin/jellyfin/pull/4384. If you are still having FLAC playback issues on iOS, please open a new issue with your specific details so we can debug it.
