### ISSUE TITLE
Jellyfin Dumps Files From Album Folders Into Playlists

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin#5030]
Not sure entirely what file, but it's most likely either CUE files, XML files, or M3U files. I'm assuming M3U.

So, on Jellyfin if I add a music folder, sorted as such
Music > Artist > Album > Music Files/Cover Art/Extra Files

Under playlists, there's a long list of albums, click and it's empty.
I'm assuming it's fetching M3U playlists within those album folders.

This is obviously not desired. It makes creating actual playlists a mess.

This could probably be solved by simply allowing a user to set a custom playlist directory, and only show stuff from that directory there? 

Edit: If I go into Jellyfin, and click on any of the "playlists", the actual contents show empty. It just shows the album name, but nothing contained in it.

**Comment by kescherCode** [comment]
It's most likely M3U files, yes. I highly dislike this behaviour as well. A setting per library for ignoring such files for playlists would be highly appreciated.

**Comment by grravity** [comment]
It could probably easily be resolved by just ignoring all .M3U files from a library, and have it create a "Playlist" directory and only read the files from there.
That "playlist" directory would be where new playlists are created, or where users can drop .m3u files they want read.

**Comment by muhlinux** [comment]
This is still an issue

**Comment by seniorm0ment** [comment]
can confirm

**Comment by tomnehek** [comment]
This is still an issue for me. I'd abandon plex immediately if Jellyfin gave the option to ignore m3u files at the library level.

**Comment by itsjustdj** [comment]
I can confirm that this is still an issue. Adding new albums automatically adds them to the Playlists library. It's clearly adding a .m3U file to each album directory when the metadata is refreshed.

Once I manually delete the .m3U file in the album and refresh, it's gone from Playlists.

It's a workaround, but it would be nice to have this issue fixed.

**Comment by Bond-009** [comment]
Please upvote this feature request if this interests you
https://features.jellyfin.org/posts/478/ignore-m3u-playlists
