### ISSUE TITLE
SyncPlay not keeping in sync at all 

### ISSUE THREAD

**Issue by voarsh2** [jellyfin/jellyfin#5557]
**Describe the bug**

SyncPlay doesn't work properly.
When playing, two people get out of sync, when one presses pause, it doesn't bring the other person in the group in line, back in sync. Trying to watch something in sync is near impossible. Better to just play at the same time with syncplay off.

**System (please complete the following information):**
 - OS: Debian,
 - Virtualization: Docker , LXC
 - Clients: Browser, Android
 - Browser: Chrome 89
 - Jellyfin Version: 10.7.0
 - Playback: Transcode
 - Installed Plugins: none
 - Storage:NFS

**To Reproduce**

1. Go to make a SyncPlay group
2. Play something with two people or more
3. Try and watch together, you'll become out of sync, pausing and playing doesn't re-sync/get the timing with the person who paused like the previous version.

**Expected behavior**
Pausing will bring both clients to the same time. Seeking different parts of show/movie will work as expected.

**Comment by voarsh2** [comment]
Related to: SyncPlay needs to be fixed/re-implemented in MPV Shim? https://github.com/jellyfin/jellyfin-meta/issues/1

**Comment by voarsh2** [comment]
I reverted to previous version and no problems. Hopefully it gets addressed in next patch.

**Comment by OancaAndrei** [comment]
While fixing another issue I'm noticing this unexpected SyncPlay behavior too. I'm pretty sure this was not a thing some months ago. Currently looking into this as well.

**Comment by voarsh2** [comment]
I think your comments describe the issues quite well.
It's hard to know if the buffering issues affectings seeking and keeping everyone at the same time, or if there's new issues as well.
In any case I'll be happy to help test this issue when fixes are made.

**Comment by OancaAndrei** [comment]
One quick note and question: are you sharing the same user across different clients/browsers?

Because I think there's a regression in how the WebSockets are handled which restricts the number of active connections per user (new connections take over the old ones and "steal" all the messages). In Jellyfin `10.6` this is not an issue.

**Comment by voarsh2** [comment]
> One quick note and question: are you sharing the same user across different clients/browsers?

I *may* have at one time opened two browsers or tab with Jellyfin with this release, but the usual SyncPlay with friend/family, both just using one session doesn't really work in this release.

**Comment by OancaAndrei** [comment]
@voarsh2, if you're still up for some testing, I've pushed a Docker build at `andreioanca/jellyfin-syncplay-preview:latest`.

My suspicion is that the underneath WebSocket connection (that provides realtime updates and syncs the playback) was dropping, for whatever reason, and upon reconnection the now-fixed issue would manifest.

Let me know how it goes.

**Comment by voarsh2** [comment]
I gave it a test - seems better. But my other SyncPlay partner complains about drop outs, and I need to pause/play/seek a bit for it to work again.
I might need to revert back to 10.6.4 again.

**Comment by ikomhoog** [comment]
>But my other SyncPlay partner complains about drop outs/freezing, and I need to pause/play/seek a bit for it to work again.

is this freezing one of the streams while the others play along fine?
I have this same issue on the main jellyfin docker image.
Maybe the logs in my ticket will help: https://github.com/jellyfin/jellyfin/issues/5619

@OancaAndrei I have syncplay parties fairly often so can help test if you think you found something.

**Comment by Vitorvlv** [comment]
I'm still having issues with SyncPlay losing sync, or not even having to begin with, the issues on #5619 also happens sometimes.  It seems to have gotten worse recently for some reason, I'm on 10.7.7

Is #5648 supposed to be the definitive fix? Unfortunately the docker build provided by OancaAndrei didn't worked for me, so I wasn't able to test the changes.

I'm mainly sending the bot away. Since I have almost daily SyncPlay sessions, I'll come back with some logs next time it happens.

**Comment by OancaAndrei** [comment]
@Vitorvlv, if not definitive (probably not haha) at least it should help into making other issues more obvious.

Did any problem in particular arise while trying the Docker image? Also, did you try it recently? Because I'm afraid it might be a bit outdated now (5 months old).
