### ISSUE TITLE
Multi disc music albums are displayed as separate albums

### ISSUE THREAD

**Issue by RedKong** [jellyfin/jellyfin#5605]
The expected and correct behavior would be a single album, that lists all tracks, separated in different sections by the "Disc #" line.

The "Disc #" line is already present, but useless.
Moreover, the "albums" appear in random order in the standard A-Z sorting.

Images below are current state.
![smxqkh83jpy31](https://user-images.githubusercontent.com/52454506/112241576-d1303c80-8c4a-11eb-8912-8531cb26d631.png)
 
This is the first in the image above, note that it is Disc 3 (the following is number 8, it's random)
![smxqkh8wew3jpy31](https://user-images.githubusercontent.com/52454506/112241817-050b6200-8c4b-11eb-9ace-628d2ecc7cf4.png)

**Comment by dkanada** [comment]
Album detection is mostly folder based so if you move them all to the same folder it should work.

**Comment by RedKong** [comment]
> Album detection is mostly folder based so if you move them all to the same folder it should work.

I see, thanks for the answer.

So changing the folder structure of my entire library where multi disc albums appear would be the only work-around in this case?

I still consider this a bug, every other music player/library manager that I have ever used  (from Winamp, to Emby, to Samsung music, etc. etc...)  does not work like this but uses the "ALBUM" tag, not the folder structure.
Especially Emby, which I thought would be the behavior inherited by Jellyfin.

If this somehow not considered a bug then I guess I should make this a feature request.

**Comment by Zunawe** [comment]
It used to be the case that separate directories for each disc in a single album would be detected correctly. Not sure how it got changed. [The Jellyfin docs even still recommend this folder structure.](https://jellyfin.org/docs/general/server/media/music.html#discs)

**Comment by cvium** [comment]
@RedKong Is your music library in Jellyfin set to `Music/OST` or just `Music`? I can only replicate the behaviour with the former, which does not adhere to the recommendation.

**Comment by RedKong** [comment]
If you mean this, then it's `Music/OST` 
![image](https://user-images.githubusercontent.com/52454506/113922558-b8498e80-97e7-11eb-9247-548944fbd60f.png)


I have been using these settings since Emby (long before actually), without any problems, I wasn't aware the recommendation were against this.
(https://jellyfin.org/docs/general/server/media/music.html#discs other than the "artist" folder, which I strongly dislike from an organizational point of view, this looks fine to me)

If I were to set the library path to `Music` wouldn't it include other stuff I have inside that folder? Which I don't want in the same library in Jellyfin.

**Comment by cvium** [comment]
> If I were to set the library path to `Music` wouldn't it include other stuff I have inside that folder? Which I don't want in the same library in Jellyfin.

Yes it would.

I did some more digging and it looks like your setup worked before 10.7, but another bug was fixed in 10.7, which "broke" your setup: https://github.com/jellyfin/jellyfin/pull/4968

The problem is that your folder structure was never officially supported, so I'm not sure how to proceed from here.

**Comment by Zunawe** [comment]
I'm in the same boat. My library is set up like this:
```
/Music
    /Album
        /Disc 1
            01 - Song.mp3
            02 - Song.mp3
        /Disc 2
            01 - Song.mp3
            02 - Song.mp3
```
with no separation by artist. Lots of my albums are the only album in my library from that artist and some albums are collaborations between a couple artists with their own individual albums, so it only makes the organization sloppier and more confusing to separate albums by artist. Not to mention albums created by "various artists".

**Comment by RedKong** [comment]
@cvium When you said:

> [...] set to `Music/OST` or just `Music`? I can only replicate the behaviour with the former

Do you mean that if you set the library to the latter, a direct sub-folder of root, then you see the albums/discs displayed correctly even with my folder structure?
I tried to create a library set to `F/Test`, put inside it a multi-disc album and the bug is still there for me. 
Also noticed another bug, under the artist view I see double the number of albums, still in random order:
![image](https://user-images.githubusercontent.com/52454506/113946942-cad4bf80-9809-11eb-9e59-972a28629fb4.png)
16 "albums" instead of 8 (well, of course it should be just 1)


________
Regarding the fact that it was never officially supported, it looks to me like it was, according to the documentation.
It is also still linked in the media library creation process, it takes you to the link I posted before.
![image](https://user-images.githubusercontent.com/52454506/113946774-7a5d6200-9809-11eb-94ae-11d3e4d1153f.png)
Is the missing "Artist" folder the problem?

@Zunawe I saw your reply while I was typing. I have the same opinion, in this case organizing by artists is **extremely** inconvenient, to say the least.
_______
What would the recommended folder structure look like? Flat inside the album folder with no "Disc" folder?
If that's the case, I say again that is not desirable and also not needed by a single other program that I know of.

**Comment by nsonnad** [comment]
Chiming in to say that I'm having the same issue and that something has definitely changed here. Since upgrading to 10.7 the folder structure of `Album/Disc X` no longer displays multi-disc albums as a single entity, rather splits each one out into its own thing. Which is very inconvenient, and it definitely used to display on a single page. (I'm sure of it as I've been collecting lots of anthologies lately.) My music is in a beets library so it's easy enough to change the folder structure around, but I do have a personal preference for having each disc in a separate folder, and as mentioned that is officially mentioned in the docs.

**Comment by RedKong** [comment]
I made a new folder in explorer F:\temp\Artists
Then I created a test library pointed to F:\temp and it seems to work correctly.

If I take an album out of \Artists and put it into the above \temp then the bug appears again.

![image](https://user-images.githubusercontent.com/52454506/114591641-65118900-9c8a-11eb-853b-52083be651b2.png)
The first two albums exhibit the bug and are in \temp, the other two do not and are in \temp\Artists.

Looking at this difference in behaviour I guess that the the work-around is to not point the library directly to where the album folders are located (the dummy "Artsits" folder name should not matter, right?).

I don't know if this is the right place to ask, but is there a way to now re-point my original library to a different path that includes the dummy "artists" folder without needing to rescan everything?

To make it clearer, now the library is pointed to F:\Music\OST and all the album folders are there as well
in explorer I make a new folder F:\Music\OST\Artists\
I move all the album folders from \OST to \OST\Artist

Do I really have to rescan? Can't I migrate or something similar?

**Comment by RedKong** [comment]
Just to confirm the efficacy of the work-around method, which I have tested over my entire library and can confirm it to be working normally. I would add the work-around tag but I don't know how.

To summarize, you must not point the library directly to the folder where the multi discs albums are located, point it to one folder level above. 
There is no need to have the albums categorized by artists as stated in the documentation (documentation which, as discussed in this thread, apparently was and now still is outdated/wrong)

![image](https://user-images.githubusercontent.com/52454506/116610000-51764b80-a935-11eb-8a6e-7134d889c565.png)

![image](https://user-images.githubusercontent.com/52454506/116610029-59ce8680-a935-11eb-8412-64d74cef1b1a.png)


![image](https://user-images.githubusercontent.com/52454506/116610067-6652df00-a935-11eb-91f3-e9daeb56f01c.png)

![image](https://user-images.githubusercontent.com/52454506/116610137-779beb80-a935-11eb-820d-9694d082c4ba.png)

![image](https://user-images.githubusercontent.com/52454506/116610122-72d73780-a935-11eb-81bd-5f1189b336e0.png)

**Comment by Zunawe** [comment]
The docs _might_ be misleading by leaving it ambiguous whether the name of the artist folder _must_ match the tags of the music in that folder, but I wouldn't necessarily argue that they're wrong. I don't think there's much reason to update the docs.

However, I'll advocate that this get turned into an enhancement. Obviously there are Jellyfin users for which the artist folders are inconvenient, and the fact that the solution is to create a dummy folder just to have an extra node in the tree I think is a good indicator that something needs to be improved.

**Comment by Kurozeto** [comment]
Two features that could be added are the ability to add a disc number to the metadata, and a merge feature in the event that album recognition fails. This is something that Plex has implemented and allows for more control over the library's structure.

**Comment by Zunawe** [comment]
Songs already have a disc number metadata field, and Jellyfin already acknowledges it and lets you edit it from the web UI. Jellyfin doesn't seem to do anything to try to group albums based on metadata, which I think makes sense. You're not guaranteed two albums with the same name are the same album. Or even two albums with the same name by the same artist. Better to rely on folder structure because it's a more explicit separation of albums.

Merging might also already exist. If you select two albums in the web UI and click the three dots, there's an option to "Group versions". I don't want to actually click the button in case it's hard to reverse.

And even so, as some random user, I'd still rather have my library's format be detected automatically without having to group every multidisc album via the UI.

**Comment by Kurozeto** [comment]
It didn't occur to me that the disc label was at the song level and not the disc level.

In that matter, I've gone ahead and performed the experiment on a 3-Disc album.
First by individually labeling each song with their appropriate disc, and then attempting to merge them into a single album with the "Group Versions" option.

The conclusion is that the "Group Versions" option does not merge individual discs into a single album. Even after refreshing the metadata on the library, there is no change to the structure.

**Comment by Tau5** [comment]
I can also confirm that this continues being an issue

**Comment by ClementNerma** [comment]
For info this is still an issue after the latest update.

**Comment by LinAGKar** [comment]
>Album detection is mostly folder based so if you move them all to the same folder it should work.

Why? Albums are set in a tag in the files, the folder structure should be completely ignored.

**Comment by Zunawe** [comment]
For a quick plausible counterexample, two performances of Beethoven's 5th symphony might be given the same "album" title in the tags. They may even be given the same album title and be published in the same year.

There are plenty of edge cases where you would want to distinguish albums based on which folder they're in rather than tags in the metadata.

However I still think being _required_ to separate by artist is annoying and extraneous.

**Comment by LinAGKar** [comment]
>two performances of Beethoven's 5th symphony might be given the same "album" title in the tags. They may even be given the same album title and be published in the same year.

In that case you would probably need to add some qualifier to the album name, or they would be indistinguishable anyway.

**Comment by Morgan-6Freedom** [comment]
I manage to make it almost working :
Instead of :


```
/Music
    /Album
        /Disc 1
            01 - Song.mp3
            02 - Song.mp3
        /Disc 2
            01 - Song.mp3
            02 - Song.mp3         
```
I did :
```
/Music
    /Album
        1.01 - Song.mp3
        1.02 - Song.mp3
        2.01 - Song.mp3
        2.02 - Song.mp3
```



![image](https://user-images.githubusercontent.com/49686866/186639724-c16b0b5d-125b-482b-bbeb-0e80dc46bd77.png)


But the thing is that Jellyfin show me 9 albums :
- one is the 180 track album
- the 8 discs as albums

![image](https://user-images.githubusercontent.com/49686866/186639814-315c0ba6-4e7b-42a5-96d0-b054bd56406c.png)

**Comment by Fangh** [comment]
I manage to make it almost working :
Instead of :


```
/Music
    /Album
        /Disc 1
            01 - Song.mp3
            02 - Song.mp3
        /Disc 2
            01 - Song.mp3
            02 - Song.mp3         
```
I did :
```
/Music
    /Album
        1.01 - Song.mp3
        1.02 - Song.mp3
        2.01 - Song.mp3
        2.02 - Song.mp3
```



![image](https://user-images.githubusercontent.com/49686866/186639724-c16b0b5d-125b-482b-bbeb-0e80dc46bd77.png)


But the thing is that Jellyfin show me 9 albums :
- one is the 180 track album
- the 8 discs as albums

![image](https://user-images.githubusercontent.com/49686866/186639814-315c0ba6-4e7b-42a5-96d0-b054bd56406c.png)

**Comment by RedKong** [comment]
I think the workaround I posted above https://github.com/jellyfin/jellyfin/issues/5605#issuecomment-829556447
 is still the best (the only, in fact) way to have this functionality work as it should.

With the latest updates however, another thing has broken, now all the multi discs album don't have a cover in the library view.

If I remove one layer from the library path (the layer needed to make jellyfin correctly identify multi album discs), then the covers do appear...

![image](https://user-images.githubusercontent.com/52454506/190712811-211fa5f4-79a8-41f8-87f5-84406f92b87b.png)


along with the same old bug of every disc appearing as a separate album

**Comment by RedKong** [comment]
Version 10.8.5
Same behaviour, the bug is still present.

**Comment by interdependence** [comment]
I can also confirm this is still present in 10.8.5

**Comment by cvium** [comment]
You don't have to bump this on every release. If/when this will be fixed, this issue will be closed.

**Comment by trentks** [comment]
Just adding to this issue, I think structuring your folders to have "Disc" is pretty acceptable. But this work-around fails when the "disc type" is "Digital Media" (ie instead of a folder being "Disc 1"/"CD 1"/"Disk 1", all of which works, it's "Digital Media 1")

A lot of music is released digitally, and this is an increasingly popular term for splitting (which lidarr correctly accounts for), I've submitted a pull request #8713 to address this.

**Comment by nodecentral** [comment]
Just adding to this thread to show my support for this being fixed, and there being clear guidance on how muti-disc albums are handled with Jellyfin.

Also when Jellyfin takes a 3 disc album, and separates it into 3 seperate albums, how best do I get the three updated to one again? Do I delete and refresh the whole metadata, or is there a way I can just focus on that one album ?

**Comment by RedKong** [comment]
> Just adding to this thread to show my support for this being fixed, and there being clear guidance on how muti-disc albums are handled with Jellyfin.
> 
> Quick Question: When Jellyfin does take a 3 disc album and separates it into 3 seperate albums, how best do I get the three updated to one again? Do I delete and refresh the whole metadata, or is there a way I can just focus on that one album ?

"To get the three updated again", do you mean refreshing after having applied the work-around? I think it is sufficient to remove the folder, scan for new, work-around and then scan again.

I have a question too, is anyone else having the problem of the missing artwork images, the ones obtained by jellyfin with "image extractor", affecting exclusively every multi-disc albums in the library?

**Comment by nodecentral** [comment]
Hi @RedKong 

> I think it is sufficient to remove the folder, scan for new, work-around and then scan again.

Forgive what might seem to be an obvious question, but what do you mean when you say ‘remove the folder’ ?  How do I do that, as the UI only gives me the option to Delete, which will remove it from the file system and my media library ?

**Comment by RedKong** [comment]
> 

forgive me, you are right I wasn't clear.
You are right, delete will remove it from the disk.
I meant moving the folder out of jellyfin's library folder path.

Let's say you have your library set to C:\Music\, move the album folder out of \Music\, as far as Jellyfin is concerned the album has been deleted.
Scan to update jellyfin's database, move the folder back inside \Music\, scan again.

But if you only renamed the subfolders to Disc#, then I think it's not enough, they will show up as 3 separate albums.

Best workaround now, as discussed here, seems to be adding a layer inside the library path.
So if your library is pointing to C:\Music, you would create a new folder C:\Music\test (name doesn't matter)
And then move all your album folders inside \test, without changin anything in Jellyfin.

This way disc detection works as it should... but then the "image extractor" for the album covers breaks.

**Comment by nodecentral** [comment]
Thanks @RedKong 

FYI - The original hierarchy of all my music _was_ as follows…

C:\Music
C:\Music\Album Name
C:\Music\Album Name\ Album Name - Disc 1
C:\Music\Album Name\ Album Name - Disc 2

So I have updated the disc subfolders to the following ..

C:\Music
C:\Music\Album Name
C:\Music\Album Name\Disc 1
C:\Music\Album Name\Disc 2

**Comment by RedKong** [comment]
And does that work correctly?

If your library is pointing to `C:\Music` then if I got this right it should be affected by this bug, so you would see two albums with the sama name in Jellyfin, instead of one containing two discs.

If that is the case, you can try leaving the library in Jellyfin as it is, pointed to `C:\Music`
then creating a folder `C:\Music\*whatever_you_want*\`
and move all your album folders inside:
```
C:\Music\*whatever_you_want*\Album Name A
C:\Music\*whatever_you_want*\Album Name B\Disc 1
C:\Music\*whatever_you_want*\Album Name B\Disc 2
```

This should work.

**Comment by nodecentral** [comment]
> And does that work correctly?

No, it seems it doesn’t; the `Disc 1` , `Disc 2` route e.g. under `\Music\Album Name\Disc 2` did not work for me..

I’ll try your suggestion e.g. `\Music\JellyfinBug\Album Name\Disc 2` and report back…

**Comment by nodecentral** [comment]
@RedKong  - the alternative approach, adding another subfolder i.e. `\Music\JellyfinBug\Album Name\Disc 2 ` didn’t work either..

**Comment by RedKong** [comment]
Either the workaround isn't as good as I thought or I have given you the wrong instructions, I'll try to replicate it now.

- This is the folder structure:
![image](https://user-images.githubusercontent.com/52454506/204387429-2414f672-5699-494e-90bc-fe766e269ff8.png)

![image](https://user-images.githubusercontent.com/52454506/204387556-bbdf934c-260c-4240-a656-9ed9bdbd1116.png)

![image](https://user-images.githubusercontent.com/52454506/204387596-d7f8dff0-177f-40bb-81ed-e8988d49fc95.png)

- This is the Jellyfin library setting, which I will not change at any point:
**ALL the settings are unchecked**, save for "Image Extractor"
![image](https://user-images.githubusercontent.com/52454506/204387756-77da18b9-2c84-445a-a413-6fab312fcd5a.png)

After Jellyfin has finished scanning the library, I get this:
**_The bug shows up here_**, two "albums", which are in fact Disc 1 and Disc 2
![image](https://user-images.githubusercontent.com/52454506/204387944-a9107daa-6ac9-49cd-995f-4079e47e6fcb.png)



- Now, I change the folder structure as I suggested above, I add another folder in between the albums and the root of the library and move my albums there:
![image](https://user-images.githubusercontent.com/52454506/204388255-630b2532-7121-47ce-a275-5f66c4cd62ce.png)

![image](https://user-images.githubusercontent.com/52454506/204388307-de40f0ec-0f73-479b-99ae-5c6f0af16671.png)

- I hit refresh metadata in Jellyfin
![image](https://user-images.githubusercontent.com/52454506/204388375-df32feb4-47ae-46db-91cb-bd959ed08d5b.png)


- I get the correct and expected behaviour, a single album that contains the two discs
![image](https://user-images.githubusercontent.com/52454506/204388929-717c7a03-8820-4846-92a8-473e34379ede.png)

![image](https://user-images.githubusercontent.com/52454506/204389110-7679f5b2-e088-421b-90a2-d5482f29984b.png)

![image](https://user-images.githubusercontent.com/52454506/204389134-08a9d148-07b1-4d3e-aeee-e69451b7933e.png)


Now, the workaround seems to be functioning ok on my end, I am not sure what could be difference on your configuration.

Also, as I have mentioned and as everyone can see in the screenshots, this breaks the image extractor and I get a blank image for the album cover.
Note that the tracks do have the correct cover when played.

**Comment by nodecentral** [comment]
Hi @RedKong.

Thanks for that, and if I’ve understood you correctly - you’re suggesting I add another layer (subfolder), which places the `Disco folders at the 5th level from the top folder chosen in Jellyfin  ??

Original = Creates duplicates =  `\Music\Album Name\Disc 2 `
Alternative 1 = Creates duplicates =  `\Music\JellyfinBug\Album Name\Disc 2 `
Alternative 2 = Should Work ?? =  `\Music\JellyfinBug\AnotherFolder\Album Name\Disc 2 `

**Comment by Zunawe** [comment]
I think you've been confused because they created a test folder in which they tried to reproduce your problem. You'll notice in their config they have their music library set to a folder named `test`.

What's happening here is that Jellyfin expects albums to be in subdirectories containing the names of artists. `Music/Artist/Album/Disc 1/Song.mp3`. And the workaround we've found here is to create a single folder at the `Artist` level to hold ever album in the library. That folder's name is inconsequential.

If you're following that practice and seeing a different issue, I'm not sure what would cause that.

**Comment by RedKong** [comment]
Zunawe is exactly correct, I apologize for my poor explanation.

I am just reiterating here, or summarising:

- If the current implementation is intended, it is not consistent. If it is supposed to be folder based then the "albums" should be called Disc 1 and Disc 2; instead the title is extracted from tags.
The required /$artist/ folder is completely ignored too, save for its presence, to the extent that we are literally naming it /jellyfinbug/ here.


- More fundamentally, for what purpose would one organise their library with thousands of "artists" folders, of which the vast majority would end up contain a single album. This is redudant, and adds nothing if not more unnecessary complexity.
(On a colleague's computer I have seen an endless list of folders, each named month-day-year, and each containing a single file which has that same date as the filename. All this done by hand. The current jellyfin implementation weirdly reminds me of that act of utter brilliance.)

- Let's say I want to navigate the folder structure and copy all the Metal Gear albums. As it is I have them right there, in alphabetical order, instead of how many artists folders scattered all over the place.

- How would multi-artists albums work? An ugly and comparatively un-organized "Various Artists" or "Misc" folder that ends up containing the largest number of albums, which have nothing in common with one another as far as artists are concerned.
This **intented** behaviour is eerily similar to the /jellyfinbug/ dummy folder.

Or rather, a different folder for every single combination of artists? Just one musician might appear on 10 different albums collaborating with 10 different sets of artists, how many combinations of useless folders would that result in, fracturing series and common-theme music and making it unreasonably difficult to navigate the library.

And if that is not enough (but it is), maintaining such a library would be a nightmare.

- I can only speak for myself here, but every single other program I have ever used doesn't require this weird /artist/ folder.
This includes Emby, and even more importantly, Jellyfin itself, which just worked as expected, so this is a regression.

The solution to all of this is, in principle I mean, very simple: tags.

**Comment by nodecentral** [comment]
Having recently gone down the route of digitising all my paper documents into paperless-ngx, I’ve started to become less concerned about the underlying folder/file structure, as my focus has started to shift much more towards the UI and the options that gives me. (And I’m also seeing the value of tags)

With that being said, I have also started to explore beets as a way to validate and update my extensive music library , and in doing that, it’s converting my library to that very same `artist` and `compilation` structure. And having just mapped Jellyfin to the beets music folder and what’s been transferred/converted so far, everything appears in the UI exactly as it should. (It’s unfortunate jelly fin can’t have done that itself)

**Comment by erri120** [comment]
> The solution to all of this is, in principle I mean, very simple: tags.

Tagging has also been made extremely easy with tools like [Picard](https://picard.musicbrainz.org/), which adds all the information you'll ever need:

```mediainfo
General
Album                       : The Sacrament of Sin
Album/Performer             : Powerwolf
Part                        : 2
Part/Total                  : 2
Track name                  : Sacred & Wild
Track name/Position         : 1
Track name/Total            : 10
Performer                   : Epica
Label                       : Napalm Records
Genre                       : Heavy Metal
Recorded date               : 2018-07-20
ISRC                        : ATN261878317
MUSICBRAINZ_RELEASEGROUPID  : 7b757ff3-5bbd-4f1c-83ef-6970ba01d202
ORIGINALDATE                : 2018-07-20
ORIGINALYEAR                : 2018
RELEASETYPE                 : album
RELEASESTATUS               : official
ASIN                        : B07CYZRDW8
SCRIPT                      : Latn
CATALOGNUMBER               : NPR 783 SC
RELEASECOUNTRY              : DE
ALBUMARTISTSORT             : Powerwolf
BARCODE                     : 840588117338
MEDIA                       : CD
DISCSUBTITLE                : Communio Lupatum
ARTISTSORT                  : Epica
ARTISTS                     : Epica
MUSICBRAINZ_RELEASETRACKID  : 68d4b566-de97-4256-989d-e753de0d9bb7
ACOUSTID_ID                 : 831ba158-8448-468b-843c-ffa46a509e97
```

**Comment by NovaCyntax** [comment]
> You don't have to bump this on every release. If/when this will be fixed, this issue will be closed.
Music has not been a primary focus for Jellyfin devs for years due to database rewrites and major under the hood changes. Discussing peripheral issues such as this is ultimately a symptom of that.

**Comment by Shadowghost** [comment]
Since I dug into the music scanning code some time ago and fixed some of the tagging issues, here are some thoughts:

* Not everyone has clean tags and if you like it or not this is still the majority of people
* File system layout is parsed before anything else, so you NEED to adhere to it, removing this or making it more dynamic requires a lot of work which currently nobody is up to do
* Current master properly support multiple (album) artists and properly adds them from the tags, same for other metadata.
* Tag based metadata is limited by what the used libraries universally expose for all tag types (e.g. id3, ape, flac metadata, ...), adding more is a chore nobody's currently willing to dump time into.

**Comment by LimeHunter7** [comment]
Commenting to say that Jellyfin does not understand
```
/Music
    /Artist
        /Album Title
            /Album Title Disc 1
                01 - Song.mp3
                02 - Song.mp3
            /Album Title Disc 2
                01 - Song.mp3
                02 - Song.mp3
```
to be a single album even if the metadata match and have disc numbers, but renaming the album folders to just be `Disc 1`, `Disc 2` etc. and rescanning fixes it.

**Comment by mfsiii** [comment]
> Commenting to say that Jellyfin does not understand
> 
> ```
> /Music
>     /Artist
>         /Album Title
>             /Album Title Disc 1
>                 01 - Song.mp3
>                 02 - Song.mp3
>             /Album Title Disc 2
>                 01 - Song.mp3
>                 02 - Song.mp3
> ```
> 
> to be a single album even if the metadata match and have disc numbers, but renaming the album folders to just be `Disc 1`, `Disc 2` etc. and rescanning fixes it.

Exactly, having a single album with "Disk 1" and "Disk 2" worked for me and they structure you listed resulted in 2 separate albums. Just to be clear this worked:

 /Music
     /Artist
         /Album Title
             /Disc 1
                 01 - Song.mp3
                 02 - Song.mp3
             /Disc 2
                 01 - Song.mp3
                 02 - Song.mp3

I did use MP3Tag to make sure the disk numbers were in the tags and correct.

**Comment by elendil7** [comment]
I believe jellyfin should add alternatives to the "Disc 1" "Disc 2" folder structure, such as "CD_1", "CD_2", and allow these alternative names to automatically be detected by jellyfin. Because some people use underscores in their directory names, or alternative folder name to "Disc". Additionally, changing directory name would mean having to re-backup all files, for those who perform backups of their media library.

**Comment by DavidCWGA** [comment]
I'm commenting here because I have a similar but related problem, but I think it's basically the same issue.

My music library looks like this:

```
/Artist
	/Album Title
		/01 Disc Name
		/02 Disc Name
```

and so on. They don't have "Disc" or "CD" prefixes.

I have thousands of albums so I really don't want to restructure my entire library. The tags in the files already contain the album name and the disc number (and the MusicBrainz UUIDs) so is there any way to get Jellyfin to ignore the directory structure entirely and just read the tags? It feels like that would solve most of the problems in this bug.

**Comment by Shadowghost** [comment]
The problem with the tag approach is that tags are notoriously unreliable if not properly curated on all files. That's why we're currently relying on folder structure this much.
The scanner in itself isn't really intelligent in that regard. Adding more possible disc directory names shouldn't be an issue as a temporary fix.

**Comment by DavidCWGA** [comment]
Could this be an option? My tags *are* properly curated in all files, so I'd love for there to be an option in the scanner that says "just trust the files". It could be off by default.

**Comment by KodeToad** [comment]
Following the current multi cd naming convention recommended now for cds that don't have cd number embedded, results in problems too. It looks like a single album with multiple tracks numbers the same.
![jellyfin 3cd metadata](https://github.com/jellyfin/jellyfin/assets/3880336/18c64adb-fd2c-4f0c-971e-4e5c8a0a725a)

Disc 1 Track 1 - Name A.mp3
Disc 1 Track 2 - Name B.mp3
Disc 2 Track 1 - Name C.mp3
Disc 2 Track 2 - Name D.mp3
...

If the track metadata doesn't exist embedded in the track, can't it be scrapped from the names, otherwise, what's the point in the naming convention?

**Comment by felix920506** [comment]
@KodeToad It states that discs are identified by their metadata in the documentation. https://jellyfin.org/docs/general/server/media/music#discs

**Comment by KodeToad** [comment]
> It states that discs are identified by their metadata in the documentation.
It also state "If no other metadata was found, Jellyfin uses the file names as track titles."
In this case there is no embedded metadata for the cd number but it is in the filename.

**Comment by felix920506** [comment]
Nothing in that page says JF uses file names to identify disc numbers

**Comment by Shadowghost** [comment]
We don't parse file names at all. The line in the docs means that we use the filename as title if metadata does not provide a title.

**Comment by KodeToad** [comment]
> If you want proper multi disc, use the proper file structure:

So I changed it as you suggested and it's even worse. Nothing has changed except now the embedded track metadata isn't used either.

**Comment by amasover** [comment]
Not sure if this is related, but I had an album that was already in the structure:

```
Artist
|- Album
   |- Disc 1
      |- Foo.mp3
   |- Disc 2
      |- Bar.mp3
```

But there was no disk metadata existing in the files. It would be really nice if Jellyfin could check the folder structure against the metadata provider and figure out that it's a multidisk album so that I don't have to add it manually. In this case, the provider had information about multiple disks:

https://musicbrainz.org/release/da1e19d2-be13-47e9-b7ce-026582923a2b

**Comment by V4ler1an** [comment]
> For a quick plausible counterexample, two performances of Beethoven's 5th symphony might be given the same "album" title in the tags. They may even be given the same album title and be published in the same year.
> 
> There are plenty of edge cases where you would want to distinguish albums based on which folder they're in rather than tags in the metadata.
> 
> However I still think being _required_ to separate by artist is annoying and extraneous.

I disagree entirely. If you're giving two albums the same title metadata you're just going to make it confusing for yourself when the media manager's UI shows them with the same name. How is that a good user experience? If the media manager is displaying album titles from tags (as they all do), then re-tag your albums with unique names. E.g. in your example, my tagging would be - Album Artist: Beethoven, Album Name (title): Beethoven's 5th Symphony - Performance 1... Performance 2 etc. Now they show as distinct in the UI. Media managers never display albums using folder names the files live in. So by trying to group discs into albums by folder structure you're mixing two systems, folder organisation and ID3 tag metadata organisation. Which creates confusion. Also, there are loads of great tools for quickly re-tagging music files. Conversely, re-organising the folder structure is cumbersome and difficult. Metadata should always be king! The fact that some people like to organise their folder structure by artist is just file system organisation preference. It should never have any impact on what a media manager does.

**Comment by KodeToad** [comment]
> There are loads of great tools for quickly re-tagging music files.
Some files must remain intact.
If the metadata isn't complete and the directory structure exists, use that.

**Comment by geriko2000** [comment]
Same issue

```
Artist
|- Album
   |- Disc 1
      |- Foo.mp3
   |- Disc 2
      |- Bar.mp3
```

Not works

**Comment by V4ler1an** [comment]
IMO embedded tag metadata grouping should be king, (Disc # etc...) but this seems to conflict with JellyFin's design which favours folder structure in certain instances. Like you, I found that the disc folders didn't work no matter what I called them (CD 1, Disc 1 etc...).

Regardless of this, I suggest the developers add a configuration option to JellyFin for those who are messy and don't assign correct tag metadata to their tracks: 'Prioritise folder structure for: Disc #, Artist, whatever...'). Then the people who want purely metadata governed grouping can turn these options off.

Trying to cater for both approaches causes confusion and it doesn't work well. Other media managers i've used ignore folders and defaults to grouping discs and albums by metadata. I hope JellyFin will get onboard. Migrating my music to JellyFin was a total mess and I abandoned it in the end.

**Comment by dvanmatre** [comment]
Like @amasover I'm using the recommended file structure. I don't use a disc number tag. I use album, artist, genre, title, track, year. With no disc number tag I end up with the same result as @KodeToad where disc 2 get lumped in with disc 1. 
```
Artist
|- Album
   |- Disc 1
      |- Track11.mp3
   |- Disc 2
      |- Track21.mp3
```
```
+---Pink Floyd
|   +---The Wall
|   |   +---Disc 1
|   |   |       07 - Goodbye Blue Sky - Pink Floyd The Wall (Disc 1).mp3
|   |   \---Disc 2
|   |           02 - Is There Anybody Out There - Pink Floyd The Wall (Disc 2).mp3
```
I would expect the same behavior as everything else where I end up with two albums from the same artist, one called Pink Floyd The Wall (Disc 1) and one called Pink Floyd The Wall (Disc 2).

**Comment by KodeToad** [comment]
There's a neat feature for series which allows them to be displayed in different order by changing the Jellyfin "Display order" metadata. That would be a nice option

**Comment by itsmistermoon** [comment]
So far the best results I've had were by just putting every disc in the same folder and naming the files by putting the album number at the start, like `1-01 - [song name1].m4a` and `2-01 - [song name 2].m4a`.

Not ideal at all, but it solves the issue until an official, proper fix is implemented.

**Comment by OnyxGhub** [comment]
Hello. I just wanted to chime in to state that this is most definitely a bug that needs to be fixed. Tracks for an album should be grouped together based on the combination of "Album Artist" & "Album" audio file tag values, and the file/folder naming structure should be a fallback method ONLY when the two metadata tags above are missing from the files. All of my multi-disc albums are organized where the tracks for each disc are separated into Disc folders. So my folder structure is "`<root folder> \ <Album Artist> \ <Album> \ tracks`" for non multi-disc albums, and  "`<root folder> \ <Album Artist> \ <Album> \ <Disc Name/Number> \ tracks`" for multi-disc albums. This naming structure works for me in all other applications I utilize (MediaMonkey, Kodi & Plex) regarding what track album grouping is based on: the combination of "Album Artist" & "Album" audio file tag values.
I'd prefer to migrate my daily usage from Plex to Jellyfin once core issues such as this get fixed. Thus hopefully this bug will get fixed soon.

Thanks for the great work put into Jellyfin thus far.

**Comment by blaisebrennan** [comment]
Chiming in once more, like @OnyxGhub I am still having this issue. What makes it especially frustrating is Lidarr will group items exactly this way, then I have to go manually rename and move files to flatten them so Jellyfin is happy.

**Comment by dinugr** [comment]
i had the same issue and fixed after follows the [latest docs](https://jellyfin.org/docs/general/server/media/music/#discs), by adding `disc number` each track (.m4a in my case) with matching `Album`, and `Album Artist` tag.

> Albums with several discs are identified by the metadata tags with the `disc number` and `total discs` fields. Place the tracks for all discs in one folder. They can optionally be separated into disc folders, but embedded metadata takes priority.

<img width="1024" height="582" alt="Image" src="https://github.com/user-attachments/assets/55b2e4ce-8106-46f2-8f52-9bcc6f260564" />

**Comment by darkdragon-001** [comment]
@dinugr Your comment made me investigate this further on my instance. I found some tracks which are displayed correctly and others which are not.

I investigated further and identified the following differences:

Working: ID3 version 2.4.0, field TPOS
Not working: ID3 version 2.2.0, field TPA

When checking the metadata in Jellyfin, the disk number is not shown in the TPA case.

I double-checked that the same mp3 files are parsed correctly by TagLibSharp and ensured their source code converts TPA fields correctly to TPOS ones: https://github.com/mono/taglib-sharp/blob/TaglibSharp-2.3.0.0/src/TaglibSharp/Id3v2/FrameHeader.cs#L423

So I manually triggered "Refresh metadata" with "Replace all metadata" on this album and indeed this fixed disc number reporting.

Edit: Running a rescan of my whole music library now. Note #15573, there is currently no progress bar shown when rescanning a single library.

**Comment by OnyxGhub** [comment]
@darkdragon-001 This is a great observation, yet I assume that the working ID3v2.4.0 standard versus the non-working ID3v2.2.0 standard only applies to MP3 files. Thus this bug is still a wider spread issue since it doesn't address issues where the disk number tag is already present in M4A and FLAC files. Is that correct?

**Comment by darkdragon-001** [comment]
> Thus this bug is still a wider spread issue since it it doesn't address issues where disk number tag is already present in M4A and FLAC files. Is that correct?

@OnyxGhub I personally only use MP3 files.
