### ISSUE TITLE
Subtitles not working properly for DVD source

### ISSUE THREAD

**Issue by T4NNh4u53r** [jellyfin/jellyfin#6098]
**Describe the bug**
After updating to Jellyfin v10.7.0, subtitles won't show for MKV-files that are copied from DVD. The only instance where it works, is when choosing the quality to be "480p - 3 Mbps". Even then the subtitles are displayed a bit to the left, but that was also an issue in v10.6.0. Even though the subtitles was displayed a bit to the left, they were always present in v10.6.0. From this experience with the issue, it seems to be a resolution problem when playing through different clients (Browser, Android and Chromecast), but I'm not sure.

**Video details**
Video codec: MPEG2
Video resolution: 720x576
Subtitle codec: DVDSUB

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2.0 LTS
 - Clients: Browser, Android and Chromecast
 - Browser: Firefox 88.0.1 (64-bit)
 - Jellyfin Version: 10.7.5
 - Playback: Transcode
 - Installed Plugins: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Copy DVD with MakeMKV
2. Play the MKV-file in Jellyfin
3. Choose a subtitle from the MKV-file

**Expected behavior**
I expect the subtitles to be shown in the lower center of the screen.

**Screenshots**
<a href="https://imgur.com/SUmeGkB"><img src="https://i.imgur.com/SUmeGkB.png" title="source: imgur.com" /></a>

**Additional context**
Subtitles are showing with no issues when playing MKV-files that are copied from Blu-ray (and converted to a smaller file size with HandBrake).

**Comment by GamerBene19** [comment]
As far as I can tell this is still an issue with the current Jellyfin version

**Comment by prahal** [comment]
@GamerBene19 could you include the output of `ffprobe <your video file>`?
Though unlikely as MakeMKV does not crop video streams it could be a different video stream size for the video per see and the subtitle video stream.

**Comment by GamerBene19** [comment]
@prahal I just tried to reproduce the issue with a few movies and for all of them subtitles were displayed correctly. Seems like the issue is fixed?
@T4NNh4u53r is it fixed for you too? If so I think this issue can be closed.

**Comment by prahal** [comment]
@GamerBene19 this report talks about multiple issues: missing subtitles and previous to the missing subtitles, the subtitles being displayed a bit to the left.
I guess the issue you backed back then was the missing subtitles as the subtitles are a bit to the left I can still reproduce with cropped videos that are wider than tall (with horizontal black borders added), the one where the video goes to the bottom of the `video area` have subtitles adequately centered (ie ones with vertical black borders or no black borders).

What is weird about these subtitles being a bit to the left is the reporter tells that date back to 10.6. But as before 10.8 and the fix from https://github.com/jellyfin/jellyfin/issues/6833 my subtitles were cropped maybe I did not pay attention to the left off back then.

I believe that this bug is too wide. It describes the subtitle's left positioning well but then it should be retitled to only talk about this left issue. Could the left issue be made into a new bug and this one closed (or the opposite)?

**Comment by GamerBene19** [comment]
> @GamerBene19 this report talks about multiple issues: missing subtitles and previous to the missing subtitles, the subtitles being displayed a bit to the left.

Oh, I must have not read the issue properly (or perhaps I didn't remember it properly). As for me I don't experience this issue anymore - which is good for me, but also means I can't help you debug.

I don't think I'm of much help for this issue anymore.

**Comment by prahal** [comment]
@GamerBene19 that is fine with me. But may I ask you which is the issue that you do not experience anymore?
That was my point, ie to find out which part of the bug report should be kept open in another bug report and which to close. Even if yours was a different one than the two I mentioned this will help.

**Comment by GamerBene19** [comment]
I was experiencing the issue with the shifted subtitles. As stated above I'm not able to reproduce it now so it seems to be fixed :thinking:

**Comment by prahal** [comment]
@GamerBene19 well mine are still shifted (but only if the movie has horizontal black bars, ie is more wide than tall). Do you have a video that exhibits horizontal black bars on jellyfin players (ie not jellyfin kodi plugin, for one jellyfin web is a good test) and that do not have the subtitle shifted to the left?

**Comment by GamerBene19** [comment]
@prahal
>  Do you have a video that exhibits horizontal black bars on jellyfin players

Yes I do, since most movies are in that format (if I understand you correctly). I just choose the first movie I could find and I don't experience the issue (anymore). See screenshot (which is from Jellyfin Web)
![image](https://user-images.githubusercontent.com/20821976/211386612-f0ea9680-b798-4499-889f-edd2934bd4da.png)

**Comment by prahal** [comment]
It might well be that this old left off of the subtitles is not the same as mine. 
My left off of the subtitles still exists, but this left off only happens for cropped videos with non-cropped image-based subtitles.

@GamerBene19 What puzzle me is your screenshot shows horizontal black bars ... but also vertical black bars. I was talking about horizontal black bars only. But I also believe my issue is not the same, that even with only horizontal black bars you would not be able to reproduce the issue with a video the same size as the image subtitle size (ie non Handbrake cropped video).


I believe that non-cropped image-based subtitles are not scaled at the correct display ratio since https://github.com/jellyfin/jellyfin/pull/7736/files. Before, they were cut so no better.

Back in December 2021, I made an attempt to fix the cropped subtitle (that were cropped to the cropped video stream size) by using FFmpeg scale2ref. That is from:
`-filter_complex "[0:3]scale=720x512[sub];[0:0]scale=trunc(min(max(iw\,ih*dar)\,min(720\,512*dar))/2)*2:trunc(min(max(iw/dar\,ih)\,min(720/dar\,512))/2)*2[base];[base][sub]overlay"`
to:
` -filter_complex "[0:0]scale=trunc(min(max(iw\,ih*dar)\,min(720\,512*dar))/2)*2:trunc(min(max(iw/dar\,ih)\,min(720/dar\,512))/2)*2[base];[0:3][base]scale2ref[subs][bases];[bases][subs]overlay"`

ffprobe shows for this cropped video:
```
Stream #0:0: Video: h264 (Main), yuv420p(tv, smpte170m/bt470bg/bt709, progressive), 716x430 [SAR 64:45 DAR 22912:9675], 25 fps, 25 tbr, 1k tbn, 180k tbc (default)
```
and for the subtitle (not cropped thus bigger):
```
Stream #0:3(fre): Subtitle: dvd_subtitle, 720x576 (default)
```
which gives:
![Capture d’écran du 2023-01-10 22-20-20](https://user-images.githubusercontent.com/140865/211671442-765dc8c9-48b4-44dc-8e21-ed3d11f1fa12.png)

with vanilla DVD, ie non cropped video, that is video the same size as the vobsub:
![Capture d’écran du 2023-01-10 22-19-19](https://user-images.githubusercontent.com/140865/211671761-695362e2-e45c-48d0-82c1-39c3996a42c8.png)

I expect that with cropped video the image-based subtitles stream has to be rescaled and so will not look as good as vanilla, still it should be stretched to the width (with scale2ref).

**Comment by prahal** [comment]
Still this bug report tells about 10.6 and 10.7 while my cropped video vs non cropped subtitle issue giving a left off should only exists on 10.8 per that is what  https://github.com/jellyfin/jellyfin/pull/7736/files was merged in.

**Comment by GamerBene19** [comment]
> @GamerBene19 What puzzle me is your screenshot shows horizontal black bars ... but also vertical black bars. I was talking about horizontal black bars only. But I also believe my issue is not the same, that even with only horizontal black bars you would not be able to reproduce the issue with a video the same size as the image subtitle size (ie non Handbrake cropped video).

This is because I did not take the screenshot in full screen mode (see little icon to toggle it in the bottom right corner). In full screen there are horizontal black bars only and the subtitles are still centered. Sorry for the confusion.

**Comment by prahal** [comment]
@GamerBene19 by a cropped video I mean Handbrake has a setting to strip the black bar from the encoded video (thus it does not code the black bars and this saves bits for the *real* video. The issue I have is that the subtitles video is the same size as the non-black bars cropped video (the subtitle are partially in the black bars). Thus on playback, an issue arises that the subtitles video is not the same size as the *real* video with black bars cropped.
The subtitles video is scaled inside the *real* video (and thus does not appear in the black bars anymore). Or if not scaled it will be drawn out of the rendered area (in the now non-existent cropped horizontal black bars). There could be an issue if the subtitles video is not scaled both vertically and horizontally and centered the subtitle are not centered.
Thus my issue does not affect non black bars cropped video.
You can check with ffprobe:
```
Stream #0:0: Video: h264 (Main), yuv420p(tv, smpte170m/bt470bg/bt709, progressive), 720x428 [SAR 64:45 DAR 256:107], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 02:08:18,781000000
(...)
Stream #0:4(eng): Subtitle: dvd_subtitle, 720x576 (default)
    Metadata:
      title           : Closed Caption
      DURATION        : 02:08:01,578000000
```
here the *real* video is 720x428 and the subtitles video is 720x576.
