### ISSUE TITLE
[Issue]: Schedules direct artwork not loading

### ISSUE THREAD

**Issue by rudism** [jellyfin/jellyfin#7528]
### Please describe your bug

I've seen this on both 10.7.7 and 10.8.0-beta1 (dockerized). I have a tvheadend instance running and getting the channel lineup works fine using both tvheadend's M3U support directly as well as using Antennas to emulate the hdhomerun API. Getting the episode guide from schedulesdirect.org also works, however artwork for live TV programs only works sporadically.

The logs indicate it is receiving a mime type of `image/jpg` and unable to translate that to a file extension. I'm not sure if that means schedulesdirect.org is sending images with an invalid `image/jpg` mime type or if it's coming from somewhere else. Seems like an easy fix to add that to the recognized mime types in Jellyfin though.

What's weird is that occasionally the artwork will start working for a handful of shows and then break again.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Void Linux (kernel 5.15.30)
- Virtualization: Docker
- Clients: Web, Roku, Android
- Browser: Firefox, Chromium
- FFmpeg Version: 4.4.1-Jellyfin
- Reverse Proxy: none
- Networking: Exposing docker ports on host
- Storage: Docker volume mapped to host filesystem
```

### Jellyfin logs
Multiple of these errors hit the logs when viewing the Jellyfin front page or scrolling through the live TV show list while the live TV images are not loading:
```shell
System.ArgumentException: Unable to determine image file extension from mime type image/jpg
   at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Jellyfin.Api.Controllers.ImageController.GetImageInternal(Guid itemId, ImageType imageType, Nullable`1 imageIndex, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, Nullable`1 addPlayedIndicator, Nullable`1 blur, String backgroundColor, String foregroundLayer, BaseItem item, ItemImageInfo imageInfo)
   at Jellyfin.Api.Controllers.ImageController.GetItemImage(Guid itemId, ImageType imageType, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, String tag, Nullable`1 cropWhitespace, Nullable`1 format, Nullable`1 addPlayedIndicator, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 blur, String backgroundColor, String foregroundLayer, Nullable`1 imageIndex)
   at lambda_method722(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/4787751/160929864-454c89d5-fa05-4bb4-9d45-8c6c0fc65d9c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
The history of [MimeTypes.cs](https://github.com/jellyfin/jellyfin/commits/master/MediaBrowser.Model/Net/MimeTypes.cs) is directly relevant here.

#6977 changed it from `image/jpg` to `image/jpeg`
#7052 added `image/jpg` back in as a second mapping
#7101 removed `image/jpg` again

I feel like there was some discussion around this that I can't find/remember regarding why `image/jpg` isn't valid and can't be left in. Regardless, I'm pretty sure that #7521 will fix this.

**Comment by rudism** [comment]
`image/jpg` is not a valid mime type per the [official rfc](http://www.iana.org/assignments/media-types/media-types.xhtml) that defines them. But I would argue that if it's known that Schedules Direct uses that mime type despite being technically incorrect (assuming that's where it's coming from--I'm not really sure), in order to get full value out of that integration then leaving that mapping in is probably the lesser of two evils.

**Comment by rudism** [comment]
Just to note, I created a new docker image based off of `master` which has #7521 merged and it did not fix this issue. I think it's because the Schedules Direct media urls don't include a file extension in them. However when I patched `image/jpg` back into the mappings in `MimeTypes.cs` that did fix it and my Live TV images started working.

**Comment by abpei** [comment]
> Just to note, I created a new docker image based off of `master` which has #7521 merged and it did not fix this issue. I think it's because the Schedules Direct media urls don't include a file extension in them. However when I patched `image/jpg` back into the mappings in `MimeTypes.cs` that did fix it and my Live TV images started working.

Unfortunately, this is still an issue. Is there an easier fix than re-compiling with this workaround?

**Comment by frabe8378910** [comment]
> > Just to note, I created a new docker image based off of `master` which has #7521 merged and it did not fix this issue. I think it's because the Schedules Direct media urls don't include a file extension in them. However when I patched `image/jpg` back into the mappings in `MimeTypes.cs` that did fix it and my Live TV images started working.
> 
> Unfortunately, this is still an issue. Is there an easier fix than re-compiling with this workaround?

I'd like to second that. Using LiveTV is the most important task I'd do with jellyfin as our family is still doing with emby. We are located in Germany and the only useful and easy EGP which map clean to emby/jellyfin with ready to use EPG is "Schedules Direct". Not getting any pictures inside jellyfin still renders it unusable for our LiveTV experience. 
So I'm also interested in having a fix for that or any work-a-round to get that "gap" closed. 
Thanks in advance.

**Comment by arazilsongweaver** [comment]
This bug is still active in Jellyfin 10.8.5 (Debian Package) running on Debian. Attempting to update the Schedules Direct provided TV guide data results in a steady stream of the following message in the active jellyfin.log file:

```
[2022-09-28 13:00:21.787 -05:00] [ERR] Error getting image info from schedules direct
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.IReadOnlyList`1[Emby.Server.Implementations.LiveTv.Listings.SchedulesDirectDtos.ImageDataDto]. Path: $[0].data | LineNumber: 0 | BytePositionInLine: 35.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetImageForPrograms(ListingsProviderInfo info, IReadOnlyList`1 programIds, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.Listings.SchedulesDirect.GetImageForPrograms(ListingsProviderInfo info, IReadOnlyList`1 programIds, CancellationToken cancellationToken)
```

In addition to these log messages, live television shows do not have any artwork associated to them.

**Comment by jedthe3rd** [comment]
Might be related to this: 
https://www.schedulesdirect.org/news/056/SD-JSON-images-now-require-tokens

**Comment by matthiaslexer** [comment]
+1 have the same problem, a fix would be very helpful

**Comment by abpei** [comment]
Not a JF issue - SD silently disabled images altogether. https://forums.schedulesdirect.org/viewtopic.php?f=5&t=3222
I'm using zap2xml now which imports pictures fine, but it's a bit of fiddling.

**Comment by anthonylavado** [comment]
This should be fixed with the coming 10.8.6. You may need to refresh Guide Data once installed (I think we cache around 14 days out). Thanks for your patience.

**Comment by junobomb** [comment]
Although fixed in 10.8.6, now it requires refreshing Guide Data for images to appear.  After a while images disappear and do not refresh automatically.  Refreshing guide manually works.

**Comment by rudism** [comment]
@junobomb I see the same behavior. Might be worth opening a new issue for that one.

**Comment by anthonylavado** [comment]
Yeah, I see the issue. Thanks for opening up another ticket. I'll try to get some of more experienced server team on it.

**Comment by Sketterman23** [comment]
I am running 10.8.10 and also having this problem. Some images load and others don't. Then after a few hours they're all gone. Even refreshing guide data manually doesn't fix it.

**Comment by duplexsystem** [comment]
Same issue for me

**Comment by anthonylavado** [comment]
Continuing in #8835
