### ISSUE TITLE
[Issue]: Episodes of tv shows treated as versions instead of separate episodes

### ISSUE THREAD

**Issue by FrankJeager** [jellyfin/jellyfin#7855]
### Please describe your bug

Jellyfin parses different episodes of a tv show as multiple versions of the same episode.
A lot of tv show have this problem on my server. But not all...

I join 2 snapshots to illustrate the issue.

I tried to erase the database of metadata and rescan the folders but the issue persists...

I suspect a conflict between regExps in https://github.com/jellyfin/jellyfin/tree/master/Emby.Naming/Common/NamingOptions.cs

Plus it seems the regExp at line 287 has an error near the end : 
the last bloc should be `([^\\|\/]*)`
and not `([^\\/]*)`

### Jellyfin Version

10.8.0

### if other:

10.8.0 beta 3

### Environment

```markdown
- OS: Windows 11
- Virtualization:
- Clients: Browser
- Browser: Chrome 102.0.5005.63
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: local
```

### Jellyfin logs

```shell
[2022-06-06 16:48:31.016 +02:00] [INF] [1] Main: Jellyfin version: "10.8.0"
[2022-06-06 16:48:31.032 +02:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2022-06-06 16:48:31.034 +02:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2022-06-06 16:48:31.035 +02:00] [INF] [1] Main: Operating system: "Windows"
[2022-06-06 16:48:31.036 +02:00] [INF] [1] Main: Architecture: X64
[2022-06-06 16:48:31.036 +02:00] [INF] [1] Main: 64-Bit Process: True
[2022-06-06 16:48:31.037 +02:00] [INF] [1] Main: User Interactive: True
[2022-06-06 16:48:31.037 +02:00] [INF] [1] Main: Processor count: 20
[2022-06-06 16:48:31.037 +02:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2022-06-06 16:48:31.038 +02:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2022-06-06 16:48:31.038 +02:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2022-06-06 16:48:31.255 +02:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2022-06-06 16:48:31.409 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2022-06-06 16:48:31.848 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniDB, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\AniDB_6.0.0.0\Jellyfin.Plugin.AniDB.dll"
[2022-06-06 16:48:31.867 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniList, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\AniList_5.0.0.0\Jellyfin.Plugin.AniList.dll"
[2022-06-06 16:48:31.895 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniSearch, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\AniSearch_4.0.0.0\Jellyfin.Plugin.AniSearch.dll"
[2022-06-06 16:48:31.917 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Fanart, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Fanart_9.0.0.0\Jellyfin.Plugin.Fanart.dll"
[2022-06-06 16:48:31.963 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\TheTVDB_8.0.0.0\Jellyfin.Plugin.Tvdb.dll"
[2022-06-06 16:48:31.971 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\TheTVDB_8.0.0.0\TvDbSharper.dll"
[2022-06-06 16:48:32.024 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Trakt, Version=19.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Trakt_19.0.0.0\Trakt.dll"
[2022-06-06 16:48:32.394 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2022-06-06 16:48:32.394 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2022-06-06 16:48:32.395 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2022-06-06 16:48:32.402 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2022-06-06 16:48:32.402 +02:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2022-06-06 16:48:34.474 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniDB" "6.0.0.0"
[2022-06-06 16:48:34.474 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniList" "5.0.0.0"
[2022-06-06 16:48:34.476 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniSearch" "4.0.0.0"
[2022-06-06 16:48:34.477 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Fanart" "9.0.0.0"
[2022-06-06 16:48:34.478 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "8.0.0.0"
[2022-06-06 16:48:34.479 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Trakt" "19.0.0.0"
[2022-06-06 16:48:34.479 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.0.0"
[2022-06-06 16:48:34.480 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.0.0"
[2022-06-06 16:48:34.480 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.0.0"
[2022-06-06 16:48:34.481 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.0.0"
[2022-06-06 16:48:34.481 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.0.0"
[2022-06-06 16:48:34.548 +02:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
[2022-06-06 16:48:34.820 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2022-06-06 16:48:34.837 +02:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extraire les images de chapitre" set to fire at 2022-06-07 02:00:00.000 +02:00, which is 09:11:25.1625730 from now.
[2022-06-06 16:48:34.928 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "5.0.1"
[2022-06-06 16:48:34.954 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2022-06-06 16:48:34.975 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2022-06-06 16:48:34.995 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_cuda", "scale_cuda", "scale_opencl", "scale_qsv", "tonemap_cuda", "tonemap_opencl", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2022-06-06 16:48:35.086 +02:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2022-06-06 16:48:35.105 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2022-06-06 16:48:35.123 +02:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2022-06-06 16:48:35.127 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "bc6bd12877474d48bfe2369f59997506"
[2022-06-06 16:48:35.249 +02:00] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.1.15/24"
[2022-06-06 16:48:35.258 +02:00] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "127.0.0.1/8"
[2022-06-06 16:48:35.260 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1301978
[2022-06-06 16:48:35.261 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2022-06-06 16:48:35.360 +02:00] [INF] [13] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Vidéos\Anime"
[2022-06-06 16:48:35.360 +02:00] [INF] [7] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Vidéos\Films d'animation"
[2022-06-06 16:48:35.360 +02:00] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Vidéos\Séries"
[2022-06-06 16:48:35.360 +02:00] [INF] [9] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Vidéos\Films"
[2022-06-06 16:48:35.391 +02:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1298615
[2022-06-06 16:48:35.392 +02:00] [INF] [1] Main: Startup complete 0:00:04.8817942
[2022-06-06 16:48:37.244 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"AccessSchedule"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.246 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ActivityLog"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.246 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"CustomItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.247 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.248 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"HomeSection"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.248 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ImageInfo"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.249 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.250 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Permission"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.251 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Preference"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.252 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ApiKey"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.252 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Device"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.253 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DeviceOptions"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2022-06-06 16:48:37.254 +02:00] [WRN] [21] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"User"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
...
[2022-06-06 16:54:22.546 +02:00] [INF] [120] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "Black Mirror"
[2022-06-06 16:54:22.669 +02:00] [INF] [13] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "Better Call Saul"
[2022-06-06 16:54:22.682 +02:00] [INF] [134] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "Banshee"
[2022-06-06 16:54:22.775 +02:00] [INF] [96] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "Animal Armageddon"
[2022-06-06 16:54:22.812 +02:00] [INF] [99] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "La Vipère noire"
[2022-06-06 16:54:22.841 +02:00] [INF] [122] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "All of Us Are Dead"
[2022-06-06 16:54:22.842 +02:00] [INF] [122] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: 184d3485-67fb-c156-6c72-354fafb04620
[2022-06-06 16:54:22.844 +02:00] [INF] [122] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison 1" entry for "All of Us Are Dead"
[2022-06-06 16:54:22.865 +02:00] [ERR] [101] MediaBrowser.Providers.Manager.ProviderManager: "TvdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "D:\Vidéos\Séries\Bridal Mask"
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2022-06-06 16:54:22.915 +02:00] [INF] [99] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "Bridal Mask"
[2022-06-06 16:54:23.047 +02:00] [INF] [99] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "La casa de papel"
[2022-06-06 16:54:23.058 +02:00] [INF] [134] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "The Outer Limits - Au-delà du réel, l'aventure continue"
[2022-06-06 16:54:23.104 +02:00] [INF] [122] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Better Call Saul"
[2022-06-06 16:54:23.104 +02:00] [INF] [122] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: 49037c8d-a05e-99b9-4bc6-6ebb5eefae36
[2022-06-06 16:54:23.116 +02:00] [INF] [122] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison 1" entry for "Better Call Saul"
[2022-06-06 16:54:23.162 +02:00] [INF] [136] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Altered Carbon"
[2022-06-06 16:54:23.162 +02:00] [INF] [136] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: f192020b-70db-1fdf-b3ea-6443cfb2cfb8
[2022-06-06 16:54:23.168 +02:00] [INF] [136] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison 1" entry for "Altered Carbon"
[2022-06-06 16:54:23.187 +02:00] [INF] [13] Jellyfin.Plugin.AniSearch.Providers.AniSearch.AniSearchSeriesProvider: Start AniSearch... Searching("Pokémon")
[2022-06-06 16:54:23.230 +02:00] [INF] [134] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "Breaking Bad"
[2022-06-06 16:54:23.297 +02:00] [INF] [88] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Banshee"
[2022-06-06 16:54:23.298 +02:00] [INF] [88] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: 64fc726d-3d9b-9bf9-ba79-59157370ece9
[2022-06-06 16:54:23.300 +02:00] [INF] [88] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison 1" entry for "Banshee"
[2022-06-06 16:54:23.340 +02:00] [ERR] [120] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[date(FirstAired):2008-06-01]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2022-06-06 16:54:23.341 +02:00] [ERR] [120] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Episode 1xnull not found for series "72224"
[2022-06-06 16:54:23.351 +02:00] [INF] [137] Jellyfin.Plugin.AniSearch.Providers.AniSearch.AniSearchSeriesProvider: Start AniSearch... Searching("Les chevaliers du zodiaque")
[2022-06-06 16:54:23.545 +02:00] [INF] [13] Jellyfin.Plugin.AniSearch.Providers.AniSearch.AniSearchSeriesProvider: Start AniSearch... Searching("Mushishi")
[2022-06-06 16:54:23.690 +02:00] [ERR] [120] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[date(FirstAired):2008-06-15]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2022-06-06 16:54:23.692 +02:00] [ERR] [120] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Episode 1xnull not found for series "72224"
[2022-06-06 16:54:23.759 +02:00] [INF] [120] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "The Outer Limits - Au-delà du réel, l'aventure continue"
[2022-06-06 16:54:23.760 +02:00] [INF] [120] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: c916a29b-5ed7-cbe2-1d77-827b2d59703c
[2022-06-06 16:54:23.763 +02:00] [ERR] [120] Emby.Server.Implementations.Library.LibraryManager: Error in ItemRemoved event handler
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.OnLibraryManagerItemRemoved(Object sender, ItemChangeEventArgs itemChangeEventArgs)
   at Emby.Server.Implementations.Library.LibraryManager.ReportItemRemoved(BaseItem item, BaseItem parent)
[2022-06-06 16:54:23.764 +02:00] [INF] [120] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison 1" entry for "The Outer Limits - Au-delà du réel, l'aventure continue"
[2022-06-06 16:54:23.865 +02:00] [INF] [88] Jellyfin.Plugin.AniSearch.Providers.AniSearch.AniSearchSeriesProvider: Start AniSearch... Searching("Berserk")
[2022-06-06 16:54:24.223 +02:00] [INF] [111] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison Inconnue" entry for "Agatha Christie - Dix petits nègres"
[2022-06-06 16:54:24.324 +02:00] [INF] [111] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Animal Armageddon"
[2022-06-06 16:54:24.324 +02:00] [INF] [111] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: d6101f80-4128-e278-37f3-a0cbb1e917a6
[2022-06-06 16:54:24.327 +02:00] [INF] [111] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison 1" entry for "Animal Armageddon"
[2022-06-06 16:54:24.338 +02:00] [ERR] [120] MediaBrowser.Providers.Manager.ProviderManager: "TvdbSeasonImageProvider" failed in GetImageInfos for type "Season" at null
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
...

[2022-06-06 16:57:13.969 +02:00] [ERR] [92] Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider: Failed to retrieve series with id null
TvDbSharper.TvDbServerException: The given series ID does not exist; ID: 0 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider.FetchSeriesMetadata(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
[2022-06-06 16:57:13.970 +02:00] [INF] [133] Jellyfin.Plugin.AniList.Providers.AniList.AniListSeriesProvider: Start AniList... Searching("Star Wars Rebels")
[2022-06-06 16:57:13.999 +02:00] [INF] [24] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Animal Armageddon"
[2022-06-06 16:57:14.000 +02:00] [INF] [24] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: d6101f80-4128-e278-37f3-a0cbb1e917a6
[2022-06-06 16:57:14.007 +02:00] [INF] [24] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Saison 1" entry for "Animal Armageddon"
[2022-06-06 16:57:14.027 +02:00] [ERR] [92] MediaBrowser.Providers.Manager.ProviderManager: "TvdbSeasonImageProvider" failed in GetImageInfos for type "Season" at null
TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2022-06-06 16:57:14.044 +02:00] [INF] [78] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "Agatha Christie - Dix petits nègres"
[2022-06-06 16:57:14.044 +02:00] [INF] [127] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "All of Us Are Dead"
[2022-06-06 16:57:14.045 +02:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: c081eea2-7e66-92b0-5296-357735b4b1fe
[2022-06-06 16:57:14.045 +02:00] [INF] [127] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Saison Inconnue", Path: "", Id: 184d3485-67fb-c156-6c72-354fafb04620
[2022-06-06 16:57:14.049 +02:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Error in ItemRemoved event handler
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.OnLibraryManagerItemRemoved(Object sender, ItemChangeEventArgs itemChangeEventArgs)
   at Emby.Server.Implementations.Library.LibraryManager.ReportItemRemoved(BaseItem item, BaseItem parent)
```

### Please attach any screenshots here

![Capture d’écran 2022-06-06 173732](https://user-images.githubusercontent.com/106985437/172194799-3b68c3a9-0a96-4ceb-b11b-ebdf506170a6.png)
![Capture d’écran 2022-06-06 173804](https://user-images.githubusercontent.com/106985437/172194817-d6cfe963-fc2f-46d1-a7a5-291f68f92ba8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nalsai** [comment]
I have a couple of shows that have this problem too.

**Comment by SenorSmartyPants** [comment]
Try removing the second dash in the file name.

**Comment by Nalsai** [comment]
I moved the shows that had this problem into a `Season 1` subfolder and that fixed it.

**Comment by SenorSmartyPants** [comment]
When the filename matches the directory name and there is a dash after the SXXEYY numbers this is when JF starts looking for multiple versions. I think.

**Comment by Shadowghost** [comment]
Place your files in a season folder and it should work.

**Comment by FrankJeager** [comment]
Thank you for your comment 👍 

I already tried to put the episodes in a season folder but the result is exactly the same.
Plus if it worked it would only be a workaround.
The naming is correct, the software should parse correctly the episodes.
Its not the episodes or folders that should be renamed.

**Comment by SenorSmartyPants** [comment]
Double checking the [multiple version naming](https://jellyfin.org/docs/general/server/media/movies.html#multiple-versions-of-a-movie) the problem is the first space-dash-space. Everything before that is the same as the folder name. This is what signals to JF you are trying to do multiple versions. Remove the first dash from your naming convention. Or using season folders, since then the first part of the for name won't match. 

You could do a full rescan of your library just in case, after renaming.

**Comment by ScuttleSE** [comment]
Having the exact same problem. Worked fine before 10.8.0, after upgrading it broke.

Also, the "multiple version naming" documentation applies to movies, not TV shows.

**Comment by ScuttleSE** [comment]
> When the filename matches the directory name and there is a dash after the SXXEYY numbers this is when JF starts looking for multiple versions. I think.

There is nothing in the documentation indicating Jellyfin should act like this for TV shows, just movies. Also, it's something that started with 10.8.0, so _something_ changed, or broke...

**Comment by crobibero** [comment]
Fixed by #7892

**Comment by cschlesselmann** [comment]
In case anyone is interested, i wrote a small rust program to move all my series into season folders

<details>
<summary>Source</summary>

```rust
use std::{fs::{self, DirEntry}, collections::{HashMap}};
use clap::Parser;
use regex::Regex;

/// Moves episodes of series into season subfolders
#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
struct Args {
    /// Base folder that contains series folders
    #[clap(short, long, value_parser)]
    dir: String,

    /// Dont actually move files
    #[clap(long, value_parser, default_value_t = false)]
    dry_run: bool,
}

fn fix_series(folder: &DirEntry, dry_run: bool) {
    let re = Regex::new(r"^.*S([0-9]+)E[0-9]+.*(?:\.mkv|\.mp4)$").unwrap();

    let mut season_files : HashMap<String, Vec<DirEntry>> = HashMap::new();
    let parent = fs::read_dir(folder.path()).unwrap();

    for path in parent {
        let file = path.unwrap();
        let filename = file.file_name();
        if file.file_type().unwrap().is_file() {
            if re.is_match(filename.to_str().unwrap()) {
                println!("File match: {}", filename.to_str().unwrap());
                let season = re.captures(filename.to_str().unwrap()).unwrap().get(1).unwrap().as_str();

                season_files.entry(season.to_string()).or_insert(Vec::new()).push(file);
            }
        }
    }

    for (season, episodes) in season_files {
        let season_folder = get_season_folder(&season, folder);
        ensure_season_folder(&season_folder, dry_run);

        for episode in episodes {
            let path = episode.path();
            let source = path.to_str().unwrap();
            let target = format!("{}/{}", &season_folder, episode.file_name().to_str().unwrap());
            println!("Moving {} to {}", source, target);
            if ! dry_run {
                fs::rename(source, target).ok();
            }
        }
    }
}

fn get_season_folder(season: &String, series_folder: &DirEntry) -> String {
    return series_folder.path().to_str().unwrap().to_owned() + "/Season " + &season;
}

fn ensure_season_folder(season_folder: &String, dry_run: bool) {
    println!("Ensuring folder {}", season_folder);
    if ! dry_run {
        fs::create_dir_all(season_folder).ok();
    }
}

fn main() {
    let args = Args::parse();
    let parent_paths = fs::read_dir(args.dir).unwrap();
    if args.dry_run {
        println!("DRY RUN!");
    }

    for path in parent_paths {
        let series_folder = &path.unwrap();
        if series_folder.file_type().unwrap().is_dir() {
            println!("Fixing: {:?}", series_folder.path().display());
            fix_series(series_folder, args.dry_run);
        }
    }
}
```
</details>

**Comment by agonybroccoli** [comment]
I believe this is still a bug. I’m currently using 10.8.4 docker, official Jellyfin build and have followed Jellyfin’s official naming guide, tried using Sonarr default naming and have tried [this guide](https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/) as well. I’ve renamed and rescanned about 4 times and the issue persists. Some TV shows consistently work fine and others group all the episodes into “versions” of one. Any chance of an option to switch off this “feature” in the settings?
