### ISSUE TITLE
No external subtitles (.srt) on 10.8.0 using DLNA Samsung j5200

### ISSUE THREAD

**Issue by nakhla** [jellyfin/jellyfin#7974]
### Please describe your bug

No external subtitles (.srt) on 10.8.0 using DLNA Samsung j5200
- OS:Windows
was working before on 10.5.2, any one can confirm this issue?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LePips** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/7960

**Comment by nakhla** [comment]
should i downgrade to 10.5.2 to use ordinanry .srt files instead of converting to subrip
please can you give me more further information?

**Comment by LePips** [comment]
No, you can wait till 10.8.1 which will be released soon. The conversion from srt to subrip isn't something to worry about.

**Comment by kminek** [comment]
i think it's still not fixed: see https://github.com/jellyfin/jellyfin/issues/8674

**Comment by nakhla** [comment]
> i think it's still not fixed: see #8674

 downgrade to 10.5.2 and inform me if this trick solved your problem

**Comment by kminek** [comment]
@nakhla where can i find debian package with 10.5.2? i tried installing via docker but somehow my TV doesnt see jellyfin at all :(

**Comment by nakhla** [comment]
> @nakhla where can i find debian package with 10.5.2? i tried installing via docker but somehow my TV doesnt see jellyfin at all :(

all versions was available here under old stable releases section (archive) i don't know why are all deleted!!!
https://repo.jellyfin.org/releases/server/

**Comment by nakhla** [comment]
> 

you can find old stable releases under archive section, available for debian and ubuntu
https://repo.jellyfin.org/archive/server/debian/stable/
this is for debian and version 10.5.2 is available here, try it and get back to me

**Comment by kminek** [comment]
@nakhla i managed to install 10.5.2 but still my TV cannot see Jellyfin server over DLNA :( but 10.5.2 is quite old release - its from march 2020 - so its like almost 3 years old.

but i did some other test - i installed DLNA server on my smartphone: https://play.google.com/store/apps/details?id=com.al.dlnaserver and put video file in question there (along with subtitle file) and my TV plays it fine with subtitles - so there must be something wrong with DLNA support in Jellyfin

**Comment by nakhla** [comment]
Still persists, other simple servers work better
