### ISSUE TITLE
Fresh install of Jellyfin 10.8.10 (MacOS) on Mac Mini with M1 chip, Ventura 13.2.1, freezing at library scan 80% with no additional entries to logs

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin#9685]
### Please describe your bug

The issue is on a Mac Mini with M1 chip, Ventura 13.2.1, with Jellyfin 10.8.10 installed via DMG. A few minutes into the scan it will freeze at around 80% then no more entries are added to the logs. The WebUI becomes unresponsive and Jellyfin is unreachable. I have tried multiple times to just leave it alone for a few hours but nothing is added to the logs once it freezes. There is no particular media file causing it to hang. The logs before everything stops are quite ordinary and are different every time. There is no indication in Activity Monitor that either Jellyfin Server or jellyfin are unresponsive. When I try to quit, it doesn't work so I have to force quit. I tried reinstalling Jellyfin 10.8.10 and the problem persists. I tried restarting my Mac a few times but the problem persists. I tried uninstalling the YouTube Metadata plugin and the problem persists.

I tried using `lsof | grep /path/to/stuff` to see what Jellyfin has open when it freezes, and it's usually an NFO file. It's always a different NFO file, so I'm not sure if it's a particular file that is causing it to freeze.

Note that I never have this problem with Jellyfin 10.8.10 via Docker, using the same exact libraries. In fact, just today I booted the container up and completed a library scan without issues.

I'm just trying to switch to MacOS, starting from scratch, so I can use the hardware acceleration.

The logs I've included below are the last logs that show up, _sometimes_, as they are different every time. I see these messages closer to the beginning and middle of the scan too so it doesn't seem like these are what's actually causing it to freeze.

I would greatly appreciate any help that anyone can provide. Thanks so much.

### Jellyfin Version

10.8.10

### Environment

```markdown
- OS: Mac Ventura 13.2.1
- Linux Kernel: none
- Virtualization: none
- Clients: n/a
- Browser: Opera 98.0.4759.6
- FFmpeg Version: whatever is in the 10.8.10 DMG
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin Logs (Example 1)

```
[2023-04-25 13:28:16.198 -07:00] [ERR] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 7) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 13:28:16.198 -07:00] [ERR] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 8) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 13:28:16.198 -07:00] [ERR] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 9) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 13:28:16.198 -07:00] [ERR] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 10) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 13:28:16.198 -07:00] [ERR] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 11) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
```

### Jellyfin Logs (Example 2)

The access to path is denied message here is new to me. I usually get logs like Example 1 and Example 3 and sometimes different ones too.

```
[2023-04-25 13:42:19.741 -07:00] [ERR] [24] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "YoutubeMetadata"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/path/to/stuff/Anime/Fighting Spirit/Hajime_no_Ippo - S03E20_Rising_(720p)_(FroZen)_(Hi10).info.json'.
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at Jellyfin.Plugin.YoutubeMetadata.Utils.ReadYTDLInfo(String fpath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeLocalProvider`2.GetMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)
[2023-04-25 13:42:19.765 -07:00] [ERR] [39] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.UnauthorizedAccessException: Access to the path '/path/to/stuff/Anime/Non Non Biyori' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFileAsync(Stream stream, String path)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
[2023-04-25 13:42:19.780 -07:00] [ERR] [24] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2023-04-25 13:42:19.781 -07:00] [ERR] [24] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "YoutubeMetadata"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/path/to/stuff/TV Shows/Curb Your Enthusiasm/Curb.Your.Enthusiasm.S06E06.1080p.WEBRip.x265-RARBG.info.json'.
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at Jellyfin.Plugin.YoutubeMetadata.Utils.ReadYTDLInfo(String fpath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeLocalProvider`2.GetMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)
[2023-04-25 13:42:19.820 -07:00] [ERR] [39] MediaBrowser.Providers.TV.EpisodeMetadataService: Error validating images for "/path/to/stuff/Anime/Non Non Biyori/Non Non Biyori S02E11 Repeat [BD 1080p][HEVC x265 10bit][AAC][Anime Time].mkv"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/path/to/stuff/Anime/Non Non Biyori'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFiles(String path)
   at MediaBrowser.LocalMetadata.Images.EpisodeLocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```

### Jellyfin Logs (Example 3)
```
[2023-04-25 14:23:31.287 -07:00] [ERR] [36] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/N/Nick Merlino/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/N/Nick Merlino/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-04-25 14:23:31.316 -07:00] [ERR] [36] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/J/Johnny Knoxville/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/J/Johnny Knoxville/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-04-25 14:23:31.353 -07:00] [ERR] [36] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/J/Jason Baum/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/J/Jason Baum/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-04-25 14:23:31.378 -07:00] [ERR] [36] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/S/Shanna Zablow Newton/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/S/Shanna Zablow Newton/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-04-25 14:23:37.899 -07:00] [INF] [18] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Started library sync
[2023-04-25 14:23:38.345 -07:00] [ERR] [12] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/S/Sairi Itoh/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/S/Sairi Itoh/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-04-25 14:23:38.674 -07:00] [INF] [18] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Library Sync: Updated 11 items
[2023-04-25 14:23:38.676 -07:00] [INF] [18] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished library sync, taking "00:00:00.7737590"
```

### Jellyfin Logs (Example 4)
```
[2023-04-25 14:07:21.244 -07:00] [ERR] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 5) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 14:07:21.244 -07:00] [ERR] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 6) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 14:07:21.244 -07:00] [ERR] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 7) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 14:07:21.244 -07:00] [ERR] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 8) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 14:07:21.244 -07:00] [ERR] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 9) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 14:07:21.244 -07:00] [ERR] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 10) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 14:07:21.244 -07:00] [ERR] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 11) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 14:07:21.527 -07:00] [INF] [33] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Season Unknown" entry for "The Sopranos"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
First off, thank you for not just posting on Reddit, but also for writing such a comprehensive issue. There's quite a bit to unpack here but a few questions/notes.

So the library scan percentage isn't exactly linear. I forget the exact numbers, but I want to say that the first 75% or so is actually just crawling directories to build a list of what's there, then the last bit is the actual detailed work of scanning files, resources, doing lookups, etc. It will always take the longest. Depending on the size of your media and the stuff in it, it could very well take a long, long time. Once the scan is actually _done_, then subsequent ones are much faster because it just has to handle any changes. 

For logs example 1 (and any others about codec unknown), that's FFprobe scanning the file and reporting a media track (could be an embedded font, or image, usually subtitle related) that it doesn't handle, so it's just marking it to skip and not show in the list of subtitles/audio tracks for the file.

Log Example 2 is more interesting though. If you look at an NFO file, does it have any paths like the one shown there? Similar to `/config/…`?

If so, it looks like the files were written with relative paths based on your Docker install/file locations. All versions of Jellyfin treat NFO files as their primary information source, if they're with media. If the file has paths for resource files (poster, background, etc), it will also crawl those and try to reach them. If the paths aren't correct, I'm betting the macOS version is essentially slowing to a crawl trying to access these paths that don't exist.

**Comment by nothing2obvi** [comment]
Hi @anthonylavado, thanks so much for replying to this issue. I hope the Reddit post wasn't overkill.

Did you mean Log Example 3 instead of Log Example 2? Anyway, I did open an NFO file and it indeed does have paths similar to the ones in these logs, with `/config/...`

Are you suggesting I try deleting all NFO files and doing a scan?

**Comment by anthonylavado** [comment]
Ah you're right, I got it mixed up.

Well, I wouldn't say _delete_ them, but try moving them out to another directory elsewhere (if you can). If you did really want to use them, I'm sure there's a way to batch edit the paths to the correct location for macOS with a shell script - but that's beyond me at the moment.

**Comment by nothing2obvi** [comment]
I backed up then deleted every NFO file using Rclone. The scan got further, up to 93.7%, but unfortunately, the problem persists.

Here are the final logs, which are pretty ordinary.
```
[2023-04-25 21:16:01.062 -07:00] [ERR] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 5) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 21:16:01.062 -07:00] [ERR] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 6) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 21:16:01.062 -07:00] [ERR] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 7) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 21:16:01.062 -07:00] [ERR] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 8) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 21:16:01.062 -07:00] [ERR] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 9) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 21:16:01.062 -07:00] [ERR] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 10) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-25 21:16:01.062 -07:00] [ERR] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 11) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
```

**Comment by nothing2obvi** [comment]
In case that NFO file I mentioned in my previous comment was actually just missed when I did `rclone delete`, I ran the `rclone delete` commands over again, restarted the Mac, ran them again, and apparently it missed about 120 NFO files, so I just did a few cycles of deleting and restarting my Mac and it kept saying everything was gone. So now I could be sure everything was deleted.

I restarted the Mac again then ran a scan. The scan got stuck at 91.2%.

In the logs I searched for `/config` and found just a few entries that look like the ones below. I'm not sure why some things are still mapped to `/config`. Perhaps left over from my previous scans when I still had the old Docker NFO files in there?
```
Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/Y/Yuuya Uchida/folder.jpg"
File name: '/config/data/metadata/People/Y/Yuuya Uchida/folder.jpg'
[2023-04-26 11:45:56.767 -07:00] [ERR] [35] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/S/Shun Oguri/folder.jpg"
File name: '/config/data/metadata/People/S/Shun Oguri/folder.jpg'
[2023-04-26 11:46:57.388 -07:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/I/Ikkyu Juku/folder.jpg"
File name: '/config/data/metadata/People/I/Ikkyu Juku/folder.jpg'
[2023-04-26 11:46:57.389 -07:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/T/Tarusuke Shingaki/folder.jpg"
File name: '/config/data/metadata/People/T/Tarusuke Shingaki/folder.jpg'
[2023-04-26 11:46:57.438 -07:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/Y/Youji Ueda/folder.jpg"
File name: '/config/data/metadata/People/Y/Youji Ueda/folder.jpg'
[2023-04-26 11:47:01.412 -07:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/Y/Yutaka Nakano/folder.jpg"
File name: '/config/data/metadata/People/Y/Yutaka Nakano/folder.jpg'
```

The final logs looked like they usually do:
```
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 55) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 56) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 57) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 58) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 59) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 60) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
```

I'm pretty determined to get this to work on MacOS as I'd really like to take advantage of the HWA. Next I'll try deleting all Jellyfin folders, reinstalling Jellyfin, and setting up only a few libraries for it to scan.

**Comment by nothing2obvi** [comment]
In case that NFO file I mentioned in my previous comment was actually just missed when I did `rclone delete`, I ran the `rclone delete` commands over again, restarted the Mac, ran them again, and apparently it missed about 120 NFO files, so I just did a few cycles of deleting and restarting my Mac and it kept saying everything was gone. So now I could be sure everything was deleted.

I restarted the Mac again then ran a scan. The scan got stuck at 91.2%.

In the logs I searched for `/config` and found just a few entries that look like the ones below. I'm not sure why some things are still mapped to `/config`. Perhaps left over from my previous scans when I still had the old Docker NFO files in there?
```
Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/Y/Yuuya Uchida/folder.jpg"
File name: '/config/data/metadata/People/Y/Yuuya Uchida/folder.jpg'
[2023-04-26 11:45:56.767 -07:00] [ERR] [35] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/S/Shun Oguri/folder.jpg"
File name: '/config/data/metadata/People/S/Shun Oguri/folder.jpg'
[2023-04-26 11:46:57.388 -07:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/I/Ikkyu Juku/folder.jpg"
File name: '/config/data/metadata/People/I/Ikkyu Juku/folder.jpg'
[2023-04-26 11:46:57.389 -07:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/T/Tarusuke Shingaki/folder.jpg"
File name: '/config/data/metadata/People/T/Tarusuke Shingaki/folder.jpg'
[2023-04-26 11:46:57.438 -07:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/Y/Youji Ueda/folder.jpg"
File name: '/config/data/metadata/People/Y/Youji Ueda/folder.jpg'
[2023-04-26 11:47:01.412 -07:00] [ERR] [24] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/Y/Yutaka Nakano/folder.jpg"
File name: '/config/data/metadata/People/Y/Yutaka Nakano/folder.jpg'
```

The final logs looked like they usually do:
```
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 55) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 56) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 57) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 58) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 59) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 11:48:31.150 -07:00] [ERR] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 60) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
```

I'm pretty determined to get this to work on MacOS as I'd really like to take advantage of the HWA. Next I'll try deleting all Jellyfin folders, reinstalling Jellyfin, and setting up only a few libraries for it to scan.

**Comment by nothing2obvi** [comment]
1.) Deleted the two Jellyfin folders as described [here](https://jellyfin.org/docs/general/installation/macos/). Reinstalled Jellyfin 10.8.10 via DMG. Deleted all NFO files again. Restarted my Mac. Installed only official plugins, added two libraries, did a scan, and unfortunately the problem persists. Tried the scan a few times between Mac restarts but I keep getting stuck around 70%.

The final logs looked like they usually do:
```
[2023-04-26 13:03:07.090 -07:00] [ERR] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 7) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:03:07.090 -07:00] [ERR] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 8) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:03:07.090 -07:00] [ERR] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 9) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:03:07.090 -07:00] [ERR] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 10) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:03:07.090 -07:00] [ERR] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 11) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:03:07.090 -07:00] [ERR] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 12) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
```

2.) Tried that whole process over again, this time installing no additional plugins. Scanned between Mac restarts and it keeps getting stuck around 70%.

The final logs looked like they usually do:
```
[2023-04-26 13:51:22.614 -07:00] [ERR] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 37) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:51:22.614 -07:00] [ERR] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 38) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:51:22.614 -07:00] [ERR] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 39) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:51:22.614 -07:00] [ERR] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 40) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:51:22.614 -07:00] [ERR] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 41) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-26 13:51:22.614 -07:00] [ERR] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 42) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
```

I'm at a loss here =/

**Comment by nothing2obvi** [comment]
Btw, I know this is another issue, but I tried to enable debugging logs by following this [guide](https://jellyfin.org/docs/general/administration/troubleshooting#debug-logging) and changing "Information" to "Debug", but when I do Jellyfin just won't open. I mean, the app opens but there's nothing in the logs, only stuff from the last session, and the WebUI won't open. In Activity Monitor there's no "jellyfin" there anymore. It doesn't resolve when I change "Debug" back to "Information." It only resolves when I delete all the Jellyfin folders and start the app from scratch.

**Comment by nothing2obvi** [comment]
Deleted all NFO files and both Jellyfin folders. Installed Jellyfin 10.8.9 instead. Same results, scanning between Mac restarts, stuck between 70-80% with Jellyfin WebUI unresponsive.

The final logs looked like they usually do:
```
[2023-04-27 14:18:56.742 -07:00] [ERR] [41] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 14) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-27 14:18:56.742 -07:00] [ERR] [41] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 15) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-27 14:18:56.742 -07:00] [ERR] [41] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 16) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-27 14:18:56.742 -07:00] [ERR] [41] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 17) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-04-27 14:18:57.047 -07:00] [INF] [41] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Season 2" entry for "Seinfeld"
[2023-04-27 14:18:57.286 -07:00] [INF] [30] Jellyfin.Plugin.TvMaze.Providers.TvMazeSeasonImageProvider: [GetImages] Images found for "Season 1": []
```

Just wanted to note again that after all these trials I've done I've restored my original Docker setup NFO files, booted up my Jellyfin 10.8.10 container, and ran a full library scan without issues.

Hope I'm not spamming too much!

**Comment by nothing2obvi** [comment]
Deleted all NFO files and both Jellyfin folders. Installed Jellyfin 10.8.10. On Mac, went to Settings > Privacy & Security and enabled Full Disk Access for Jellyfin. Restarted. Did a few scans between restarts with same results, stuck between 70-80% with Jellyfin WebUI unresponsive.

The final logs looked like they usually do.

On these trials, using `lsof | grep /path/to/stuff' Jellyfin was stuck on a JPG and/or MKV file. I ran the command once per minute for about 15 minutes and each time it was stuck on the same files.

**Comment by nothing2obvi** [comment]
I wonder if it has anything to do with [Ventura](https://www.reddit.com/r/jellyfin/comments/zsq5t1/new_jellyfin1088_install_on_macos_m1_mini_locking/)?

**Comment by nothing2obvi** [comment]
@anthonylavado I may have something for you.

Reading those Reddit threads made me curious about whether the issue might be because of my hardware, Mac Mini with M1 chip, or perhaps because of my MacOS, Ventura 13.2.1.

I used Rclone to mount my media library onto another computer on my LAN, a Mac Mini 2018, Intel, Monterey 12.6. I did not enable Full Disk Access. I installed Jellyfin 10.8.10 via DMG, added only official plugins, added the same large library I've been testing with, hit "Scan All Libraries," and it completed successfully!!

So it seems this issue may have something to do with the hardware (maybe Apple vs. Intel) and/or the MacOS version.

There's something that I'm not sure is worth noting, but on the Mac Mini with M1 chip when I go to Finder and select "Get Info" on Jellyfin, there's nothing that says "Open using Rosetta" as described [here](https://support.apple.com/en-us/HT211861). Should it say that? I used the DMG located [here](https://repo.jellyfin.org/releases/server/macos/stable/).

Anyway, I hope this and my previous comments are helpful. Sorry there are so many of them.

**Comment by compufox** [comment]
Commenting here to let you know that I have been having this exact same issue, and I just downgraded from Ventura to Monterey on the machine I've been trying to run this on and it's having the same issues.

So it looks like this may be an issue with running on the arm64 arch and not with macOS 13 

Tested this on an M1 Mac Mini on macOS 12.6.5
after telling jellyfin to scan my largest library the web interface becomes completely unresponsive and nothing loads.

I left all options for the library as default, just clicked thru all the prompts.

**Comment by nothing2obvi** [comment]
@compufox So did you get it to work? Did it scan to 100% and finish? Is everything else working properly? Are you able to watch your media?

**Comment by compufox** [comment]
the first scan thru the media would freeze up, but subsequent scans would work and end as expected.
and i was able to navigate back to the home view and watch my media, yes.

I didn't choose any settings for the libraries, just selected the folder and clicked thru the prompts

**Comment by nothing2obvi** [comment]
@compufox Thanks for this. Maybe I'll try it again but in my experience it still froze up on repeated scans. Your experience with it sounds promising, though.

**Comment by WhyDidIHaveToDoThis** [comment]
I've been having the same issue, Jellyfin crashes every time I add a new library so I have to restart. I started getting crashes while playing media though too. I haven't tried all the debugging methods, I'll see if they help. (on macos m1 ventura)

**Comment by sunpig** [comment]
I've got the same, or at least very similar. I recently moved my library from an old Intel Mac mini to a new Mac mini M2, Ventura 13.4.1. Jellyfin will run for a while and then just freeze. I've switched to running it in a docker container for now, but I can't get it to present itself as a DLNA server to the rest of the house in that mode. :-/

**Comment by haddnist** [comment]
> I've got the same, or at least very similar. I recently moved my library from an old Intel Mac mini to a new Mac mini M2, Ventura 13.4.1. Jellyfin will run for a while and then just freeze. I've switched to running it in a docker container for now, but I can't get it to present itself as a DLNA server to the rest of the house in that mode. :-/

Hey, are you able to get hardware acceleration for docker container on, if yes then how?

**Comment by QihangYang** [comment]
I think I've encountered a similar issue. I'm using a Macbook Pro with an M1 chip, Ventura 13.5.2, and Jellyfin 10.8.11. Every time there are some updates to the media library, Jellyfin has a chance of completely freezing. The web UI won't load, and even quitting doesn't respond, so I have to force quit it. The log contains very little information, the only thing that might be useful is:

MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.

I've tried many methods I found online based on this error message, but none of them worked. I suspect it might be for the same reason as this issue.

**Comment by felix920506** [comment]
> Hey, are you able to get hardware acceleration for docker container on, if yes then how?

@haddnist Please keep discussion on this issue focused to this issue, thanks. You can always reach out to our Matrix/Discord rooms at https://jellyfin.org/contact for help with your configuration.

**Comment by Thomas-Z** [comment]
Same here.
I’ve been having this problem for months now.
I tried with logs in debug verbosity but nothing found in these logs seemed useful to me.

Sometimes it will work without any problem for days and sometimes it will freeze 5 to 10 times in a row (having to force quit between each freeze) until a full scan complete.

I haven’t been able to pinpoint what is causing these freezes.
It’s happening more frequently when adding new media (and renaming existing ones?) but not only.
It does not seem related to users viewing activities.

When I detect a freeze, I force quit the Jellyfin process (cannot quit it normally) and start a library scan. If it completes I know it should work for some time. If it freezes, I quit/rescan again until it finally works.

The server is a Mac mini M1, 2020 with Sonoma and Jellyfin 10.8.11.
Users use the Jellyfin web site or Infuse.

**Comment by eherrm** [comment]
Also been having this same issue for a while.
M1 Mac Mini running ventura (persisted through 13.1 - 13.6) / 16GB RAM, 2TB SSD with ~1.5TB free
Jellyfin up to date at 10.8.11
No extra plugins.

Debug log doesn't show any specific errors when it crashes, usually just the last file it processed successfully and then everything hangs until it has to be force quit. 

Interestingly, I recently for some reason I decided to start adding music to Jellyfin in the midst of this and it crashes constantly after under a minute for each library scan. I kept thinking it was a corrupt file, so I removed them all and starting adding them album by album. If I add an artist with 10 albums, it crashes. If I go back and add the first album, scan, 2nd album, scan, 3rd album, scan, etc, then it makes it through all the files it just crashed on (same files, nothing at all different). Subsequent scans will work fine, until I add too many files at once again and it crashes. Doing them again in smaller chunks, it makes it through without issue.

Real time monitoring is on for all libraries, but it crashes the same way whether the scans are manual or not. Forced correct permissions on all files in my media folders, no difference. Uninstalled all plugins except the stock ones, no difference. Files are all accessed through direct attached RAIDs (OWC Softraid volumes). Disabled all metadata grabbing, and NFO saving, still crashes. Doesn't matter if anything else is going on or it's 3AM and nobody is using the server. Host machine is not overloaded – plenty of free RAM, CPU/GPU available, disk space free, etc. Tried all the things I could think of and keep thinking eventually a jellyfin or Mac OS update will change something, but it's been a pretty consistent problem for months.

**Comment by Bond-009** [comment]
Please test master/unstable as the issue may already have been fixed

**Comment by nothing2obvi** [comment]
> Please test master/unstable as the issue may already have been fixed

@Bond-009 Where do we access that? Here? https://repo.jellyfin.org/releases/server/macos/stable/

**Comment by felix920506** [comment]
Clone the repo from GitHub, open a terminal in the directory then run `dotnet run --project Jellyfin.Server`

**Comment by felix920506** [comment]
@nothing2obvi to run from master do the following: Clone the repo from GitHub, open a terminal in the directory then run `dotnet run --project Jellyfin.Server` (you need to install a dotnet runtime first)

**Comment by Thomas-Z** [comment]
I was not able to check with the master/unstable branch but this problem still exists with the last 10.8.12 release.

**Comment by Bond-009** [comment]
It isn't fixed in 10.8.12 due to the newer SkiaSharp segfaulting

**Comment by samusaran** [comment]
I have the same errors on a Synology NAS using the official docker image (10.8.12)

```
[2023-11-24 18:48:26.010 +00:00] [ERR] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 14) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.295 +00:00] [ERR] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 8) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.295 +00:00] [ERR] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 9) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.296 +00:00] [ERR] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 10) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.296 +00:00] [ERR] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 11) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.296 +00:00] [ERR] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 12) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.297 +00:00] [ERR] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 13) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.297 +00:00] [ERR] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 14) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.297 +00:00] [ERR] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 15) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.891 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 8) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.892 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 9) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.892 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 10) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.892 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 11) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.892 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 12) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.892 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 13) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.892 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 14) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.893 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 15) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
[2023-11-24 18:48:27.894 +00:00] [ERR] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Codec Type "attachment" unknown. The stream (index: 16) will be ignored. Warning: Subsequential streams will have a wrong stream specifier!
```

The final result is that the media has PGS subs in it and Jellyfin does not detect them. this is the probe for one episode from that series:
```
Input #0, matroska,webm, from '.\Kill la Kill - 1x01 - Se avessi le spine di un cardo - 1080p v2 by stress.mkv':
  Metadata:
    title           : Kill la Kill - 1x01 - Se avessi le spine di un cardo - 1080p v2 by stress
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-05-06T13:22:18.000000Z
  Duration: 00:24:28.28, start: 0.000000, bitrate: 13080 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 269.186000
      Metadata:
        title           : Prologue
    Chapter #0:1: start 269.186000, end 1362.027000
      Metadata:
        title           : Episode
    Chapter #0:2: start 1362.027000, end 1451.992000
      Metadata:
        title           : Ending
    Chapter #0:3: start 1451.992000, end 1468.284000
      Metadata:
        title           : Preview
  Stream #0:0(jpn): Video: h264 (High 10), yuv420p10le(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps,
 23.98 tbr, 1k tbn (default)
    Metadata:
      title           : by stress
      BPS-eng         : 9195038
      DURATION-eng    : 00:24:27.008000000
      NUMBER_OF_FRAMES-eng: 35173
      NUMBER_OF_BYTES-eng: 1686149350
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-06 13:22:18
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(ita): Audio: flac, 48000 Hz, stereo, s32 (24 bit) (default)
    Metadata:
      title           : Italiano
      BPS-eng         : 1523650
      DURATION-eng    : 00:24:27.616000000
      NUMBER_OF_FRAMES-eng: 17199
      NUMBER_OF_BYTES-eng: 279516700
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-06 13:22:18
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Audio: flac, 48000 Hz, stereo, s16
    Metadata:
      title           : English
      BPS-eng         : 784399
      DURATION-eng    : 00:24:28.224000000
      NUMBER_OF_FRAMES-eng: 15294
      NUMBER_OF_BYTES-eng: 143959272
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-06 13:22:18
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(jpn): Audio: flac, 48000 Hz, stereo, s32 (24 bit)
    Metadata:
      title           : 日本語
      BPS-eng         : 1549119
      DURATION-eng    : 00:24:27.007000000
      NUMBER_OF_FRAMES-eng: 17193
      NUMBER_OF_BYTES-eng: 284071217
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-06 13:22:18
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(ita): Subtitle: hdmv_pgs_subtitle, 1920x1080 (default) (forced)
    Metadata:
      title           : Cartelli
      BPS-eng         : 6756
      DURATION-eng    : 00:24:25.547000000
      NUMBER_OF_FRAMES-eng: 102
      NUMBER_OF_BYTES-eng: 1237737
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-06 13:22:18
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(ita): Subtitle: hdmv_pgs_subtitle, 1920x1080
    Metadata:
      title           : Dialoghi
      BPS-eng         : 66872
      DURATION-eng    : 00:24:26.048000000
      NUMBER_OF_FRAMES-eng: 662
      NUMBER_OF_BYTES-eng: 12254767
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-06 13:22:18
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6(eng): Subtitle: ass (forced)
    Metadata:
      title           : Signs & Songs [FFFreeka]
      BPS-eng         : 1208
      DURATION-eng    : 00:24:26.980000000
      NUMBER_OF_FRAMES-eng: 1812
      NUMBER_OF_BYTES-eng: 221688
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-06 13:22:18
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:7(eng): Subtitle: ass
    Metadata:
      title           : Dialogues [FFF]
      BPS-eng         : 1329
      DURATION-eng    : 00:24:26.980000000
      NUMBER_OF_FRAMES-eng: 2203
      NUMBER_OF_BYTES-eng: 243824
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-06 13:22:18
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:8: Attachment: ttf
    Metadata:
      filename        : 123-and...-Regular.ttf
      mimetype        : application/x-truetype-font
  Stream #0:9: Attachment: ttf
    Metadata:
      filename        : Babylon-27-Babylon-27.ttf
      mimetype        : application/x-truetype-font
  Stream #0:10: Attachment: ttf
    Metadata:
      filename        : BeeMarkerInk.TTF
      mimetype        : application/x-truetype-font
  Stream #0:11: Attachment: ttf
    Metadata:
      filename        : Franchise - Extra.ttf
      mimetype        : application/x-truetype-font
  Stream #0:12: Attachment: ttf
    Metadata:
      filename        : HiraginoGyoDS-W4.ttf
      mimetype        : application/x-truetype-font
  Stream #0:13: Attachment: ttf
    Metadata:
      filename        : Painfresco-Italic.ttf
      mimetype        : application/x-truetype-font
Unsupported codec with id 98304 for input stream 8
Unsupported codec with id 98304 for input stream 9
Unsupported codec with id 98304 for input stream 10
Unsupported codec with id 98304 for input stream 11
Unsupported codec with id 98304 for input stream 12
Unsupported codec with id 98304 for input stream 13
```

**Comment by smailpouri** [comment]
I noticed I have the same issue on macOs 14.4 with the latest stable release 10.8.13. 

The lockup started to happen after adding a folder to the library. This time though the folder was from a different disk connected to the Macmini m1. All disks are USB disks. 

Once the folder was added, the lockup happened after a while during the library scan. I'm not sure if that helps but just thought to mention it. 

That being said I'm unable to truly use Jellyfin remotely, as it keeps freezing. I checked connection speed, CPU workload etc.. nothing matters. Even the download speed is extremely slow. 

I guess I can try to do this through a VPN connection.

**Comment by gnattu** [comment]
We are going to have native Apple Silicon support in the following 10.9 release, once release can you check if it still happens with that version?

**Comment by felix920506** [comment]
For anyone before and after:
Please test on the master branch. Please stop commenting about it being broken in 10.8.
This is very unlikely to get fixed in 10.8.x (assuming there will even be 10.8.14 which is also unlikely)

**Comment by smailpouri** [comment]
> We are going to have native Apple Silicon support in the following 10.9 release, once released can you check if it still happens with that version?

Will do, thanks

**Comment by nothing2obvi** [comment]
> We are going to have native Apple Silicon support in the following 10.9 release, once released can you check if it still happens with that version?
> 
> 

Will do.

**Comment by felix920506** [comment]
@jellyfin-bot rename Library scan freezing on macOS

**Comment by compufox** [comment]
After 10.9.0 came out I took a backup of my mac mini and updated it to the latest version of Ventura (14.5) and I have not been experiencing this issue like I was on 10.8.x 

Been about a week and things have been running smoothly afaict.
